apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - factorio.yaml
  - monitoring.yaml
  - network-policy.yaml

configMapGenerator:
  - name: factorio-bootstrap
    namespace: games
    files:
      - factorio-ready.sh
      - factorio-save.sh
      - render-config.sh
      - start.sh
      - verify-saves.sh
