apiVersion: v1
kind: Secret
metadata:
    name: netbird-policy-credentials
    namespace: tofu-system
type: Opaque
stringData:
    netbird_token: ENC[AES256_GCM,data:dKa7aoZAuD9gdZGaXn56Vj2c5WkiX8fyxt1TX3B9CWW+U6cJaWFauA==,iv:roafjVXRzazsvvipPjalpf7CQbBgjhAIbQqQ0sKgiYk=,tag:eALZw1t1+VWsbhuAP7SCNQ==,type:str]
    default_policy_id: ENC[AES256_GCM,data:ZDMtiAsFlVJpPAzq+w2KZElAnCo=,iv:ktyL1D3MrNWibirVVJC7QLNJXqxXGRkxBYvM+yMsacU=,tag:al/wNyZMyRuMk4unQJdTxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNU8zOUhjeUd0NHpiWE4x
            bzlnR00zQUFrODhpd0EvbUgvMmJXVEowRnlzClBZSUVDTUpjcWFKamFIQlVoTmRr
            R2tnTVFqK2RTeGRNaktUcnlOZFpwQTAKLS0tIDZVVkRKQ3lTSUlwb2dFSkpPWHpi
            aWd5OW5jamEvTHJOWVZNZDBPUkVXaHcKarY8TqOzH1wCp+atYHSJ40M8uphm21Mi
            GFeOzl+uRZSt3ExCBV+Ii9RcvvKExDS+fQDnyokfQgJcc5T875DtuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOFJ1M1phOHBCVGg1Tysy
            N3NmK1hjMTVEekhUbThJNXlXRnlGSDcvdzBrCmljeElWVStvdHRwczJPbk1uSHJm
            cVpFVy93Q0VEandXNnhQTEtOaHZjcXMKLS0tIGNsY243Rk4rZGNaYUdhcTUrTEFx
            cHIrSHZuK0RPL0Q2WVhWT1V6NWZwUUEKEbCBtyn/XKA6ZdVy1ADYggCZ9AARQ3Y5
            /yJuBHMV98XVr791iE1XsjX1SZ+jQEffc7ykf9FExvYaywe3FOPKlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T18:32:21Z"
    mac: ENC[AES256_GCM,data:HETjR24n/YVZiHyPv7U79ndbySTk46qwTTudzzTzQbEHaK1j2cgn4wbjpXwIfi0gJtfe4D+iwfzZD0hrg4hhEI8ndMCTKO1zjga02kOk5Hs1g66sLr8L1u3ZLjkHY7uKpJTtEcVhQJ4+6Wke/UXoDBPvqlAvxhyALfW74EbP7ks=,iv:vEsBOFwKH/cN1LoAeSJJZNvyMQ4HOjx0NnRZkkybbhY=,tag:CCz2ee354qR2T/TwykLECw==,type:str]
    version: 3.13.3
