apiVersion: v1
kind: Secret
metadata:
    name: automation-credentials
    namespace: home-automation
stringData:
    homeassistant-password: ENC[AES256_GCM,data:ENzdAnaJdKmH0RfkxxP3VJrzixKLH10TnzCOtzO/wJEO75XxAmf4yL3L/Zf7GHDR,iv:NoKFZMPHAkDaYUDxE0C393W3dyVLA+lLnYBeExos1mM=,tag:FnGC8ejOQfcgArZ1Zdu3uQ==,type:str]
    monitoring-password: ENC[AES256_GCM,data:zs2XGdFBJ23eKNIzLOv23gqt3fVg2ty2trz1bdtgYhdBsHLLHD1FsIFYdRaRgCiZ,iv:cVxH72RYuYVf1OdXo72deSaBNT2dfzBHcHpsODVhlyA=,tag:vaieKx2kDS2PvqQHX3CKCQ==,type:str]
    zigbee-ui-token: ENC[AES256_GCM,data:sIK0qxYfjB/YGUG0i1uaRzh7o5wEIPKS80zUld5T67oIN1sZuhoOCTIurOEhbS5O,iv:4dS1FWbpH+W1fo/LLwQKUW3FzdWNrUg283rk0LBkpQc=,tag:Pt6jlLfCEm66oLafaAPTJw==,type:str]
    zigbee2mqtt-password: ENC[AES256_GCM,data:Kh8R5g34na1Ve0wOFFLCvNABqjJuN4on8jemPaKBaGRvabnEjmSX9rfgfLr69xdY,iv:1Vj6YGjk926pa1CguxE+2lXzpqMvJdRjH0UlIUM5CX8=,tag:ZW39nE3/O5hVg6IXNtCjRQ==,type:str]
    nuki-password: ENC[AES256_GCM,data:BO5Tt2KlZeXXT4LlevXpDRBOTDpgF21B,iv:cIzS+STcwodILw2w0gFSoMZypVuqZV5tEsnkFbZU1U8=,tag:my7UkL/cU94hzVD1T9TQ2w==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQjc5RFdIV1g4VkJXbDdn
            NFVaUmNsdU1YbEZwUmZUVkdZbGhXQUxRVkZZCkkzcjhRSytoZUVuTFB6TXpKRHVu
            L3JTQ3Z6TUpDZlJXL05LU0tLQkZIMEkKLS0tIGhGK2dXMGFobFVBNm1GbW5oVGxQ
            ZG9lRElTRE9mbTFwYysxdUpaT0U4L3cKERgsO2mLX5qYwZtcAnDi0Kg6arWJhLBo
            TR9gn+wXPCbYV6HNbr/CyfmKJvgr7K0O0BljP9+IWhFmiJ+G/MzcJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDelBUZEtUZi9jTTN0TE5E
            bWs5clMzQ2xuSVNJK0pSOXlLU3ZidFJPRkcwCm5MU0crWk10RGs3bVh4dHdGU0d1
            Qm13VllOK21kWW4xVGlydDJOVXl5TzgKLS0tIEdYaGVGVHlncWNUb2NFZ1RqVkpM
            Njhzc3lsRStwR292dUZCUk8vTlp1ZjgKf8f3NTM4/iT1F5cdaMmw2lZJ3NrUJVZw
            rv1r6pYbd8JM0AUAPqkgQ0SpfWKM4OGMG6sH0maLIeVOk4Wk05Z2WQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vfxeaxdj7jze5p5ytff0peyjm3rusn8naacfudklvzwknv4yk5wq3qqg3v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T21:19:05Z"
    mac: ENC[AES256_GCM,data:kbT6OjwEvM4djDGgPhy6rIHRv4emyW/9yvoY5jLrFFcq2FY7ss3+szOAyjd3UQK15Jdim+1Nd0CUdUJhnB0zxnUKzHz9wOigqKOkZWP91mpLBeniRUlseZmovQY0qh5Pugg4almLLKsaHWKPAaMT7+a1Ht32+QnG6SAdbBbunBM=,iv:PoQPKAlqtLDmtMmbzUmmRjLXQ8h0lLYoXfjMWxkpgw4=,tag:mGdX9/aIHSn7X0tzRR2XkQ==,type:str]
    version: 3.13.3
