listener 1883 127.0.0.1
allow_anonymous false
password_file /runtime/mosquitto-passwords
acl_file /runtime/mosquitto.acl
persistence true
persistence_location /mosquitto/data/
autosave_interval 300
log_dest stdout
log_type error
log_type warning
connection_messages true
max_queued_messages 10000
max_packet_size 1048576
memory_limit 67108864
