apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automation-state
  namespace: home-automation
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: rbd1
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automation-backups
  namespace: home-automation
  labels:
    backup.fahrican.com/verify: automation
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: rbd1
  resources:
    requests:
      storage: 20Gi
