apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-database
  namespace: finance
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd1
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-logos
  namespace: finance
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd1
  resources:
    requests:
      storage: 2Gi
