apiVersion: v1
kind: Secret
metadata:
    name: keystone-oidc
    namespace: openstack
type: Opaque
stringData:
    oidc.conf: ENC[AES256_GCM,data:Q/65thCyfBBGv1sAe9qGZi7SgoRpQWk25sgzFf/SLqibhkSksVI+es4rZBCB1xqNpfBFTmzK89wn0xx4+RJ7StlgG1cKJvGTLpJ0D63v3C23oW3dg+F4lRlfXPpQJhQ9NfgX6cvlPmgJHSBp4gEQAptmRbzgU+2wvafqMgz5rCNbJKDL4hsqZteqTa2V4fN5q0VA1XiVt2on8cVQ4o1ehj3KRS1xN2VUjuK6dbSKHc+JC92Zedb2UVNgbi1vNHWlTknxCgaTQNCUsAhS23TZzlZ13qd+qoGCvykyGFqfZYJUSByojZ7oKE89BmCaMBC7zWasi10LDseRoL0b38NOlrNf+3L7cDHmVt/SmHXqKDgkfJgZyp3CZE6dnCp8QR5quKHf2Lj37ngQQL/KMwDrNcYnQCOg1vMoQZ7DVZ3mJAqJQJis5szAUMdiGuYRAECGQS5mpL91oPnIK4FemedLsaL2nbIVmxdodGePqokkD+wdTUaG1RtLhLP4O1SPGGbtIiAOgTdEZGNuEo8QRVOg2lNxqhN/FI480CEgHH2qDoEAjD1AgVu7MjbpwpzGIX5tKRNUzNK/O1Hwy+sAqvPeTfkdBrwh2uSgRpIEOgabFMmJqr7GSOOflWFDFLjYYIF40kKobLugC2chkz69tK+gmeLyRBJOHRI+sNzXJjqAhI/f1Yp6jOpseNylVBWFbEsuL8+z7i+XZdgCsGlzAhArXf8ObDq7MeR/XtsFvPYnoP0D25DUKot/PcEg5zuTmaZzp4P+isVgzRDsYXiUm0b64Bolrt8O2181fHnPJ2rVIYEjVgwJ+hZfJae+cXanLkFyREWBC3HNdaRNQQnxKBMRogyKJk62hLTmCuWJloOUs1WgFBrld6bL14dVyhKIPFCgAzkAwQ5Z76Z3FxvyGATijpLJpveQ6Iwm1lxOGfvrEEhczqKBt8F0T21pWw0gEj4tOhfP9a7Wk8w7vgVRQcHQgoeNimcUldtuzrlZ4fZZ5BeESkUFecGESaOeaolo1kOefM1OmWsHL+nqdEAll/pDnUUyPBXXm/zAJKCuFG3OvPf8QpGdSUFR/ZCGPi1/QRaEYhfFymeL99olvXlGmYutIzMgxavvMwIF2Bb4rlMpEz+0LGo9NKvJ26LguGCNsjdYCaQE1LXBgguZcDik09WnhJB6gYyKdkcaN2Subq6pQW71BQNb9Ee35IozXykVAkCmFndSk5IvAlZtgoPeC799zpIlpaZcIb400c+MtUdy4577dVm8oL0cqMkm1eZjEf69h1mL+bs8vxA6R3SReotz5O9Ft6KghTawECTYvJNHnDxg3rjPKfigfQJDGknZ9Xn1GshcRhEaYWwtL51XeiRlOPcZjr8atJsfnGhVCZXMwqkMOaeHO6pHFou7XYshJys4Qm0D1UNEbfiDESCnvVVlUrxUayuPCdcExNZMT7dwHVph8hEdAuFmTEFBncOXIoCHGWNw1IsMFxjxxgQLuitjP3iL8x81fmmSdIlpow/YjZwI0F4dThuN8VUDLFg8hyRslpm/potwV6lFI/BtKnID/7j3GPa+dy4d5bMbI3proDjdD43wD4s9iCvWVAYTwo6KP5F5oEn/8xo9TWHmMeDgp3DGsXKqLnZVAO8KpopjFcNPFl6M7g==,iv:raYPLCauMIylSdUrIGykqMYVc6h42QllHgrSsb2S/Ks=,tag:RF3H2tlOfQdXYU1nMjXCmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMnI3RlNMVUFRSUJlc0Va
            TnE2SjU3SDdiU0JKSVprQlIyOGtWL1QzVjJVCmc2TE1HMjJyZ3NYWWpNQjJ4TzJP
            ZVdQZkFQNDhGdTlzOVA2c1ZVMmZ4Z00KLS0tIHlscjgwMVZqZC9sdStPZGhYS2s1
            VTA0cEZKZ0dXeDNoT09Sb3NoRUxRVDAKRIBPq7Upi4mBIuNDARxV6u7rDQ7c7sF7
            +RPyTBT/E643sNFsEVuuIZsUduu5rMsK57wpknQgWsi0kKMFVEfj+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVWJ6MFY5TzhyS0Q5Z3BH
            U0t5ZFBKZWZqZ0hFUTJlUU9aL2lVTy9lTXowCmY1bkhTTkR0V08rRkVpK2JvbEZi
            ei9MK2ZZMTdKSEMxMXcxaWpwcEN6RFEKLS0tIHdkRytVQlNoaytjeS9DMFM5YVk4
            WWtrbWNjWk44VDJhQjhZTXpZWWllOXcK5xNLmCQ32Haf+LdOGczd+4m/AUnkYxRX
            48of2BDhdoG08vlSti7I8gn2xQM9mkbjNcyQjKD2GEDf+13P2nK2Cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T22:11:59Z"
    mac: ENC[AES256_GCM,data:MlBUGRV6QLeRmJsFVS7pWQX3Xx1Quf7h9VIUXMNzC2oVlWCF1+h+w841/q5o2NwQiumJL9/Y3m/54sfnDGu8BcqYw4dbQ32DItMMpf3JOqq0o+BFFU63XR6nrHLbMu2tVvwbK3ZngT0qgRMFQIjpeGTOAF49F5cm5c0kSOiM1p8=,iv:tUOHOx2nK4uwfq/NXqO+iHSCYc7RhP6nNBa36S+K3sw=,tag:fEPyXY5igoep4rl45SsKaA==,type:str]
    version: 3.13.1
