apiVersion: v1
kind: Secret
metadata:
    name: keystone-oidc
    namespace: openstack
type: Opaque
stringData:
    oidc.conf: ENC[AES256_GCM,data:lgoijXSmma4Ta2mRDYB72owwc714u3ggJR8i7SdrROLCGQxuKkjWakEiwE0WBiv5uo84MchCjLVE5HiKIJr2ZpBzKYr6KHP5j7OgCCqZGsTh7PT6x9V1+HoJ7KGa5MrimO2wNSZFzN9SirhnDBEAOlvIG8rRvK8lpg69GeN3oX/B4/3/lXxvCbgQCIf6wCZUh2CWB28iejElI1ysOFOunGWNFSfxcSrYtcXHWGHVdgZFOM4F4BcpBC3Z7XIsPllq6UnsbN5TWwbG/FOUC7oOis1GsmwKUYxBtt+QS3tSKlVxfpfOLdURFy7bsOpooZZWy2CF+PI1RfLd4SXwZGT8rjYDe2XkKG2B8LIpa+7jO7pDP78EPtKYqpsBzpiU47AMtIUd9X15bSwA29XtwOTcafAeAt8kDdqMnEYXzI8JYWvCe1Lo5fL8CS+AHAqokCPKctjad3ixE0Z9N6Z+E19HeUxtJ10R6H+1B+XhpENVIFKKWxXOvF30CWpc6b6zaFyOUG92XF8v45BAuZgIJbOWrhrFkva3RnleP1aBncFZZXp5pt8JsdywaFYdPH5mDiWDi9ZOJrMbX1IVL7DrWdlqlQmAHzR8Xs/s19g25Q2r8WT8DgXQ0PdZ86Yc4zgDqeL8AB1LnOEB79DWlX0i6HnX/Oj+6m8VzvyViOLG8LrOpGWXJiHk9IEZa2B/2eKQqAYENXi4slYcmR4vIU5NFWcVSQIwHs5G7s/KgRALXVOEX9hktCvYkRJG/a7EcJSrUcLSv5qdNTzQrt66OvDY4691ulHrDkdCKTJ3R/L90sFHrtpu6xL/66f+3EioJWbGUdynxh2udP7MFss1ufFjx+F6velwWoFiRIWflFclWupToE+Gw+l7qIrXVlf4DWLu7069xE0XTqAQ1Sd3w6vUsyv70vFBa3Bxp7pxTZ+hQVR+aaPRh3GwSIMR/JGVycVGhc208kgkWFP7N6r4026qNGvfcUIfRzcfN0TotdHBI82zzrA+OgyBP+nVoWN5KYfM2PX8p7qf/UTNPK16rqezrvXtE/rBGLOGa7yvsl5K9ASxGvcA6ksgCAMGWNf8/WcjsZcqJ8dB+Hz5v06//oCYxv7Crrw8GSGnnmYr/3b3sjau3iiLxZops9XCdfMi06u7kYeWh7WvUEUgrimItTxvD4QK/wMuw9RyMxHHnkE+1V2R2XQuajsCL9WYQmAr/7IIBC9oiqNOmBdW3nTwNlMt2n7GHT7LSwCMSOSvPQeFrLNE9noEJIL9jHkKtEYMUnJABY1Pz9ZPbacxsAXdZOtSuv79wJL4cOfibARc5u1WJwp5x54qasWS7Oj8Gwarzb04A0YHXsTnEGnKHepZYo9Jx3Bbv6F5dOl9wkEVUBIWFR3m3o4cY2TNtm5FalapvumDnBYjLv7knPO0pRKVA3LPp+GOHGzpSg9qo5AuiQIh+oP4kJee3sBnRD4eSloeTiOd1QkseolMIaQIIR7o8XI7ncFVFeFHv5M7g1/Zs/ToBzsrmuJfT9/2HLGwcPSwFug6w7Y/1cMlSBwn/izfWkR8Ea8+df9L9u7lnCJ88H2xjLrcBXHuBuSisBSdT6easJHzS8ZKwUJPvb6/TSMrQtcnCyYVWakq2I3LK+bpYmpal1Q7gdxRQmPKyA==,iv:zkOpn2/ZAdrhTtQQ1nUfyOULKtqntSqdmKAR/x5RA+c=,tag:+gD6gVm6ewehz0n4DS7wdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ0F6bUZUYk5xQ0RVLzlw
            N2VOOGNoTGpWcWUyYzhKZDI1TXRNelNydm5BCk0wTVlBdjc1cjlXU0p6eW9mZFFC
            TG9NcjdwM0lueWpxMERoTm5kbDBsVXcKLS0tIEJGQTVaa1VsdjlrZk5UVDl0VXVJ
            cFp6aHBJSjhOMllwSzU4MVJReG0rQkkKXQEeqp5zHGv2Yqs+Kj/vdX0cfHlGxlo3
            8/XRg1x+1ya0f8Q2q4Fv6mdliOBrNLoX6h6J+sZEpTirnb9OoyPlCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTTh3UmRQWWFocXVLRkNm
            YStOVjJxVmUrbzMza3pML1FvNDFhWk0rcmxJCm1jWjdjeFhqaXNkUHBZUUlxbmh3
            OGlKZG5yeFRPUk5xSlNQK1poa2diRHMKLS0tIGZJTGpGRXMxM1YrUTBONDdnNGlT
            WExsZm5aZTB3SWYyRStEN05kakFLWTQKtFC7rs3iOWQJ0GL4IObA5q2pzVamVTMi
            VO/v96Ad9kPJJS8X/lvT2pImJ4GCWfCF6VgormfD/cUxMQ7j6tlfhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T18:13:43Z"
    mac: ENC[AES256_GCM,data:HMK78H/7x3MGHZ1b6nHRmh+aX8YEPyN9UUoUtBe3y2fw599B2tZecRm72L8H7GTL0C7R10KaynSGHx1w+u0J5P7b9DOwzrI/5bN3S48/nNNXQUuAlLIGNDwtAvRy+/wVSVDUg9KrLDIq8J9GhY3hTcfHM82MYVy0R3tLvsnp510=,iv:o3RU8pFYfEPldZzOzbslXCosludEf1qsNLUx5qNP0Pg=,tag:A89Brp/s3UQ5/UCACJI3Kw==,type:str]
    version: 3.13.1
