apiVersion: v1
kind: Secret
metadata:
    name: keystone-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:ebwsVH0CmQ1CfXSr6dmgAjV+LYJZ42txbtsQc2VdNkeq+OkyjneLvzWjmXXM2FAfkF/gcDmkqSW9LzyrwRCH+JOvXwcObx4LoRw24QbcQ5HHTIGMDqT7PIwyZ8w63tt96Ou+ta2+e/WPp5UzBJkScmTeUkJ3TnOl4fFovWGjq4SdK8TEQMHQT2GvV3UPNBjtj9+ToNDn+kcErMZ1Rtq0fV5NlDb7uL3+QS9JTpXKumzgleOpC0J1oXNCd/6wCJUESAzF6VgRFRHgeWzHINHU+VP6mBNWGIJh0aA4Yr2vHWCejBMmKac6Z0CCmU0AbLJJHuH5IDMmuCF3MEiN+gIq1srQvrErRaIMvwlsJ/OLqfdlx/EDR5axO9bjXCFuYRkmnV19Bj5lJDeK9QMyZ8kgMrJWOuc7Ub006vQpFdcMFfGV62hWyWcC2XTMZ7noF6dGIlgNd07SWwYdKSQ4G6vEfXcZpE62EgU4knggaRoBlsF6SsiobtqpcgFSszhIsIF77gdKFMAJBbFYrQqnMWAZuF0R1Qp3zNYKLVEFCZoNcCncYd17lvvxB+AtPfV6RdRD55gOmcK43JzshLuORKi1Io6rpppLwg/F1kgcloR65MmetUs2kew0HBlfpGTenrBWCyOHLu1nExTXsGgBAIuGZSn98ybA9UAUZKLZU9EG0zqaeXA7fCIrmJQlqUk6mQS7d0+uuDfZBGSz2qbGHzTNgAadNOuvfRZkN7RU+8OfdoU+u9UZLcYS5oypOjUUhukHbgWrOxCeKdIBDjSvO7+JGhUSARwbgd7Cp3xwlFkzz7jRsRvAKViCoeN7JnanN3UsEDmMOcZWEEgcr1wLobAPQFDLvoP8dkoEzkW20DTY5as2rP0bcKsQ8X1jlMfK2qi7wyAifArw9HIrw4umHZs8mCXK,iv:k8YcEvzZOMVDlPnaHuamUAM9H95huCesdl27Q0wJOzQ=,tag:28WjIeqXlAuTO+l+q0FV1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxajYwQWh0Ty9YRUplTHJP
            c3VPcUk2OUFxeGFhRWVFRThKQk1kQ1ZidjJJCnVQQ1g2aDU5T1dNMEdPR0VjMnRY
            QTU3dWRXdml5VzI5bWxXcnZVQ05ES0UKLS0tIFpMc1ZZbjREa1g3R1YvYktwNnUr
            ZkZVaE52Q1pFc3RRdzBTRXI5MUZrRVEKJItQhCnq7Bamojn69fhMctBOkbMp55IO
            hc9j7rHjOSO9D9zWJq4/d9fcPU3zfJAHqMTzB2PUpMPVxq/l0mgSQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aEwvSmc0QkxtajMrVmxz
            NWRlcGplanR4YXUvVFJiWm1VMHRrbC9NeGhjCjFIek5ZaXo2NnhQbk5vNENya1Bh
            SWh0ZFhqMnBIUXZBNGdNZFZmUGhmQU0KLS0tIGFNS1piNWFSZG9XanVOcWxqcWFL
            MjNKaURFTGpXcDhqMDRlMDFYVUpjNG8K6sdItLq0Ea63ZJM5bCK2KeX4mm1qIXeS
            G1s/gEN1moPLq34bhdn8VQFEezLj0lRHLrYc4KA2zzQei6d1CGOQcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T00:01:03Z"
    mac: ENC[AES256_GCM,data:3A0qWZHQa3UFGNnuiREAPMzEVzlr48geWRXZehl7JJejPc45t6AaUzwMjaEnDPKnuRwZOu9p+svE6Dts73ALDmf0xWRq36GlFYla5rHQwcBVtlCXRmjnZQU9hPCQXTFzONDy2EiFQHyyjnnRjINvf2GIkolAPFureD+Lg4IgeRg=,iv:DGFcsWrdcvtm8ZVZOMEX2844FJOXtEcPoJiv7B+70rc=,tag:tfeMxLQOAg4TvaBeuVXlig==,type:str]
    version: 3.13.3
