apiVersion: v1
kind: Secret
metadata:
    name: keystone-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:+RHuA/b9Il9P62gp89qIW8/RNU/zyVLLkZ/ki6BB+sds0JuDRS0+jZ8Wz31+YTIxEt2CZ5wGi0rdvjee28MYPjap0l6f68BAdRvklcG6NyUcNHxD5YW+/K6HdmA0vCptkLzdq1CxoD46FwJcTA5+HrK5Bq5bNXuG/S4ndtnjjTjygg7ze9CIJmWJAhDvWMN6dEEN3dSLbwOvedh7wIGfrPMIAa6T7HsvO5lnfdFLbeZjY6ztsdicwjeMAbpf0B9ySaaco3Z1/vNQ2wHxLkY8JchXEOpRZ5WA593WM+YWNIJXdAqtgvl4ppWevvv8AkLkqH1Kvr5DarwpwujqJZks0sXnK1sEIncFc1X0lSdZpzR2Flj2WxezUoErm3ICIgVJvzFh2TvqhuK486KxT12RoHFBYvnu1BcrtGO7vYhYZTlecd6h6jYBOx1wznaawJmEBkxvuF2uFaskSRjMJ3KZg/94ehqIiragrO9/kleHYUhcMKiuJrjqdVi4At6soO1q5s2hD57Cv5T9Oo3cHwePzB4rpVUvunjy+B1CAeGsSKvTkysrvs6+26WiTfa0rJg6gVbWytIG/RfywABoEAwhCj+IaFHeXTKMU9x5RGfmaZoJDPTGvnwzud+raOUaoEuu8LeeR9w+3+yPNaIZJt/XdXPV07yBPXelRIaZq5QM7HCI1X5wmNL8hlyFhcLYYs/axvHqQDLoHtoSDfmLmQ1IYh9H7TUMCxqpLuhUFhxzUf96xFFQpLjMlp/33ceAIEjd51HaR6n/ZNOM8+YbKrkQ7+ITRKEPbbw7cSAllP3jl6O2liNNpu1iW44fDlNAHWa3zfnEAAVSqTUpU8rQD7nkq3yVjwNs4m2JgnpMYY5tLADOm9ACp6eN8yoDWJytkZ2DNUmPidVpU18t57GDM54YqvyG,iv:2Oa6/u3XYp9Uz3+fvb1PVZ6X7hx+Vz7i3o6RIWz4NhY=,tag:esGE7xsjjzvFSPMoSyRHkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQ2s2NkNjclBPT2dhZjgv
            K3pOUWVZNkQ2dUxSZDZCOVRaanhtUy9MdmpnCm1nN0F0UEdvRFhiaVpoZms1TEYx
            d2ZiQkRjOCtTb1ZkVVU5RTJMWVRoa1kKLS0tIGxoRXJ2L0RiQ0tDS2NzWDk4MFlP
            Z0tQc2MyOVBTbXRYUzcwRGNMVHdTaEEKzJ4dfxHC0TQmk8eHPWXdaYd99X8syk1s
            gQegHarAT+oiULytdUqEWLS5ZCZrTF+luL7gu1JwjlDj9mjhIM/HzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUnlGelhIT2pKZk9DWk9N
            a2RMTU1vVWMvejY3eUpIdk1vakdNQVRlL1F3CjhYMVZ6ejMyenZwLzdkRTF2T0Y2
            a2w5TEpRRGhXaDNONXlvQ3RTd1BnYzgKLS0tIDhyL0xXVHBXNmN0TzcraGxTVGZT
            MlJPbytna1YrbFBWTVNzRjRIek43T3cKs5b5GKnfEBx24a/1GhSs8xDgsk75xh63
            UNHrDnM2/Y/0dPgasrqXVTiMngfI0yZp8mSSG88fWHT0PQtp2hQtbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T00:16:49Z"
    mac: ENC[AES256_GCM,data:HJSXRUOU+tlNixNyuK678CRx7M7kZUspqDdm7W78Qjmzbl19Zx3GZe0f7rSTsQ1iMxze9xLV2XC/FMgBOm/GKCpoDf3oPa0a9b/eOic4mmm1L/vnZCT86p8FVcpNq22eGvi1jAUQytBAl3QmpHH0j4hZ0FD5CtxZKCEX1prpXo8=,iv:DVoT6uuRQKYkxx1lLtPPoOmZoymWLW8Oz1gO5dMPfn8=,tag:KD6gs64L3waaJUrSX0ptvg==,type:str]
    version: 3.13.3
