apiVersion: v1
kind: Secret
metadata:
    name: keystone-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:VeGdLsawq/WAv+tYisNP+emK56vv2zvwIyASGHUBy4YxmLXmRHXboGpSdH4yxM+8DKGEoVqzqsD0TZokLqVMhI/i8rXIZ/K4l0AwH8redaoNWGVfyQ/CwCSSZGMcHrFDivrSXhACf7h3hdNPqEdaqWQo4cFFjVVb86WwUat3YZByosuwaK54J9S0W3uKcqf5KoEG1VG/iorVVLuQcATudN/2n3TJaeRTNUgMOWsdfhfK4CrxwHzU7hlcAp5FKUene+Nv77n/LL8daBsTfiwc8XHbVFNIKZI+DNLGkaLO+O8jLZh4IGmcUrq7IcSk1xNHjslGA9LNLF6/eX795mw8HTPWm2+iooaKwCYV8dQDdwy3+OWDx1sMja2YTibFohtbOOKnwTRFJTJxxgWvurL6OpDSmP8JZUhGUjrL9e6F3JIhuiRrYe46w/Xh8LOStt2M66pc5PGcfc+OyZaLf+RXfdpusQeuc8ormzcQEqZc69eEoEH1kAy8STnwvK3Wzlcoq9sZu4X+HokC6XzH/nqXMVredOc13Y0MMXEAxqnyFh3bo7G+ck9eu4BL2YTcwVDfZdeBjB05rr/zs+xdx1duLO6y1vCO62wM87gNqrGS//DijDLkYyo70zha8G2AivBHwcTVdEB7hhiCv4CzaTf1seTk3cXWgM1fFdWm6PgrP6POZDbFsOb0+NnsetVuhrzQF5JB4kuzAhwc2k0TZW5OftbelS4rvpmp4GG07WgdnUzcqR3Ib4528in6Qu5HbNeUuMjBSgWH1LJtwVUBJuTWBGGqUsSHTlb1kA7UO96WeS85HxGgl/abEbz+gajNR0fBG9Vl+6R2Uo+Ctn5rsn97SIY=,iv:tHHe1FnUli8eJln0vV4x+WE5qDAfxsHXPwVcL0YZ7cQ=,tag:jwqMmAaVP17xZuWeBLvFMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWWhzc2RXYmpueUlRa1Zq
            V0o2SFJKaDBtb1BrUEprTW0yVXYzeFZMUjNJCkU4SEpnQjZMek01bzdmQWRtKzNh
            NWJockhsMFRGblIyUlVYKzJyUmJndDAKLS0tIGpZd0ZVMGJZdzROQSs2S3NkN01Q
            Y3dhWElmbk9OczFUSjNxbDVSWkFxbFEKlHcUb7S8IAxItyFUdInfUglIo/rnVgTN
            G29aUAaN/B9s4mxvOO+Bprshdp84L904Un1kbsv7n7KxGLWMM2ZowA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Slh4V21tMUJVTEUrcTBz
            M2dqNDRmUDMzTHRWRzZVd1huMlFsQUZXQW5zCmRoMUZDeXRYa2c4Vm1NNENPeStj
            SnhQL1BhUnNwRGplMmc2Z3MvQ3dOeVkKLS0tIGJhMktNeHQyRXBjamhIVERYZVMr
            aXJOaDd4cjFuTE1VZGhRNEgwZWZUVzAKfD5L4zdrJ4sePrfL4pwz6R6l6rg05Q4l
            i3hXlf9iuLaxgy2NUNx1lifklQQ91SSktyewVeu4oEmIk4GFwDTtig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T21:43:35Z"
    mac: ENC[AES256_GCM,data:KT1WLJgQr43ze4PGYEfnzuPlQLvkNqVKQ1eUNcHrXP1FqIy5wFxiIfxs0h8Z9aSbNew4YRKBCtNy8nLd7QG4ucHmL1qBtJGwBQQDbLm7IRomp1urIpP4WILBg8dUYO08Intj2YjC04FJADq2wOVHdYXvlbEBE+4M1hcRAhs3S5Q=,iv:G6wNCqbzXiLUaf0E7C/2DtXxrSF3ARDRdCRgritABqw=,tag:wd/B5zC4BsXQHSH6aomQdQ==,type:str]
    version: 3.13.1
