[DEFAULT]
metadata_services=cloudbaseinit.metadata.services.configdrive.ConfigDriveService
plugins=cloudbaseinit.plugins.common.mtu.MTUPlugin,cloudbaseinit.plugins.common.userdata.UserDataPlugin
allow_reboot=true
stop_service_on_exit=true
verbose=false
debug=false
logdir=C:\Program Files\Cloudbase Solutions\Cloudbase-Init\log
logfile=cloudbase-init.log
logging_serial_port_settings=
bsdtar_path=C:\Program Files\Cloudbase Solutions\Cloudbase-Init\bin\bsdtar.exe
mtu_use_dhcp_config=true
add_metadata_private_ip_route=false
winrm_enable_basic_auth=false
winrm_configure_https_listener=false
winrm_configure_http_listener=false
[config_drive]
types=iso
locations=cdrom
