apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-components
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  path: ./deployments/homelab/cloud/undercloud/20-gitops/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches:
    - target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        name: flux-system
      patch: |-
        - op: replace
          path: /spec/path
          value: ./deployments/homelab/cloud/management
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: source-controller
      namespace: flux-system
    - apiVersion: apps/v1
      kind: Deployment
      name: kustomize-controller
      namespace: flux-system
    - apiVersion: apps/v1
      kind: Deployment
      name: helm-controller
      namespace: flux-system
    - apiVersion: apps/v1
      kind: Deployment
      name: notification-controller
      namespace: flux-system
