apiVersion: v1
kind: Secret
metadata:
    name: skyline-values
    namespace: openstack
    labels:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:+G9/UF1NfIOICfkPsaN57OKmJakQjZHbEjY7PfNTMCcxZ8r/wcrh2mTPauVMpICM2XuPWaij9WAR7xrdTF4tqPvMSTJvcAwA5/A4RbhBkTju+VBuFCthCRH5YN/DdyDjRGn9Qd/5ovNnIJuai/tU/Hkx6fxnLiodlgh/6HVZKd/ojCWBVdMdCHHkjWpf7CtHyo1RYQmZ0h9oks8K8Z82Zobxvmc5KG9dHFGesfuaFFOregPiRxnrC3TU+BFGkAhCO+BfNl2Piz3TVyfKhD54UIxRpLY4MpsAX7yTj2Ml9Ev3wmgQjygjCECyPalZmWuW1YFGsTWHOBQruR1BsC/P4vfNXraYl55x3rotdmAJf8tC6x98c40WEvWI9Dmx28aEjO2jK6NDDz5B8s8HWclTs6PCMvZoJpWBPMoUQmtaG2SKg6QdkX4GeJbrumgdyCPkFuUBWdJyBsO9wVHLgXqt5oydYtdszH4vZBJb+W5eagnhyA97QtpVpixJhXYYojHQJ8YNAKk8dHYuN7DEfsFhwTv/8fKEKF7LPhuDAJ49FpryNzBx2w1umAtCYiVtNkgIOAkeMYhskjiIY05hFuSrydEwvdC+OKn51RylVpalXAgzaVBdwMXMGegpSjYLmB++vwXW0jItb2gtJvy/YjNbadQ7SDyYoqq+IGqkAfEKXLeKsXcxAJ5SZeZBJNVVBCArtNxh5GSZBkpBJTvGJV/GB9CgZWFyF0l2hTjnexvgAphgWycf6ksNNjbsPRkXr4L7Jpg2JwCNtsMRgMZUynrDjVbHaUu/74bRym3sss6ua6BRN9uZfsCe4pFfuLcIxHc2JVn12wTf43FTfo0NsqyowmXbcHsP0eqBpCsrtqWcqBTwNVLwY1a9QtI9FT9uhcTLVc1Dm+fV3JlnogZd5OJo/v1maNjhsNgzJ+uui7OuFdCPOxyKYQ8iCSWWEQ==,iv:pOL+GcLxCQ1EnEJcTeldlmiEcTUZiBtw9ZZUavf1FTY=,tag:UR5dybuh6hzNNl/sdvR7gA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYlNRa1hBcWNXZ1lKOGhn
            STlwQnFQTWdqejE2TjBmWllIN0RKOUtiNkhBClYzaWI4cFJNRm96bWVrOWhKUzhE
            ejBKbjBPb2ZBeWpRS3o3bFVTaEdORFUKLS0tIFE1NzJiYVlNenpZZHQ4OG0vNkVo
            SERnY1BJU1c2amk1QXVTUndYbkZOLzAKG1gBi7vsFsqRiPA2sjdoS9kkR9/srhjQ
            q+QN22Q1GC2pn5s2HgbHVQGCocbcDdfdjoqdVJaOqueDF3HCAX5Bvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MHVsNEVTZG1OMkREaXly
            NzFwZE9hSk9Ic1Nic08vSFJ2ZHA3akd5eldZCkFkMjIvSlJqbWdDcVJWSzJHUEt6
            Vm0rUDZZVStNUWlsWlh3MVBnZllKTGcKLS0tIGpIdEd3dTRtUzNyaUlsSWVaUGpx
            WGhGQUhsVlNWSm9yODZxbDVkZnQ3MTAK5f9I4y37EXlVIzecrZRrs16tcnJRDaph
            eruOEbgRA9WSWu7cb54LGVuQC2+GdKnC4If3N7kJzNV72frlLAGd9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T00:01:03Z"
    mac: ENC[AES256_GCM,data:GtjgnJQE5ZtPwzyNDB4T9OtNfxHWjVKcqRc1YobruJlvDuxWET4vialhUas3YK7Y65liun0bRv48i/n7oaYE7tyaoyTlc23aZBy8DHZs/W+oAfStKwW1OruQFgKJp/KYfg7HfNGhHvyUewNjPpBy6JIugEebB0wti3H9FAh8qJU=,iv:RJAbjOkiOMa4snssd1GbdorHLZXLpPajIZnHnJHdAiE=,tag:u08W8EnWhbVLI2Eqv77SJA==,type:str]
    version: 3.13.3
