apiVersion: v1
kind: Secret
metadata:
    name: skyline-values
    namespace: openstack
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:5s0Prv4aglwxK7OHQl8/8JHGV9xbbgjugZRXK6XsVef9WhTTOcc54HeOK4jzh7NSuEiHP4r+YZVVtADf1FkngIQDTfLlnPdsyyBCV1oKE18FUZOWy4EqpbhZshqs8cICPkjShqC9BtlGYm1YsIJABrZ8wENCBc6Nd1iMYvZETSEbY+dlyae9vPbSVbaOMe3GV2wznptfVSFR5O1p3XZBLrWKPFBnLkLygZq0r9vzZ76scgRIQr5BpwwF2YcUTpB5++DxOVPsS3Xnu138EbvREFvZOC4bjmv//S+1i/tFhTAZCf3DtVnfZeIKLNbeaHrg81H2c9HJyT/R8af7kWcwo2d0GcAmiedaXuPMmxIvdg6+hgYQqSX7/sSCyuNLKmzvipuiYqq1s4abgPo0nYCg8MkglsBaSesixE4fRHoj4twBcN5owxVfDfmJ2Oot6kB5HrlJN3qyhn6o2WVIWNBOQRI722k60n5srfSlA+w/0i6sT/nOg6hJWxqaAdwCmBCrLgKqbGg+wjOP+POHUpDTsgP6TeTtqsLR0gYob1E/c1FZXB+5bbm8e0eojID8ZUMBRWy2V51sVFGCvEdAUsCr+W8qNao9aQa10rs5LqJOd0SGuSmj1o/uHLzIMYO1T8yE8heR9jyRHYmLMPtUGDg+T/Oajh5BXq44GmyeDiYdga/WfcenQXe3JpkUL93WFH3b/3vJwAJ2J1SMb6XGbNTwMqrlhwQ9pxL3UQalQSzJNDt4A+DQ7uNf1lyNGqD+TxS9o6RoUDSRbNhh0I2PqJtpz65ddkLVVGTJTLZa3nSXmhHAni1Gxcc216Y3VTBIpenZd0t9O84L4Zfr3p21ErXENkTCA8OFTysraOZuXlocYDhJwfdVOAfuLLTTlZxy7ifa/Lzb6aFzMcwZVCmWyR03GJhvOtyPU2RH/amWNaE1YyvHDCOkQZk+wwOT,iv:x+UWpjaQzT/benNRAvelXj47XvNMKj9knjcBqh5YPdE=,tag:lakJDa6YgZqrkHizopzY9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aTZudDJGY1ppZUVFRU9G
            VzdwVkJMamo3bHlaSXpYUXd1UnR4cG5OODJvClJOV1FGeUVNK3NWWGQralg4VXNz
            dFRIY2RHZGd3aXhKSXF4QThWdnFYTG8KLS0tIGRQUjlkTWJ1cTVUMmIvcHVEVVFL
            cEYxUjhtMU9QWTUrckl1M2p6WCtlcXMKBhg3i8iW+n4jIN8c8nLTdx0iuLIvmusH
            d7KeJcX211VpNe/LxGzwUqnrain2x3VNnG0m2phm0PDJPPOz28CVCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOWlFT21aMEhIU0hOWnk4
            MHArZEdVdS9rdDExUGJwQjBQN3YrdW4rRG5nCk1FWVNnTVZZcTdzMFcxM2ZOY3U3
            Vnc3eHExL3YwWlAwc2xsTTdLcGpnUzAKLS0tIElVcXhkR1lvNExQNmJ1M0NyLy9Y
            c3R2S2NTVTI1cVJhNXJET2lWUmoxWk0KUmS0NcH6gh/m4lGqkCe60UdP1GdGvQdV
            2ZfqZrzPep83Lmmt1yaUnDg+cRvuhlsm2JhDr3zoxATYrHOYJTfMrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T18:49:04Z"
    mac: ENC[AES256_GCM,data:5IXgTeLafJJxcoRFLjAoCkYVcD27cR6DKc4MgWSuKWKjPyvxOb/RFWfPPRgrAF2No2QiVShybDyR3sNdSJMb1zhyYWeVYhLSkikeB+BuIjIAsbOCpNG1vTBn1cN1jpoyrQG/hTtiK5gzyTkOeGntC/iLq6FHPeKIVlcdiiP1uto=,iv:K9Z2uEl+KvDeynMlpfCFeII0MkHy749Ijvfk0a3pSfs=,tag:devE2ZV3h+yKoNYAxxGi4w==,type:str]
    version: 3.13.1
