apiVersion: v1
kind: Secret
metadata:
    name: skyline-values
    namespace: openstack
    labels:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:wRqs5fxmf5sQRhYyFOX64y/EKiN1nnjLUN0SOk67aMuaLugXYpqJSkFaL79T7caihYzGgR2iZ4IuWrVr3N9mM1q/flFW9GakFDMR6G3lghMxeBTSjmdxT4FOAi65Eveq6KOjeiililo/MGoFntEvmm91dd9ChxbI0tJTUR10iXKSDbIVpRwBNyC0itKMGbkNyxWWZvL6qUGqZUle3wwcPMkV0BBjJn7eXfsfSJ4scYBRLPrNVVknUK/uK60on9Z0fkeflJ8j7+V1pAFe4F0mUZ/qdsx5AqTBiN4s62pfRhMXuZY8LxjtBPIpGxqS8QjH/rpWWQ6ilIp8fYZcXKjfex5GXENsrcsctZJJcyFJJHdMJapcjExht9kKFshjKpUeMl9CYAu2v8LHxVhjY371oQiyZk4/qAWhkcpw8wqovvjfGTVpDylXWkrhuxSoU4c+Zr6Fpj4kJZdfCdZPMR2fuDXh+1UOIlSSDUveuIcZqgKOguF/PlBPm4vl7mNCIqLbIyqVwJWzRqbOyuAh4+Mv1nbA7eegwDpoPPoCDl8gB5c4OhITXYZpEwh8zxV/pcytyPzD3NX3OTjnumNpo4nYkgAtSNL69zsX4dYGGl6nfXpvUQNdpCDTOOF8kGqUvPnYyILxLQO6CifCOkKDrItI772NxO74+4AS3XW+LDeBmmy/a8+cY+2frLeY4i0rgfWzVRnuzOMYfx1U5jrx3DqymQHEFa/4Crzr5ll3PkfKFFYsIzekxG7zQUztK6FZoy/l94Ji6cpGJVqC2UO4nzr7lP1S2iB7PN/qC+YTtM3Q2FCFXMQhvGFgqx9ZTWcNKFQiWYlCB5AohG6ql5dA6U5WQnkmOHzVJIAJvwXVjPW39Y0IQbGT7hOt5j2VBY9smic37hvo3JBj5xC81tNaUqRQ5nlQYs+el3Sv9NfZcVvGfNaDFgRs0wF+4Zrn1g==,iv:oUWQjud1RgGvQ/u29A5pqhvL6zZ9vRQZYjontCVQzi0=,tag:3CPc5iHHvq7PJ5Tx1hCd6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZWhPRHdQdVU0dGF6ekoy
            OGppczk4TnhYTXByREZEdUtVNTlNMUlSNDFvCmt6NVVXVmd0QllNeFdWOFpYZ2xF
            U0QyWklTRDVDZW5vVVJ5aktJRmZ5QjAKLS0tIHhDN1Q3Tjlwdk4vZkZRTEkzRVll
            dmVCUUlBdmdwbVhLQ2cxd1IxemtqdzQKf8wFBc1pvF+3Ny/AF6RlpXGvYzoocM3I
            3HwcnOGwpl/01g+TmiaWrsdxnunZIo5I4f3aNb3VFg5Z5/ZZ9TKVLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOHorT2dzaWtsL2x0ZGVQ
            UUF3bFVSbGVYL3M1WW91WmlrUy9SdjgvWXpVCndLNnd6c2xlRFF4S2xqdFA4aWxY
            S09VWE5tU2g3UDVrMWIxbU56Z0ZOMGsKLS0tIG9CUll3dmNWb0NVSWg5enlHektX
            Yko1MjRQV0YrWTNOb044eEd2U1Mrd00KysU/p1idQtrf8yDqFgpjix6JinvAuxsS
            8pFMkGWPCUhqW4ALAm0zP73NVWam9ygHaCQjl6NYWnreN3NQEYB8jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T00:16:49Z"
    mac: ENC[AES256_GCM,data:HvMyzUFoIuTh3L/hA1EL1EZt5NJ4OXwd+Ppe8+t0pH91ypAMvo3+c+xiksQEkLcAzrwpDsQLU2iH3JlaTFeGLBN9drSHrxw8RO3C3ahaWHyIVubPpC5e1nIjK8seP87IHpb3iOz1bVCM//UA3baUAnpg9n/qxn5jCcKn96fGHWA=,iv:hojWKPOLnhxAxjaHmeHseuiqj+d4gfz1h4pWYf3ZVFA=,tag:2nAW+ASFLl59ngqJMbqtDQ==,type:str]
    version: 3.13.3
