apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: private-gateway
spec:
  disabled: true
  blocks:
    - cidr: 10.21.20.130/31
  serviceSelector:
    matchLabels:
      infra.fahrican.com/vip-purpose: private-gateway
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: private-gateway
  namespace: metallb-system
spec:
  addresses:
    - 10.21.20.130-10.21.20.131
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: private-gateway-vlan20
  namespace: metallb-system
spec:
  ipAddressPools:
    - private-gateway
  interfaces:
    - bond0.20
  nodeSelectors:
    - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: private
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  gateway.envoyproxy.io/owning-gateway-name: private
                  gateway.envoyproxy.io/owning-gateway-namespace: network-services
        container:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
      envoyService:
        type: LoadBalancer
        loadBalancerClass: metallb.io/metallb
        allocateLoadBalancerNodePorts: false
        externalTrafficPolicy: Cluster
        annotations:
          metallb.io/address-pool: private-gateway
          metallb.io/loadBalancerIPs: 10.21.20.130
        labels:
          infra.fahrican.com/lb-implementation: metallb-fallback
          infra.fahrican.com/vip-purpose: private-gateway
      envoyPDB:
        minAvailable: 1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: management
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  gateway.envoyproxy.io/owning-gateway-name: management
                  gateway.envoyproxy.io/owning-gateway-namespace: network-services
        container:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
      envoyService:
        type: LoadBalancer
        loadBalancerClass: metallb.io/metallb
        allocateLoadBalancerNodePorts: false
        externalTrafficPolicy: Cluster
        annotations:
          metallb.io/address-pool: private-gateway
          metallb.io/loadBalancerIPs: 10.21.20.131
        labels:
          infra.fahrican.com/lb-implementation: metallb-fallback
          infra.fahrican.com/vip-purpose: private-gateway
      envoyPDB:
        minAvailable: 1
