apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: private-gateway
spec:
  disabled: true
  blocks:
    - cidr: 10.21.20.130/32
  serviceSelector:
    matchLabels:
      infra.fahrican.com/vip-purpose: private-gateway
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: private
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  gateway.envoyproxy.io/owning-gateway-name: private
                  gateway.envoyproxy.io/owning-gateway-namespace: network-services
        container:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
      envoyService:
        type: LoadBalancer
        loadBalancerClass: io.cilium/l2-announcer
        allocateLoadBalancerNodePorts: false
        externalTrafficPolicy: Cluster
        annotations:
          lbipam.cilium.io/ips: 10.21.20.130
        labels:
          infra.fahrican.com/l2-announcement: cilium-withdrawn
          infra.fahrican.com/vip-purpose: private-gateway
      envoyPDB:
        minAvailable: 1
