#!/usr/bin/env python3
"""Compile the NetBird egress allowlists ahead of Magnum's order-20 global Allow."""

import argparse
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[4]
DEPLOYMENT = ROOT / "deployments/homelab/cloud/services/48-netbird"


def selector(value):
    if set(value) - {"matchLabels"}:
        raise ValueError("Review new selector semantics before exporting to Calico")
    labels = value.get("matchLabels", {})
    if any("'" in item for pair in labels.items() for item in pair):
        raise ValueError("Selector literals may not contain quotes")
    return " && ".join(f"{key} == '{val}'" for key, val in sorted(labels.items())) or "all()"


def compile_policy(path, namespace, endpoint_selector="all()"):
    rules = []
    for policy in yaml.safe_load_all(path.read_text()):
        if not policy or policy["kind"] != "NetworkPolicy":
            continue
        spec = policy["spec"]
        if "Egress" not in spec["policyTypes"]:
            continue
        for egress in spec.get("egress", []):
            if set(egress) - {"to", "ports"}:
                raise ValueError("Unknown egress semantics")
            for peer in egress.get("to", [{}]):
                if set(peer) - {"namespaceSelector", "podSelector", "ipBlock"}:
                    raise ValueError("Unknown destination semantics")
                for port in egress.get("ports", [{}]):
                    if set(port) - {"protocol", "port"}:
                        raise ValueError("Unknown port semantics")
                    destination = {}
                    if "ipBlock" in peer:
                        destination["nets"] = [peer["ipBlock"]["cidr"]]
                        if peer["ipBlock"].get("except"):
                            destination["notNets"] = peer["ipBlock"]["except"]
                    if "namespaceSelector" in peer:
                        destination["namespaceSelector"] = selector(peer["namespaceSelector"])
                    elif "podSelector" in peer:
                        destination["namespaceSelector"] = f"kubernetes.io/metadata.name == '{namespace}'"
                    if "podSelector" in peer:
                        destination["selector"] = selector(peer["podSelector"])
                    rule = {"action": "Allow", "source": {"selector": selector(spec["podSelector"])}}
                    if port:
                        rule["protocol"] = port.get("protocol", "TCP")
                        if "port" in port:
                            destination["ports"] = [port["port"]]
                    if destination:
                        rule["destination"] = destination
                    rules.append(rule)
    return {
        "apiVersion": "crd.projectcalico.org/v1", "kind": "GlobalNetworkPolicy",
        "metadata": {"name": namespace + "-egress-enforcement"},
        "spec": {
            "order": 15, "namespaceSelector": f"kubernetes.io/metadata.name == '{namespace}'",
            "selector": endpoint_selector, "types": ["Egress"],
            "egress": rules + [{"action": "Deny"}],
        },
    }


def render(check=False):
    for directory, filename, namespace, selected in (
        ("server", "network-policy.yaml", "netbird", "all()"),
        ("access", "routing.yaml", "netbird-routing", "access.fahrican.com/netbird-router == 'services'"),
    ):
        source = DEPLOYMENT / directory / filename
        target = source.parent / "calico.generated.yaml"
        content = "# Generated by components/cloud/services/netbird/render_network.py\n" + yaml.safe_dump(
            compile_policy(source, namespace, selected), sort_keys=False,
        )
        if check:
            if target.read_text() != content:
                raise ValueError("Calico allowlists are stale; run render_network.py")
        else:
            target.write_text(content)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    render(parser.parse_args().check)
