#!/usr/bin/env python3
"""Derive the NetBird service routes from the existing application routes.

The dedicated ClusterIP gateway accepts traffic only from NetBird routing pods.
Its enrolled users are granted administration of these explicitly named services.
Application authentication, path denials, header sanitization and timeouts remain
identical to the LAN routes. LAN source-address checks are replaced by that
gateway's NetworkPolicy and NetBird policy, never widened on the LAN gateway.
"""

import argparse
import copy
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[4]
SERVICES = ROOT / "deployments/homelab/cloud/services"
HOSTS = frozenset(
    f"{name}.fahrican.com"
    for name in (
        "audiomuse", "cache", "git", "home", "mail-admin", "music",
        "unifi", "upload", "wallos",
    )
)
SOURCES = (
    "20-platform-gateway/mail-admin.yaml",
    "24-unifi/route.yaml",
    "25-home-automation/routes.yaml",
    "40-media/routes.yaml",
    "46-forge/routes.yaml",
    "46-forge/cache.yaml",
    "45-wallos/route.yaml",
)
TARGET = SERVICES / "48-netbird/access/routes.generated.yaml"


def transform(documents):
    routes = {}
    output = []
    for document in documents:
        if document.get("kind") != "HTTPRoute":
            continue
        spec = document["spec"]
        if not any(
            parent.get("name") == "services"
            and parent.get("sectionName") == "https"
            for parent in spec.get("parentRefs", [])
        ):
            continue
        if not set(spec["hostnames"]) <= HOSTS:
            raise ValueError("Unexpected hostname in the explicit NetBird route sources")
        route = copy.deepcopy(document)
        metadata = route["metadata"]
        original = (metadata["namespace"], metadata["name"])
        metadata["name"] = "netbird-" + metadata["name"]
        routes[original] = metadata["name"]
        route["spec"]["parentRefs"] = [{
            "name": "netbird-services", "namespace": "services-network",
            "sectionName": "https",
        }]
        output.append(route)
    for document in documents:
        if document.get("kind") != "SecurityPolicy":
            continue
        policy = copy.deepcopy(document)
        namespace = policy["metadata"]["namespace"]
        refs = []
        for ref in policy["spec"].get("targetRefs", []):
            key = (namespace, ref["name"])
            if ref["kind"] == "HTTPRoute" and key in routes:
                refs.append({**ref, "name": routes[key]})
        if not refs:
            continue
        policy["metadata"]["name"] = "netbird-" + policy["metadata"]["name"]
        policy["spec"]["targetRefs"] = refs
        authorization = policy["spec"].get("authorization")
        if authorization and authorization.get("rules"):
            # A newly added JWT/claim/path-specific condition must be reviewed;
            # silently treating it as a LAN-address check could remove security.
            if authorization.get("defaultAction") != "Deny":
                raise ValueError("Unexpected authorization default")
            for rule in authorization["rules"]:
                if (
                    rule["action"] != "Allow"
                    or set(rule) - {"name", "action", "principal"}
                    or set(rule["principal"]) != {"clientCIDRs"}
                    or "10.21.91.0/24" not in rule["principal"]["clientCIDRs"]
                ):
                    raise ValueError("Authorization requires explicit NetBird review")
            del policy["spec"]["authorization"]
        if set(policy["spec"]) != {"targetRefs"}:
            output.append(policy)
    return output


def render():
    documents = []
    for source in SOURCES:
        documents.extend(doc for doc in yaml.safe_load_all((SERVICES / source).read_text()) if doc)
    output = transform(documents)
    found = {host for doc in output if doc["kind"] == "HTTPRoute" for host in doc["spec"]["hostnames"]}
    if found != HOSTS:
        raise ValueError(f"Service route catalog mismatch: {sorted(HOSTS - found)}")
    return (
        "# Generated by components/cloud/services/netbird/render_routes.py; edit the application routes.\n"
        + yaml.safe_dump_all(output, sort_keys=False)
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != content:
            raise SystemExit("NetBird routes are stale; run render_routes.py")
    else:
        TARGET.write_text(content)
