apiVersion: v1
kind: Secret
metadata:
    name: heat-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:vVqqS4064/Wk1OCt14hr/NSxgWZPBHCBU1o2PxiX7Jebh9rarCz/J+2vejpmOq56ow6anCdbtc6I3oFpTQvtG6mNqu8HupwNNZCFSDtb1EkG+Ni5wPK8369iqpLwt4pFIOAGwZwdRGlId7ckEHnFF8DftWAqKfoyrp9BVbyx6L7FA85Pq939W803uRjPkjCiST2vr9vWXbIslR6/AKxAmSjcVe/X7jhBeUDiyZ7ZJcEr1KaJQlaYCpw8esLK3WdksGx/vE4WsosVkvrpdZ6MaabLNfqTGg36MB9Qrjpz9kBGtIHouqUOfXhkZG2p3u4vL9S0+BbzS1955H3d9t4tAX/koiNsDmUoDEsPXurkMSklDIMMhYDhyx8+QbhrBFWEoDrFBcr0a+pfeYJ1j/DCqtl6JzyDLZLbkSRhFaRdd6c64mcuz/Bimnwdr1qZeY0j50ZFjGHjyh3DYpe7jwPbJk/K/7+o5Yguj/LOpNNIau/Pk2UYJne+0OyzMqbdSmV5YLJpiP/9GYjQxZe63fnzxSqpL3DMCJE9hfXVmQF3GGY1yE7aZQQNKhRsPsVv8ukyvmUELzilXM5LJM+DfLeTLQx8M39L1yIJ/kaCcHBgwobPJ39/pjzNes2TvqVyJN16IG/AVfIZ+zzoO61q8iT7cLQW/4+XCNd5cua5QtdKOCgVwV+wSDtO9mbYsdpXGM55YnEIKwbfeQjLlB5SaWJKoNzBbwtYYtSdRXVSr07Cuk0XKlH+UtvUJ1fkXjkp3P7D2JeyAmEv4afIz6vRil7iUGbVcDI8v0Xqj1ny4OxBGQ+mV9dzZ36TqfPyTH92xE/oHyH4itUZRbIEsv4maYxDbOfFUCvAnW67Pt+PlwokeczFolQZ5S1uDle5ROoNg7J8oehkBi06cr8930pXmbtgw3A1XyHrprqWCxycLTKEZJanVKVLiB+tQO/bX/X6qKlhuFp8ZXvUCAFSeZXDRUXQ5pgSynH1xku4y3CW/I0+pO6PuLXwY/qPPhTVKmZeGxePD6g4BiVr947iguwq99UW81+DiGaDWELX5GanwUeHPS1f/zRxsUzN3rPUj2HIYAc8aF9geXi/lQ8S5/iV/mFArbYwO9nB9Ld5lHlbkGfHLjVgofemiVt8BWeuyDg/RnO0DRnSFMsFK1HTvIoT0l5mtTwvkv0w5MEwVJ3ZPdP5O4gtpJKgL5jcGHz7FLFVhovLFMKRKZxjwcCj006pYVAcLER2sGWt4iG91neqiG1ULNPnftTbx5fQ4KV3VpvuOpta0krhExQe9X5XKXu4urYA7Wo0b0m+if/NTbuqA7U7jWye/W7xGriyU4Ie/sJKEIUDSeW5oR579PY8pGujkUJwX/qZ2DVH0WjCgBmpff/uBnV5UmMSaaN7QiqzLhjbj3IL/14EqBI37d9f8eQevWKD6Qw342+xeupjam5Os0j3RJhHwZW7seWhFEamI9zzfA==,iv:HnkJIlc0EoWtnI3cMvGWIwEW2EFxFT0jpg8fJhewdpo=,tag:kqYFa9ybF/GCJLv4uHMscw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlV1N0djhhT1dKb29RQXFN
            VmozYWwzc0Z0L3dUeFVDRlRXaG4yYjJ0Tmc0Cm5iV2V5NzI4S20ra0dDaUJqL1hu
            RFRzcURiS3JlOGRQSEpvYzBXTUk1YnMKLS0tIC9sZHNtUnk2SkVWVXdNV1hVbXV2
            TTQzSi8rTGtJdXJpTXpUL1hJTjJBTDgKLtOAkpJRIcA88qsEWEcNPnv3ZLwQi6Kb
            PgOawLIv5LDYWs1UDpSQNF5mkz/24mxii5EsVpBJpI9ILyQ1dlZdcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWFZ2OGhuWFhzbVl6R3N6
            dExrbnpWRWU4bHlaQXNwNFhvYnBVekNlVUZ3CmFsRUxhQnRJWGpWS3ZhL3M0a1NH
            Z1M0TlozN0JCVDNsTWdjaXRIU3NrKzAKLS0tIHRhUWxEUTNGNWlkVGdoc3gvNHlp
            NDZWU25yTUkzOXBkY3pjY0YzMmNEVjgK01UFzPPJqI/G1UP7ML4c9c+CX7qf69w1
            qyR/tM+IPmJsXnPc6O2usn477gRK53gvtkwzvWFcjZpx675Aidlc7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T00:01:03Z"
    mac: ENC[AES256_GCM,data:aAD1ns5w6iiZR+q9qdJaGB6lJp8IvhhDppZ5/Xfg08vdL5c5kM+37+vDAE4NyHWs2dn6txW0cu8H3RRGYQgpfXL3u9axaCwLBQCJu80KvvbKC+BIQgy9QIwCLSNGFp1G0AHiZm1PP7cpTR8GMyJN97emsg2ptX1N1KvzQuNBhRM=,iv:O2wFu+VeYzfyGJGYXdsJcgyHRg1nhqmNoL8dQIEZObg=,tag:upOqyKD1bJ8GixCjgXvu7g==,type:str]
    version: 3.13.3
