apiVersion: v1
kind: Secret
metadata:
    name: heat-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:6OEglwRc3PNw1kv9aWbEG0NoDRa+alvvZSSrKjQFuTHmfbKF89jzI3lAH2QTbjRFA3YFuRw+DJmi+A9zpBDj1vKuWDKQGq337QoS3L4mfYmMcFq41Pg61IcOj5MvNhcMbaA3JYOnondyZtZ5Sgou2UjZfRZtEoWtJhR1URXBi/OWd4LEtKYlLX1TW738HaROyv2mFW57Aqu2AUgtZJOBFt+dVdJ40FdkdqNRZec9CH7RWn4iQNQ4zf5PZHdjRopEm4vLIrY03cLz9ZczaT5Nb4M+lVUVdBDNcsqXyTHvdYdapjNmnRonvNWlKi3mb/wGAG+3ELpC3Fa0NyxJFuN18zSSEn8ozls0YzXAsIa+deTyaPwqJ9er3idK8ooVj/g32PXLG3XbpLbo9rgLi12ED5u4APQKuH/F2+qhkACRizJ0IDb/04quwp5mxu0fw2GwxcZ1M68B61go6roQ10x4dhk2+fe0rv5s2AYCpsOWL8hzFc007Dnd6IXul12Jsa6T3WvffSBAK4H/NeRj+qVLnhY0gIbTYJHhtmwXArgTUcrynMpGI/rB5rdE0B1HhZP2Oh5iq9nyBzsnjeib8+5lKIIgRlgp/qSAvMC9Iw8VsU/XmOKY8maudOXyOAdYcX4UMWB27tBAZARpHPQThZSt3DbhbfggePbLwR7PAUcLFXvZ43Jt9w9SPXS5AeTdFl2mWAGV+Z/OZa/B+BGAs+FcvSuiT816lOjfgwMHrGAZ0SOKK14RGakW0Itsyf9NE/HEjtaLjoigymku5SiETpqnWQKKZiZsz74k+pZgtuI49IFbgzwkqdPNT5KGxGGK+2Z+rZHTgSLHVbijS/yxAeCeue/GLJh39Rh00dkw0YMbfk7TxODDZsVPsiCugYI7wc/1y8dsqpSurX5g1Mz0ACy06GvC/dnBbjqcL6c19NK7WJXuHactsmObaRlAMr7uCAQ9im+FvBvxzvsPtjgMWHvq1FQOaLvBiIDt4f/yAex6KTEeh0sJOwoDgSW9ObqxqMGss7lkhdr4dNYFH5WJvEi9jdzOP8V9o8nSTRbTJv65Pf8wSCkjkPxqIH6SmkCEewCCX6JrgysAck0YV2PAwHTOhblnjUhCmr3NNFJPMqw8DC5tQ5oihzEDfcAG89lgCH40yyCIuL1Oo5WY5p3uga9/r8Rhpj35iJC8L+LCFwhX96271ALTeBXM80ZW1Rds6HNTtcOqdT5w1eHnxjWajtQAv3QQnMuLMrft0IRMpCcyXOQW6+qYFE197ceX+pP75EgBO68z78NU2Uk5w09VCCM4IldSxGuPjACLedgJbiNPphguVA2SvuYCLgkuWz/Hyz7QtUsL6wEJoWeP4dEjD4L0E7KoxD2ZXxAFUUE3rWPZukVZS5fkZog64VArrv12Nn/gQqRWaP3SB5j0J0g9mZr8CGC8RBWlxDEKnFx8Qrrps3JLdByCgIvcKh+OI9KBYg==,iv:GhdQmCHaD5g58v3lfX18eIvDnWEo1SLMJlSP5K5wKVU=,tag:Ovj/KVT18hShgDJvhdkXow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudFdQMUJHM0kyMnVQOUJW
            TWhkazVGVzNSU2RxQXJuL2x1WTJZVmt3UGxZCjdvNkNPQTZlZ2x2QVFHcGRjbzkw
            ZGx1MmZ5NmllclFnQU5lUEVLSGV6Q2sKLS0tIC8xaFdjbzNldURCdlRWb3pZaUJv
            UDVSb0xmYW9MRGJzdEdDNi9PUytBcXMKvWKFuk6CvmffhzaMKJiHbltBGwGzAlFF
            SQwqnoyMhfJ4qPXzdUx4svJjmL3FSyEpnyzqF6Wy70FcBbMQpUm79A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6K282NURNRnNpcnNjSWFP
            dUUvZlJNdTVqVlE2YVVGQjQ5YkpWSWRiQWtZCmh4RFBPMklNb2J3TUtuZlBnUTN6
            MEhENWhaKys4VldBbUl0SEhRN1RNdm8KLS0tIDRwQnZ0QUszcVlFTjUzODRpV0xT
            Y1dRaEtXa3J2eHdHRFY3VngzdFJhVGMKM/PlELs964WAS6RZVOQ5a8FxqBwd3OJg
            9d807vKryvlGHLzdaSZ4y3K5loBxWpuywbZCSYRMOf2Zb6A/eus87g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T00:16:49Z"
    mac: ENC[AES256_GCM,data:RIMmit2sY/hzy8TaQgGIBUgZs4OWT+8yBH+CM7bVz4L/jSxAMsJIN9WNHlnzlmK9iJR56lgMymmt3DP+NZO3IaiK4+pdZfDks+S8rVmPKNSj2cjbQ6mxZI/1CxubB20rUDjHoONA1NPWcMXPu30npU9buohKleB8xUQ4MduhqQI=,iv:eAsCBIR9cjHDuy4nVOkLW0dVDQHY4gzZctDk5UdQhWU=,tag:vUBPi5uSVBVSO5VZcNAqaA==,type:str]
    version: 3.13.3
