apiVersion: v1
kind: Secret
metadata:
    name: heat-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:yNSWXl7qqKGSh3hmwTnLfq7xZQAhhBWD4XQO8LRgdVi+ooZ1a2smK09vU0/n1x2W8IGChOPTzSGgdlaO8clTaO22hhiKyiG+f9KokAlkmGKS5WhKnLFDU2EaqzqKYXhgMd7czUAtZfz//10P1nblthwDjRi2ko69d0hVJU7jUFCmx2jXX4ltcz6EOb95qCRclKjo7EyMYHtewzvKdkj2pdjLEPZWaWUomc23NoN5E4sywdRiT6qacXlHU4kGsPkaWSzSMJvQykfFkIme5FVqooiFcAfN9jSdn39fE3W/Hnk9rSKaMHKqj0Vjydfrr5fuLSj6g7y65RNnx5iw9xw5rfG1uJ8JqCd7TY/3iI8pakT74PAxdFNonvaD4gH7ZWgW8XfQnIAInCxc6FxtTzHTxONdlU8k4lNy7UgafqArcO3/98rn7MmwI3ZZdQuVLxqZbjJ44yYEZS84YjxpU6Bxi4nKYFUKSJ3Vy6pBCINYI337dm3R/TNI3j1BvC/VaB+98dZf7j7Z83X5OdIpizQjOd+6rVA/dEHgtTaPzTthrXkBVZX2yZP2kksqGN6P7KSOe+NlEJjwwf+qWExashDq3IRs+dvE2d+N97KOZgBvFRlqKUcn0kOBXjYXeK5sL0rl6v5vSKHKyOshm5xCd+w269beFV69M013Ihdi2KfaWbnRz5ThlrcnzymtevAuPWnjbwHB6n5CE4JrW3YNPBFWuZav4/sy2H/4w5+JyVwU7ClsJafryRyGfY6dnz7MAjBd6wbJ4mqClu6MHXC5KPhsgtcPSYYVyj9QLZ2KBa0rJJzZxV8LUrAjf1NyVzigjuiP0s4uuTFgIJ0Yr++tb3v8s4RrKGuZoUjFErkIMoUGhnzZgt56bZZmG59RJiEz1L1fnXy/s8egCVl0Yc6BbZvDV/itYKOIEhvf/vdk/HnmjXaCqe+ET6AUL5BsUqSiXEcCxCaDVNmRgHtVJtHKhzcfTirlr7YdT7NO3YbEevzS5/BqCZ5bgh/hXZRr5OOxERu6ZFgQPV+rgpnI19eSK3sXOhVVMpbQDhNy4or5Wi3CZjdPs4ETM+g0xYZ5QJEqsYtPnXoWXMFQoM14tNcK6VK6xNeT2QSFz1i/F9lfLTaohdiXxzZ73gcS8n/EfrBqCiEjgSvj5bfsiUVpMiNqYXZSQkXc9al96IzYaromlQ20ONDegGpmvZuPRlg1cMT1zhYzL3/W9KblE+0Hqnxl2ADKkUAXsFX9putMBfvsKzVcQyV87T1sw9+XYcbUBmIUII0pJcI2EU0gpSrKhDO0tXYwUmiz27SDLCKFpOAUqO/GUUkHkuctphGQODQTF6ysHqbTnxQjUFYHmGK+5iY3Y8c9keECKir9JEzv4oVQsqJbNcmuwQktkAoGzPMRnHD+tyTEwNSJB5hlXAhvffNmKAVdW3uHdwX3bS1TdhpY+ZQxCGhwnlDRKC7yCHT6NhWdgw==,iv:/09vpcTjR1yr9SpluYkAMxSJSZQG+ut2Tk0XXsHXu/E=,tag:Hx/XOmXRSmyCNDB6BTYxnw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINHkzaHE3RkUybCt2aUt2
            cUNlNEZuUGdpOURrSlVRcG9DenAxQzlvQkhVCnIyckp3WmdJaHFMMmZYK3BmTDYz
            UFdrMmpid2VZakE4Q3FGMzlZcm1qQ1UKLS0tIGFJMkg0SUcvMit3WXBEQmIyYUZj
            cmx3Q3JGVHN5RytreVRDeVJ5WjhZRTQKPQ9TVqEpwTMfQExQ4L4X98/J55Ilq7R0
            6mbZjxkhQ2+on54aP+QFNp4/+D6+fPqyqG14gj0+lxcArCYFOUI7nQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaFBabGZPUGZQZTZGSDlN
            blJSN2FWdWtxekF2TGFTVWg5VVlBaStpaVJNCjg1eEtHWk9DT2JiS3doUnhRaFhs
            TWQ3Z2JHUXJQdy91Q3RybTljd3dPRjQKLS0tIEhzeDlUaUVoeXNRbkJTSDU4Mktq
            ajBZc0FkUG1XWFJqdDBJa016cHJRY1kKLkm0XNYPTQDSYck4uRh5dOkNCjiZ2cx8
            h8GcAMicjLpATVFVCQERMnHgt8fih8gwwEyOvb2sv19kIWQ/3/Us8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T16:08:50Z"
    mac: ENC[AES256_GCM,data:pSEjREvqN8pJWT5+jp+cydu+knqlTSHZc4kqocoqTKri7rxGJbuyj7CHEET3ONrXliGtKL5xgot+CIBi4WD7RjWJGYorTAxRKU9shQI3XUbRLrltFa8uDMffmoCPwE2b99fnA5qEK4cGfcwB+CmsZ2K6Y3dshNySgBkMvuqlCYU=,iv:1rPLM+ZF8XSUnUJe4MaVH/uad+tFtglRN63kqVUxpIY=,tag:hqI8JYR+HeTTCBBsnCCM2A==,type:str]
    version: 3.13.1
