apiVersion: v1
kind: Secret
metadata:
    name: matrix-alerting
    namespace: services-observability
    labels:
        velero.io/exclude-from-backup: "true"
type: Opaque
stringData:
    smtp-password: ENC[AES256_GCM,data:sdmYGXIqF5guvUnr5mBM5U2nj+U85JoqY9ZqRTCI/LmU/v5K,iv:X/Od7dQqseR/KZC7n8TehDbGqOOPhNHNtDUGT/4sgxA=,tag:1H+KEbTrSh3hAetIz7wYiQ==,type:str]
    alertmanager-token: ENC[AES256_GCM,data:Q4U+lEQ+9YQPoc0VDZ7e1giBmgGiLrQMzH+gUMN4jiRLewb3FgcvVSUHqQ==,iv:agUSTxV45uarh8+eIa7FbK00loNaPCzpDF/vL0HdGyA=,tag:uGpKpubzCFUW+uH0jZj+DQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ODNkQ0xhRFFBQWNNbjRy
            VS84ejZpRFZUenpFOU4xNzVRWnFHY1pqVVdzCjZRRk5oVHpqNko3VERLenRLeHdI
            SlRIYmFrTmg3OVFUdnltSkZiNXl4T3MKLS0tIFZwVVVOdXV0RTBqV0RodmxBRS9V
            K3p1dDdicXppR2lFbW5KRVNCMzd5c00K53S+q4H3li/oKoNI0M199P4fAlZ211xo
            E4N6GWd9GvCuOrZ2kZMv6uCEjIfcU5PhgWprkQeZyIH0wS2Ku1Sykw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1clBuamVmZjl0dzhJRi9R
            NTBXRUpaVkswODVIUWliemJWbTdvZ3BPVUhJCno4Lyt6YzNPalVzQVYzUHAySHZ5
            bk04QjczdjFOUXNsTy80UkEyNUh4Wk0KLS0tIFowWXVCeXJud3N1SWozRS94Q21Y
            VFhTcHRjZkhob3BIc0pubzdRdXh5RjAKlF+25egckIzTH0haL38xxHF4UyZsHRV4
            wPA7t9KAmbNus/gH/6sEtrI4jA/t6drLcTl53iHt5pn+eidvVrBsag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vfxeaxdj7jze5p5ytff0peyjm3rusn8naacfudklvzwknv4yk5wq3qqg3v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T19:49:43Z"
    mac: ENC[AES256_GCM,data:uZzhTYsBGGgJTfZkiUYFEVlOA0nlu3KEmRV3eScXAOTsq+PzWV1FAOHKLgto0/Oh/AzG1ELmpC5/eJ/6kb8NGAiLBqJsleu/MLD5/RhqjMu5fm6Xnl89P7QoYFqmcdGquS0QSC3vo9c486awpnhf4F3PJjWQcHDDj0IZSfYPT58=,iv:hMBM+kbuu8jynJ6jUQmSQSEBgQpsO4278op0JOHdQ+M=,tag:lGzFaCH7jQR7FWHS+NZ9GQ==,type:str]
    version: 3.13.3
