apiVersion: v1
kind: Secret
metadata:
    name: matrix-alertmanager-values
    namespace: services-observability
    labels:
        velero.io/exclude-from-backup: "true"
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:u4NtYvjI1j7b5tmqM9gxI2io9w9CeWOyJPVC0tIa5CVY78sScaANW4T51Q6marwLZNKPyxIikHg6P+IzqwLcs1dyX/QRtDjKuwZvl0Bg7hjXhxD3wvpPmjMRag61ooibxKYqffROU/PT2jbenPqZPcBKXCvsNlS+WJsjkKEOQJ86+ul5z5d/i/KNzpfFUsOiW3IzAttXxlbS01LogjtMUO2BPWRjfg/QpjJQmI/ZlyYhXojaCNU2rI/A5HG+TKEzqXP3+PDd/c0PeVyYg8ZJs46P9Cw9z9+b9gKyTiLWmBt04iX/YleOqIQecLdk48ndL4vrGkhHvmSUKN22WoVNEB6k4Eod2hIVG0AD44meG93FhzHPdOvjDNnIwMHgQQFahSkdWTq5QI5aQI91VoV5FsjxbnTajypvsy+pPrMQk4N0atGx31L63YSOBUDL8f3qg6TGasU6BI49wmALiCk1c8UHUqcQJcQdXBSONR+Rc8Nsqca+5kI8op7ZUFmVW6IXQKjttfFBK8fAcCZ0seQx+EcsWnzjoj8i639IzNEWUps73WYPXvCaRj1xgoyd1scnEYIbAnLYdtcTas2QRHvK8NdDLCuXhfwdqoytykPKWP8teUF6DkxrFwGfsiEWTUsOKQACunFhFz7DRYb4s30oAT9bjiBV1baWdOrAhfJVRHrvYJQb9oWdvnoW8crd4TilwypbzyRdHCI0VoHfjW7TsoR11PjyAjtgUvvykI6/FkQP4ica3N1AJZQiuJ2BinIKodISaw/3pDuqbIrqADh+BW+f/Cy1gadCfCU62bXS+L4TTkGaIeMR6zVMrWHqK/2EdzezaDOu6f0ygif1E+W4OPSqlXpw9hHj77RQP7LGHpNdcSDHsU7X6fulVIysqp0PrFwBtzZ8gIwkyQTn2VuJggMXc2OLFW1UdGEkGeybR90FH88NFq0khqjY7qVaoxQAYkiokmSy6iR7r8evIQSvUyweQnGArM6Aq9lHSyKOaxgePl0erFt+i2WKAjbujFcTQFal40BTbIB5GT2FsKVhWpZ0QatsvGK8ui77lM9PA2iocw52Pt+XVR8DAOxN0CEd9aTiHcXC/CXMv7/zJqmJyvZWf8nn5ft+87UwYAewodJNf92qOVyGC5LKW6JfeAmrmTbG+Z2ZekfBLehoFB0NvV6jiFceQecNPAWqPMykj0C/JRRxUzpi1mRi46s1qVmIM00fmXWpWN3bpsR2j9JYbeMRygmLARloKGds/kr5SvPVidhfKCrUEQjjDOCIRx5qeqeoouy9FTHybYwMlTS+S24c6uJonrZ3hgePBMrSNMrdnUNZ8Xfo7fs45d7sBPTJySCEvgXmpRzteM5LlCH26YYJh9eVvj9Gn6FujpH396U6hwesYofb5piRmspZ8fu+bWqEPh8gOTqPei4iFhjTcLRm1Td9NGQEh8LGyMRGzeANko+MQ77qMJPmnI5nynwE9w9jwvINf9ia/yxwXT+NcQTI/+9IR2pi2L1Zrk16nfe2cAhCu5VdL6K26ZmtLvL+HzP37owNc6bF1KnOgLLf/ebRWT1WuyyATmlkqbEwDbzeTPDjVX8yQXcP+rLD8sGZ5XoU5P2HJYtKar1i1yEn8S3ZKgadX140HDiLvxCW2XYEwLg7TnhVlX/coIqLn965BB5D6y16RFXjbET3UIpuNeHZl3ctjFe+o6cv7ttFN2k+m6fQPwuKy+Miavz+DEpi2CAYKukLSTqIjwmSS3J5C3TlY9/MYA5c273WGpPXi7g6cvQfCdlwGiKdmhW+413hIIaDqb+vEnrWf9KxXjFTNcElhw64yy7SWUorgwjqbtTbvJkLnQMpuMXcXpM6rdHIa73+CjzW/nHpydo4dLSdsTzN43n1lcbJ+t+0Q07vodfbNEvLLaQZzy5g+01ZoqAb8z1GIvSarRUmIKTTC3683FBED2NZCxBr6k+q6T9XWI/uCc3oOOzrmbK+wj49T3RQNmj1Bk1z3OdJaJli78K0630LBd/uCalbZTn5kf14lInr/yQvThbFWK9q7P6kP/cBSiieVZ6SB3jDeQkwCSjEbROUoIA5z0qnzQsceMXyfWUfPtjTaFJYovf9fwW42AtDtqeNGwNuINUPPBSsNngW+d2S86fWO934ABS7IlRYLgqTxNdvLylvrDcsKJBDLcaAVrP5vS3LT3g1prdpRQ==,iv:5oL85xHbjEtBxq9jOpWv+Nyp+rn5XN1/5X+w+bd389o=,tag:lT/n1I6G9a+NBBvGN98vqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbnBtWVZVU1AzS2FmU3pZ
            RU5VKzljdEVxcGEyN1RtWmVReGpWbjdSTTFzCktDUnhEL3ovcFlwL29rV2RaTUNq
            T0puQmx3VkxPanRIU212ajZNaUJMWmsKLS0tIEIrQlhpditybENJbEZFN0N1RTJ6
            eVV6dUl4eVNoa1RBNXNraDF5SzlzTmcK4k9x2jAFE3y0YHqgL5rz5MAvBh9O0fOU
            wtoz4mf39VTbALH3KTkXJcyYqGW88UF2hHow84S0ENglfQcPW+ivYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWkhPSVZ3ME84Q0xkcnE1
            R3N1ZmtvWVR0a3RZRE1lOGNTdi9IbjArUTJBCkpqT2xhcS9JSUJya3R4U3dRMkYr
            RkczbUgyNi8vV1ZIclR0Ky9CZFNZblUKLS0tIEpnUW9oK2xyRHlhRTl2elB3OGZy
            M01pcVdrQ3ZJL0Z4MitWcGRPMXQ1M1EKe5GCrPIIHDrH7NR+SXPecTtEZxbKFxL7
            n1iVM5KuZrdfMUTBEGk+nPgJYUECENwQNibGzJYxAkyFPqKXmx3xRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vfxeaxdj7jze5p5ytff0peyjm3rusn8naacfudklvzwknv4yk5wq3qqg3v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T20:15:19Z"
    mac: ENC[AES256_GCM,data:J3pfo4U4yk8FOpWkebauoLRKuMuQkssxfViG1vD3813B9kwRL0UmaWYez4OVpcVqPFM/VLiXVHebf/PkWNw7IR0X1P4RvP3XFyZsHB/3C4ZNJ6bsd4JN8/0fB1rBpMbtZ3nff4ZUvxPTjzaN1T7r3aq9dufelfq3RjA1YvEdYBY=,iv:KbniP7WI+vIkcWO9IxPi2bFLe4LWK08Sy2pPU3B6Xts=,tag:IYTFZYlKTgu9PFvuxg1kBA==,type:str]
    version: 3.13.3
