apiVersion: v1
kind: Secret
metadata:
    name: matrix-email
    namespace: matrix
    labels:
        velero.io/exclude-from-backup: "true"
type: Opaque
data:
    MATRIX_RESEND_API_KEY: ENC[AES256_GCM,data:eAHhGH77lebsyH2gglje2LvBjFN6ZW19JFzBf4A3QHjHEbMmpEKmLMNA8gYMmAWG,iv:2zPOuwgQ1ms+ksuQbnZEGjLY6Kn8SVhYE6jDPFHJVxw=,tag:dgIfajg61MlSjzI/E7q7zA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTEI2ZmVNeEppMEFBQzNu
            RGxNVThDTjM4OFdlN2lLSnpGT3d3clgxbFE4Cm9QRlZ6V2pacTQ4cUVHb3hBR0Zo
            UUl1VmwzNXQ5TVJSRWZVWU9nSU8zL00KLS0tIFYydG5BWGpmbVJTMlBTeERoM1FG
            cGFqQkt6VDI4VWdlVStncmJnVjdJUzQKURN0Waf6zLcifJ0wtoAeSScpDt6XkVYn
            oq+31Zn4a0ux0zwH3g7PY06ersEa+3VaMX7JlmKeN/bpgW34a3Ia0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWm1tWVgwR3ZsT2crbGxB
            TGJyWTVCSldZWDMxSDNMSEhLNVhkKzNLWkVrCkd4QVpnajRsZ2ZkRWtuYmZiOWs5
            bk1HeGtxeW1HemNUNEM0eWhaOXU5d2MKLS0tIEIrV3RLR0h0a2Fyc2c4WStBMUJj
            U2xZZE90Q096NTdnbzd1S0JjbW9pd1UKehTZek8/JK3tOQ/O1AFuDy4Cf4fokloi
            JBoPCjvbph4QdeNR0QIB3UthCvzW4HTgf7IgHen6x/u/tMJiuetQfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vfxeaxdj7jze5p5ytff0peyjm3rusn8naacfudklvzwknv4yk5wq3qqg3v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T16:48:11Z"
    mac: ENC[AES256_GCM,data:pJcjaaMqzOh2TXoCyQ4J71VoF4bcOXM6uJgrR8j7q55QX2a/3QfU2GnQqi/ItxE2rOwiuOvO41MCyZonRI/o4mE95mtGRSuT/rka2hse9OdZIm/MnEnPjCHHDDWkLc5nTIua2g7Bq0yqHGLTCW8JRuDiRbO+3YcVCNSitfYjilQ=,iv:FO+AyEvxDXjw4kYtyss1GDSOq1/VquYCJg40GOLITCg=,tag:cmPjBrdqQ/8cg7nwcF6JZQ==,type:str]
    version: 3.13.3
