apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../components/cloud/services/matrix
- storage.yaml
- config.yaml
- workloads.yaml
- gateway.yaml
- routes.yaml
- network-policy.yaml
- monitoring.yaml
- runtime.sops.yaml
- email.sops.yaml
- restore.yaml
- registry.sops.yaml
- registry-restore.sops.yaml
images:
- name: git.fahrican.com/forge-runner/matrix-runtime
  newName: git.fahrican.com/forge-runner/matrix-runtime
  digest: sha256:e2ffcf80e22d306b0fa2868fa40d661e6f7409a9eb8915d355c41a1f612085bd
