apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../components/cloud/services/matrix
- storage.yaml
- config.yaml
- workloads.yaml
- routes.yaml
- network-policy.yaml
- monitoring.yaml
- runtime.sops.yaml
- email.sops.yaml
- restore.yaml
- registry.sops.yaml
- registry-restore.sops.yaml
images:
- name: git.fahrican.com/forge-runner/matrix-runtime
  newName: git.fahrican.com/forge-runner/matrix-runtime
  digest: sha256:cf468a71ab0584f1c1b67fdb1511bfa24be365fdc3d76bee87efb11893827f6b
