apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../components/cloud/services/matrix
- storage.yaml
- config.yaml
- workloads.yaml
- routes.yaml
- network-policy.yaml
- calico-policy.yaml
- monitoring.yaml
- runtime.sops.yaml
- email.sops.yaml
- restore.yaml
- registry.sops.yaml
- registry-restore.sops.yaml
patches:
- path: runtime-rollouts.yaml
images:
- name: git.fahrican.com/forge-runner/matrix-runtime
  newName: git.fahrican.com/forge-runner/matrix-runtime
  digest: sha256:9a2085fccc6c24252b545f0a1899542cf315d02c91d78171d389594753e8ddcc
