apiVersion: v1
kind: Secret
metadata:
    name: matrix-registry
    namespace: matrix
    labels:
        velero.io/exclude-from-backup: "true"
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:qxuhB0aGsZEEylpxSTxSf95uzq0jIXUuvRvHuYct+Lfoq7vevXAkHIAHBm0pKcSQRHyteLrFDkEI6Ab+nAgLpKvlpfveASPE6s7f/pAu5YIpBDAPFxTrYJX30UhIL6eoVtk3w1ua7mHkDZB86eLMsdSK2s+/JTJT3OivVU7IFPT1rjh+7lrX0zRAE0xnox0noUjciJo=,iv:s6MgprihuonxVgF9sMJxebYOWoq+hEBMLXogtKeYQCg=,tag:QSl8VGqvYoDdW/touDUIzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtS1dSTEJ4OGF6Sk5EY2dB
            cEZxRUdqRlhBdHBLYlgvdmx4Q1BnVURsVEc0ClJMNE5KS21Sa3RpMUFCcGJmcFNH
            VU03MEh5SEZXUVg5bjllRDh1TFAyRWsKLS0tIGRRclVsWlYzUEh1Rjd4aS9oRkE2
            RVBNckt3WkhSeEhSZ0creE9VOHVIWUEKh841We9pzjt+lGP9pte/RoKYUXoL2JYh
            n3gIWEZd7tt8heFhCO6BhfdktSrArO4JceOYCc4oYAqwP7wybxTTIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMFE1WVduSVpIMTZyT2FT
            dEg1QU9NeUltTmQzMEZyTGpXL3FyQ1NsQ1hRCmsyZWFkQTBxcmNYa3o3T3JKUExo
            Q2pqT2d4ZVpMaHZMN1E4Q09vZnk1blEKLS0tIGlQd1pCRndkaXVKa3RwUGNzZEdR
            YzdXWUxjQXJxQmI1dGtRbjRuaXhuQmMKZunisz3UrHJoJ95/B0ghXiIJG+/etjhI
            klK/ReFIQ2pB1dSigcmAdfHtZ/LKANGSRO5fR2HjyeLPkG3Lp0HgeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vfxeaxdj7jze5p5ytff0peyjm3rusn8naacfudklvzwknv4yk5wq3qqg3v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T18:18:41Z"
    mac: ENC[AES256_GCM,data:3TU5xAoDpnPTEGXDcNGX7Hn1nL8HE4uTd46qq6/kUZWZhMmJCvniy0HX8absJz0vfmzKqiY4y63Lq940v8kQ+HpObzn7mruk6bDj0G0bxCL8kM+nM9CiSE2nAe+Wayj/WSkj2cUtVff/gOYCcoQVxZ7odKRSDwfZUL/MKqOrmDE=,iv:OqVjuSJY2kLVqM6NvTt60T3xlpYWfAOlAV4DQ0v9rEM=,tag:A4MikmmDBBC9d+kHB+J+vw==,type:str]
    version: 3.13.3
