apiVersion: v1
kind: Secret
metadata:
    name: matrix-registry
    namespace: backup-qualification
    labels:
        velero.io/exclude-from-backup: "true"
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:vFEfuMrEgZxRHFJFxDZWjSvcdCWCuO10UMuHX1SiEXZcRkCkfuQusPDq0a/IoxMyEmZ75R+XMXU9MG6TmIJOBJMBO7ZG10DizBibcbBE5YcDnn681YqqFVk+D6GPXS/+wHAyhCminSE44XWNBSSBXxzgLHQTf2vJlwufThyedO8SSv7GYLS60MAVNk9h7/1V4EGp63I=,iv:MrgTJ/Nb7f4V4jMcMpNUmKKaKlE6lvJyL6FkrNszisc=,tag:RCR8BpyKkj0Mlgg5B88tIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteW10dk5WV2FsS2JXeUlF
            Z20yMmxmcklwZ2cwT0VTcDQwN2NHYUZOUlhVCmptN1NpcmdPc0VWZUJhWm16T2ZJ
            UWZhbllyWFNlNkkyeEo5TWRZUjJQN1UKLS0tIGo3aVJ2UmhmWTl6ZGpqMTV1UEkx
            bjhhRTMwZ2prQkNJQnFzR25DbjBoLzAKjb0V2+KaPfPBWCLzU+2k1IIPu1xofHdM
            Qr5k/y4Y278JPZJfgPbt+r1HvMmpLyiZkCLB3YUULXDjL4udLUOzdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeVpMeWdlRmlRYi9MMkRS
            aVlpNncvTkVISy8wRUxkc3dJWUt5NjRjSHlBClZPdW5DV25McTYyNDNLczROeGZQ
            bm9UQzJyYnNSeThZK2ZNSjVsZExyZDQKLS0tIG1JZTZHdTFqb3BFRXlaTXZKZnhS
            U1d4S21JWmhmSkJwYkZqY2EzZmVPOVEKM0cXWp22H8K0JPT3BFF3pUJhJ9s7W85O
            AsLy+VApoqxbxPVbILMUa6meM+0DiPwRP1NCU2U37idwCeTkUnbj9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vfxeaxdj7jze5p5ytff0peyjm3rusn8naacfudklvzwknv4yk5wq3qqg3v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T18:18:41Z"
    mac: ENC[AES256_GCM,data:sfEpkf+RlPbpxvCP871Z839J0FSwIxWEAKhiHPdQbtHI64jP3c802jguntuBT+Ufjd/0sRMZnI9AE9ZgXmqcssFtN0jJn0f3+0natt6FC61tuw5/aGGHod8UBqo+bdrgbPgWnG7xSLU8/XtBFnXCJOpMQKIjR0hKd2NQihH8ooE=,iv:N6uHAQ5k4xOfUZWYx5N0cRwd+qyaFjTKDIGdF0xwt4Y=,tag:t4ZVPmwZCVBsELGA5JwmXw==,type:str]
    version: 3.13.3
