apiVersion: v1
kind: Secret
metadata:
    name: matrix-registry
    namespace: matrix
    labels:
        velero.io/exclude-from-backup: "true"
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:B4w+7svO49/jUwca9O01hEZ6I5i8tBZQLW4EQToDUdLfnAAZveL62j92jA8qM0Hjy9PFqpswBTJB5awbPQvj5fITYDKCisyvSxDeyzWscy9DaDBeLCjPzbZPg9lTuiKqR3XPhykWvP+IcSEWWcF9+1H+WKfSCWBii7ULh9IoGS/yPYZ5cB0WoTN1Uz1Ajj5Fh5G/SaI=,iv:PJx/kFjLUgnvYK1JRPRs4g6+vV8+96Gfjldlf+AdKXs=,tag:bzhjURJ8iWWMA4zEy21LzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VnZEUFdZMzdGeFBGNmwv
            UGtEaEpPMDNZYUdrY2gwVjRMUkN0SUlWZlQ0CjVnNmNYQzZFY3hENWkxV053MWlN
            TlVqdmFFUHRDOVpkY1NpOVVXQVZhNjQKLS0tIG8zVVhKMDlnQUJISmhKTlhCMFZn
            ci9GRjh2R2VhN2VrWjBKb21yTHhzakkKOgv2PLUAHuvHCDkmm5SgvcE2Ux1JtxvS
            v1Q3MrLnj3fBxhz+JWvAPCVcI0eP7Yc97i+5BT0bLWfZS39+M7Qcaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMTBiWXNhU2NhSndjQ0hx
            OXFDSENqUHYwelpiNzZ0UXJuak42Qk93L2tzCjZLSFpOZk43bXlRRDRySU53Tmpt
            VGJKRVVuSzdYa2xnL0grYVV4Y2NGSTgKLS0tIFFzOEVZVjFlVDZHVVg0V3lhUUU3
            N1RSaS82U2xwU0tQcGxac1R5QjY3U2sKWaEHU5EOEq4csuNCrxDqZJVCDjrygMP+
            IjJW3hmr7lwL6oOhqClMf00e/WdgsD3qbjgiZKcWDq820BFOIC5n6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vfxeaxdj7jze5p5ytff0peyjm3rusn8naacfudklvzwknv4yk5wq3qqg3v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T17:38:23Z"
    mac: ENC[AES256_GCM,data:d4Dy3IZABD2Q53XoYYoxg0t17H9nmwHoTUNXCpZDuKTx8V5WD6BKp6RuN/S0OlspsfiEbfMggJDb7wMuSatEDQYuSAfL0OZE4Y+/8GWBQMheETQemVRigqe9FEo4/olqGP/10J2UjrcdlheoUwifT8cflxL1HwcB103PRyRhZto=,iv:7gfJmuNDq6xK3PjkwHPVe9/m8xkK3q22qKAWfG2CiUc=,tag:M5ncIO4q39apJEgkxWCLYg==,type:str]
    version: 3.13.3
