apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-relay
  namespace: matrix
spec:
  template:
    metadata:
      annotations:
        matrix.fahrican.com/runtime-config: e73edb02b73e69c3b0889207192952af674bf5e3d020acaaaad041223f0cc49c
