apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-relay
  namespace: matrix
spec:
  template:
    metadata:
      annotations:
        matrix.fahrican.com/runtime-config: d1965efa83ea5b061efa626b45c00f30463b790bb8893c1e63aec69e662e2d1e
