apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-relay
  namespace: matrix
spec:
  template:
    metadata:
      annotations:
        matrix.fahrican.com/runtime-config: 3c08792b5ee8da2f0092c5efd75a5bbbe2ac6bb6b860b6a5a3dd8a24a87410c0
