apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-restore-modifiers
  namespace: velero
data:
  resource-modifiers.yaml: |
    version: v1
    resourceModifierRules:
      - conditions:
          groupResource: persistentvolumeclaims
          namespaces:
            - finance
        patches:
          - operation: remove
            path: /spec/volumeName
