apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - finance-restore-modifiers.yaml
  - media-restore-modifiers.yaml
  - restore-qualification.yaml
  - schedules.yaml
  - home-automation-restore.yaml
configMapGenerator:
  - name: automation-restore-controller
    namespace: backup-qualification
    files:
      - qualify-home-automation.py
