apiVersion: v1
kind: Service
metadata:
  name: services-host-node-exporters
  namespace: services-observability
  labels:
    app.kubernetes.io/name: services-host-node-exporters
    monitoring-target: services-hosts
spec:
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: services-host-node-exporters
  namespace: services-observability
  labels:
    kubernetes.io/service-name: services-host-node-exporters
addressType: IPv4
ports:
  - name: metrics
    protocol: TCP
    port: 9100
endpoints:
  - addresses:
      - 192.168.80.10
    conditions:
      ready: true
    hostname: home-assistant
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: services-host-node-exporters
  namespace: services-observability
spec:
  jobLabel: monitoring-target
  selector:
    matchLabels:
      app.kubernetes.io/name: services-host-node-exporters
  namespaceSelector:
    matchNames:
      - services-observability
  endpoints:
    - port: metrics
      interval: 60s
      scrapeTimeout: 15s
