apiVersion: v1
kind: Secret
metadata:
    name: barbican-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:bz9vqgoNpeWWAcDT7F3MK89Nj2ePUAqHO339yC6ZgRykOq1Fq09hSP5pQNjdKAST9/IZ8HpqlGbOSPZDxhVYQXy/2BuqHhvnao7AaUzJi3ncNvibr1FcMj1wqqInd54ibjSyZQs2fXMgLOSVrTeMfHjckN5LDd38wQ9QGWbsOcjtrYy4N1zTW1ZvNeh9oFLL9efJks1RdUQ1YNVgJEP2LFwBTFQZTU1VliqfqrDqLWnsHP+d9WGBpUfDkOZU3Q6Qkrm3Pv7nAftOTAM65McvwtI0XNlGUpMTcSOJSxMUlIlNUlNXwRa5opIfSKM6TlLgSF6UMhxCEwtcHW8a5BKiFdYh8+rllDefaEsOQWt+SENr9z8mTsUWEcbx0CDF57eY8o57gnQ8r2HsIPRl+ZY9x5hOnjA+nBd39DlQZy9m1CmBlNtG5OUBmoVB0gYzQar/YRxpVFTRwEr90hJPU4dSWTpTMhB/USro/rBBrUhtwXWhhSdlq6ySpz1uDgyOJ8gPlBnY+K951Sj/WDBNQDVENPD1Gf8R9GAKUU45MigBdp9mK2TEp8TSLsWS0+HnrIOnJHaQ3/rRYGfCYrVl7lvmEVcgREHBv4S9CYnH9vi/TePHOjGrIs49yBpBKzoA8xUP4ujl6G4PtIL9Nfl/kIv6JuX1iwouxo4tFJxs5igFcL/MCLCaZf/22RMe3tzdvwiPM5v6Ssp4w+00ZdyLE/uR6+jbLo0nOKPljHH3hp4KFEQPsMm9SWRLg7zy8aLIC7D350Vzh//Y3AHrLzZorQD9GrGxsXwkjzgeT07r4KFPoDeGu3yFD5nYWvguIRUOxIKIFIFC8D9zmmVN/2jV3sVyLPve+KoFBRcuxH3WFlJDDueRkGrZpexuIPuIZZJddGdLKu5ZN8l4zd+jHwTsvvhOiIhv+gvfdzi9ssBAm70QMz52i9xde6K9cdA5gT7c5xV5YfYiYJPJ1huxP5uasHJq193HKoNGETk6ei9uCbTMh/tJfC0qKMXzfrf+Ibi3Se7RxaST/3bAv+43jfPZ2ZP48YbusxcYzhHiNxSSIhacPpBqmU07tahyWMoKiNSmCyJ4PLKKl8s3fkw+ncTVEIC2+Xzw5vB7IYpvBiZ2VyI7VAxCNyIB+6sDPUOlfzXkvH35pk2tzsaYcyNz+jIUcCel3myzOCm9/lUXAbn8ARFGKXOlHit1SKPIxqLC3x7TQnLQsZgbAWcOpq46/NJPMUn+vk+8BVZE1O1HzDu/4qsN0S+JVdXNC11qWD2AaoBhWw7ZjwgtsDaF9FwlD7CyyAatK3NJAU7WEe9e7BT0ZR18JGN6+1kLnEOy,iv:IfPl5OFzuU81oMUtKOWk6dayjsCD+YvCR1wWylW+hkE=,tag:UjJZvzKsjUs6Ov6/+vO8qg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdW4xaDNXNlFLK0tUcHZ2
            RlNrME85TnhjaUJhZ3BXZmlTNWVWS2JZL1JnClN1djFnOGZCa0xRMm4waVc1K25w
            RmlKRnJZN0J3WSszaDBIY0wzS1ZQQXMKLS0tIEc0N0hBUkVoMGZXYS9FL2FXcEZH
            QUM1ZDhwMTJjOUtKczRhNWgrYk1icG8KmaxnPPogz3CU5YJF4fyrOuBQFtaroKfA
            wX505eQDvKpDzViU2PcUP2irEXLg9c05Hw9Lf/0pBdUyLqhQUFj84g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MHdPSll3dVVSMzBzSmlw
            VFZJbjhBZjNMOWFHMGNsaGw4eStia3VvVFRZCjJoUVpPNStDQklmbGVxdFNybkln
            TDFBL0ZOWmxEbXRVVzZWck9YYmFKYVkKLS0tIFlFUXJwOEhKQkpNc0xIT0xuZm1z
            T05zbFJEZjNEWTlpQ1VIdGM5ckhndVUKdmHGg/0z17GvchlwFjD0lmO2u+fOQJ3R
            zS9BZmMvbuc6nvf+B3c2YaPav/8hcb6nGVobYDtQhyM5ts0dBjsjdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T00:01:03Z"
    mac: ENC[AES256_GCM,data:PY5pW9LwFAxYHhzq1CmaqwUyRcMSUoYgbnWuhpEqAZMVhle1aXkpRA4fR97rY03/ezXCEZE0X0NkcwhVCAWaTORJb7CU4nkridPqm4M6+VRDCajCLChZA/tLcB4kl5V57CO3h5O6CCNT7u9XvHRMXxnO4gEmvRFLW9GEyfEiDk8=,iv:BvSaGt7BMkP7yNbvslfT6z9MM6xAs0CsxYduiEhBoOo=,tag:d7n8dnuprUFQVvGCs5UBwg==,type:str]
    version: 3.13.3
