apiVersion: v1
kind: Secret
metadata:
    name: barbican-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:SGut642Z65qK6ONUpTbEDKPbvEA+cqYkpSBAlfNydfisjIJosNOz9v/Gdl6nn0YtfeAG2MP4BeW1tuPkbW9El2rjg2gFwEEn0yDe10mO/sEQ0nxFbgtE43TQxj2loPckRY++CxGEERH/a0F1HWaALfizBaxtUst8+ILYFVwHvXPFuMwLjKqdYNiE/8hNHdEWSoEZYcLMtMWRDWqxIK55hmV7EDYkL1Kw6KaimNN8q4rDTq83dgXaizE2IvjV9Xqyrg4eeqx3TvdWb0GeJNfU6GG0sL9Wk+ComNwTbIAe4NhnIpbc7wj9dceyiD18mDqMTBYym0wyc7WJ8Yml6knoLqhvvBNvmuOnsdYqqv0aGaK2RtMojzeegP356fUuOA8ZgB7IECjgHKNaZ9gMl+32Sj83nnqQvlQF+Tx17AjAr1sz1LdqZn6CtVpXcNtfbtxh6xzsLn2EZzn+Kf5nv7HsPNOPGQ6/ZwD7m3FqUuQ2Jy9dyj1aJctZM6YEbiCVfEt6dQKbgwldr7C4jWaGCzX2SsBr2I2usS1ZLutfe/A7My8K4SkoFDZYFcn1UeGRKIA5+f+yIX1pPgRidZc1N6ciS4VwdALEQPHygm8h3KgI6mGZaDUdaL5CPva7vCfmW05/AnfMdFsaYW2Bmh0TxKwECXJehEqC5++gSnwW/5fDM8CDrK5pUFwaYlr4ieaCQ392qLmu8I41gLbY5o4b+LsG+dTATikFLVXOIQ80PD1lOU1NPsU/3LPJdPHAuVXmYy4idI9YwE+JdMeJibwcVeHn302DJ49MTB9VkTZLfoGyb/Qm3dW1l9gdc1C4L3mAMDEQzb6fwDPOU7KOABqol3DIiYcEpnlfh5A/4tZKNqVgPcUYWC/anj4NPTzxVY2YVq2G6evOWVKfcs85Mpr/Ynf5Hu/ZMANb8BUDaGT3lAiyJWT9qrnT4Aoe53EAC/xAUUXYc9/2o+XHcnkAnJSh0dUDG12mk5ISLMz11dK33yvWNDjMF6fqw+ND2Zgkpg1TEWw+PswBA+siUt9UUfhgEnkaTzliPKLh7zmc9l4DoH7smZrHwQ2ChCxNRLNVHcbN54AwWxLk0nvfVD4/Hv3pOoP3D25pJldBzBAcT+yWMg5eTb74iz/GIW7yp50tdpQsg/nxKJHyO0vb2NMZeHEtCB824cTW5Bj3+r6ttZd6x8hr6JEylV0ixZyuLSbb8MaONuZm/8tKptFKrz6v3EbJ8g11JTbX35BjQMeXF3K9ASXQwNO0DLD6QQMIRsXjxImjo5/I6ivQatYXFZQpIMgP2UXmTBcfD6PxDGhQNeJzsGmvwgEtowV3QwZs,iv:Y42n5g2AqVIJtXP0EblhzqgVVTdgEZfVC29UTx/bzTo=,tag:+52OJJPt/JzpmqZzD59m+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbnFpYTVIcVIxbVN5N25I
            bjRVNnVNcHFxQkxvOGlucnNqcTJoVlI1eUdnClVFbk5NNHNjWURjNG5BOXNtNDNL
            TDY4WWxLTXdBd0FvOHI5ejRwV25lRlkKLS0tIDU5Z1NNTGNncWFVSGl0SExxM3lQ
            dGQ2UVR2a0FMUXJ2NklkTi9CWDRvWWcKzlj2xqdLbmpFtQamTOJW95niWPzpIba5
            6OurRyytFBiqP4a4c+jigFIWXJeRd/22dQJX4hvCwxy2K/wmG4GpOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdUNrc1VGV0FSVVg3eURM
            MlRHS3F5eHNNN0NaTzlrNWVHWHdUVmdiWHcwCk12THBSRll0bUhOZGEzK2xhLzVi
            QnFoamU4QVlhcHN6UHNZdUJuSTNKbDAKLS0tIEVsQXJzRCs0YmhVZjgrcHp2eExo
            TSs0NjNQQXo4dzBWTXl6RWNJZm5PbWsKmC6MbV9+450Tj/pzVpBHrUdDVNYEsyZ/
            HPoG0Fy0UuOyoSitI3B1eGbmg0wSwSOpasq3rnGrQkB9sVoWoodB0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T21:28:16Z"
    mac: ENC[AES256_GCM,data:hXun1mg2X468mb88aAtXxygE0Q0uD3kPnH4aG3DHUUbqyfvFuj3iBOTPLnu2+hS3aoDZ/URa7pnZqus1maaoBS3+sOsgnAraz4LRzSklCbbfZkwNYVzSycyJGcgHiImLJYmr+pKq3zHoaDsooSFFyTExbLQm30O4f5+gEXAQ9UA=,iv:XWP9NWM5nVTanXspHdnAEwb8Bqc2HZFEYz51aMgIMhU=,tag:PUY3d/FNlFcxFsytiF1YTQ==,type:str]
    version: 3.13.1
