apiVersion: v1
kind: Secret
metadata:
    name: barbican-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:4r0rApLfdDS8JEAEAl3McJV83uP8dNAQ8ypRRIZovxDyUE1XWYoZ23AU4HbgDJKeOlfJKZVE6Y+jiY1nt2o8FJQreH7LJgjtGdB6WtUUnONuiouVrTtTnDtGwbFva8AywU1hKFJdbDSM+m3f879fIroNpebB6wJRdLIs+5w4XA7+UCeO415rGeWuflI1DULDnVPr81X56SWwxey2REMM/SuP76D0LMq3vIyAw0dHdMIDhdEKTxz25obH2TY1/x9fyXPRIuQG2kKYUEr+R6/Qrw6sEAk86xZ8X2kA/RxlP5uM9Vv7NK/RzZNd090ZWxsV6eUkMw/GqK420AKmfPTPEaW9nbliLBBDmicuvZ7tEDJH1gUK4vCXz5lmzLRHhdEa81jaYFwAMhOksdHQXfXEHgFyomPkahmK1eV7w47HFWnKwJWRJk6vOU7nCjtkXLaSvY1VVWBr5xAzqJvblHC5tf+lKAI3yljfsIElQ42VBlyvI5/13O43XG2ZHx3CGdGJ9JD89K8y5rQ9wpnQtYmDn925RatfbDXI+xYBFrI9ICpPx7kmYpdzm9p/86u++i+7iReA2f1vawaLt6ZBYjxGqbzejVvNS2flTQddGz93sLoRGBd8sbVL9rJur6tt11H270OPZP8tU7QPAjYmj4CchHH9iUDvpGl4Vvmbk30e/AE0KaCpeVXJW0LmSM/wyx0NPHdoHxd4ujiRcowm5ayp4eAAHWhm2MixKT5Jf/vdnYsHA+kiczg4iD1pogafQ/YRvVrXSzkSHuVdXW1tAk7aWnnXzaRmxoE0Sq1orLvaTbdscNvyxDvFESDQGI83P2NYbYNFTxQ9kY12fLogInAqORSMA/KmCKnqD6RvEz0cZcYDDSkrcPHd7H3feAebyFezpLvuAFCpO2JO4dZThi4XQIJ1swui81oSM9HNBygh3ahKfrd1w8/XHDMPOM+xScGnvR3DXfWyGtyyjBzNzcEWsm/kG9NHXorbcoPXjxvAUIE7ccYHrE3my5WXPFeQ1WfCgZfjiNz7KPfF6r0S2CgqvFplGmHSE9oBxeTA8gQUC9WjORJraK4wNn4pPtzjloKS1PdCd6ds2mwqtKfaMoqy8ZlvqMfq0QopFnWp2FCTGNF9U++d0Xo5rf9QhyYTJp+5/13z22XwQAQXYL1kae2w7gqJvVReknfpLBoTOg/jq06LB7VGxEmPEmVcrcWkG0mPQRwDfOUppJrbIXMqWgT5iOXpbeRAeYdODDux8Tqs+9zBPNOdN8D8NsUFTTtTtkLQUD/UuHtcK5SlQZlP2ftoTFsnEs+71C8QOnvJtOUnriSVBxtEEl5v,iv:AMBfLKXF16YvJ+WUZm0nTG6JabHp+iYfAUpa4Uof+Bs=,tag:P6rVaPKuuH9PCokBmDqG8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbnFpYTVIcVIxbVN5N25I
            bjRVNnVNcHFxQkxvOGlucnNqcTJoVlI1eUdnClVFbk5NNHNjWURjNG5BOXNtNDNL
            TDY4WWxLTXdBd0FvOHI5ejRwV25lRlkKLS0tIDU5Z1NNTGNncWFVSGl0SExxM3lQ
            dGQ2UVR2a0FMUXJ2NklkTi9CWDRvWWcKzlj2xqdLbmpFtQamTOJW95niWPzpIba5
            6OurRyytFBiqP4a4c+jigFIWXJeRd/22dQJX4hvCwxy2K/wmG4GpOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdUNrc1VGV0FSVVg3eURM
            MlRHS3F5eHNNN0NaTzlrNWVHWHdUVmdiWHcwCk12THBSRll0bUhOZGEzK2xhLzVi
            QnFoamU4QVlhcHN6UHNZdUJuSTNKbDAKLS0tIEVsQXJzRCs0YmhVZjgrcHp2eExo
            TSs0NjNQQXo4dzBWTXl6RWNJZm5PbWsKmC6MbV9+450Tj/pzVpBHrUdDVNYEsyZ/
            HPoG0Fy0UuOyoSitI3B1eGbmg0wSwSOpasq3rnGrQkB9sVoWoodB0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T16:08:50Z"
    mac: ENC[AES256_GCM,data:4Omfhue5meXSFEdXpZWfRBNjLlwdHmIbfwJ/gZl6sY2a6zEg6kS1CX2ymuyMaPNEIiiOW1nmGU7sZSgfmLgkOX+lMZg39owVd8msxGi59dFxNrujEmGWtCvMH/hsbgeonGxK/Fg18MkvDkNZHGYU5uMzIBgy7Je1gNiV9p6Cuuw=,iv:TZccQwxnASGCuSw/Q+6GwmUsM0su8DjHPbs+SyVxMGQ=,tag:pwORXdr4ENMpwIsgrcgWTQ==,type:str]
    version: 3.13.1
