apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: glance.images
  namespace: rook-ceph
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  failureDomain: host
  replicated:
    size: 3
    requireSafeReplicaSize: true
  parameters:
    min_size: "2"
    pg_autoscale_mode: "on"
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: cinder.volumes
  namespace: rook-ceph
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  failureDomain: host
  replicated:
    size: 3
    requireSafeReplicaSize: true
  parameters:
    min_size: "2"
    pg_autoscale_mode: "on"
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: vms
  namespace: rook-ceph
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  failureDomain: host
  replicated:
    size: 3
    requireSafeReplicaSize: true
  parameters:
    min_size: "2"
    pg_autoscale_mode: "on"
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: cinder.backups
  namespace: rook-ceph
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  failureDomain: host
  replicated:
    size: 3
    requireSafeReplicaSize: true
  parameters:
    min_size: "2"
    pg_autoscale_mode: "on"
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: builtin-nfs
  namespace: rook-ceph
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  name: .nfs
  failureDomain: host
  replicated:
    size: 3
    requireSafeReplicaSize: true
  parameters:
    min_size: "2"
    pg_autoscale_mode: "on"
