apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - persistent-targets.yaml
  - kube-prometheus-stack.yaml
  - blackbox-exporter.yaml
  - node-policy.yaml
configMapGenerator:
  - name: services-node-policy
    namespace: kube-system
    files:
      - ../../../../../components/cloud/services/nodes/apply_policy.py
