[unix_http_server]
file=/tmp/supervisor.sock
chmod=0600

[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:valheim]
command=/bootstrap/start-game.sh
autostart=true
autorestart=true
startsecs=10
startretries=3
stopsignal=INT
stopwaitsecs=150
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
