apiVersion: v1
kind: Secret
metadata:
    name: manila-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:O9SypnuEywxkqos2l0ZyeFhB8dm6fuL1vunzQUjajDfmeh9gfXlOtD7XgDjOlzYHXzCYl1/qPEXSmv2BHzumCS1HFhU7QhPGA/GzjTac1ljds08NydPYYrqfEm9DJnGrzKmP+s1XO+6olpWLPbjguKz+anXdXxmevgFdwl6hT3DzpAjCHMUooDIZr5wVcGycO4zsJdfmw1Eref00RIThti7qZHxGuLrHAyvmu0E/4J25ICHH5Yt54ZH09IM08l+KyZ7AINdmAgOGjPw/kUVRh/70puCoTrp2MMiAtmMdAewK/+E99yBc3GZAdMXLoqOrAvhbseoEiUVKQ94nWM844XS2ZXz0kJ8J1Ytt5GVffdOxggygGkRnHxX8LSl/ab6vWEhbvIRVQ9685ex6+lVvvuhjnSsqIawr4veIFmYEjw0qQ5+gu9DJFNn3mLlYYFHEvfjJwPMIIOgtPE5dGEfzuwiA2kUojvcep5jQL3och7I0NJBl3j49Btn8gI2uusn132P4oM34/U9/OhdDzA61AiTmqS9OBpRRM5IukieyetTGmq6olsnmwuWaUYOXF1q4pfl/0wUpZ/46KMEnUtkQ3X482zd4BYgBBi6X2FfWA6YVuSi/rJ6QPXy5V6fX19lMXvKap6oEGwkZBeAuuv16ZPSmyVzewnbcBSXSWDk1ctAuJjdyVBZ7+JApJHYcnrAxkiEqZwylPJ7RWkHfulQER95irpL2VtJQ2PMMDGDtF9dJoKwl/P63ay+giiu7q6DPylPq+lBRuakPcKFN3eTobxT0c3uWIifNW8dyD8pnrJIgHqRLCy143jZ7Wk/8yL9/XgUudu8unO51XPOw1GLEk+OO/xDFsQmlQPtZn60DG/woIboADWA1nrrBI4k8jRbWj6HDmjsTwLbav6lhqf0cInj5jpRordBKdBe5dNef4RDs4dK0EDgpMDQglp4bfocJ6MnqkWeUkmDkJeMlgGTsokhU91nBovJb70FzKSQkkROxnKyITDmrgLaEyz9pfCdaOhqPZZqRYKpPmJ1U7PlKEzjbBGXF82qEPv1lDwJA6Nv1Ob4or2WqsGJ16H0mDTqjlAMqjcNHdh/ZQ0eRTjCVVzJ+xNMy87YNNJFE5/zI90BgtfKMdBvehENpIWgr19PWWvEeIyodP+RQDGbRo37AM2u8neW8mpVjHid1rkCWJC4HVejx/boaZas4E1TeGvGIdsgBTKczn7O7ySxf+Jh5vlXzya+IJ1V/bhRRjBzvJzcmwLen8nO3heSe8JhdWCLZfoE26LrOW6aWIXN3S5dCt9Mz8GQohgh8kmAEBpQXy2y7qASQAj4QLTtIednSU9QyW4LeQJZNwSBOUVru28Jyv+sQ4vSqna6OWsfxEsjzy3mEEkfw8isfpaa0FLGeTIXCiiktbzdZFW3akQqVXdQh4ZndJe/KphmZBFq2toZDj7QbrZl9AeFP3pI87dVbxinxgaFJgfgFpRMwp379zSbs39IOkvsCTp0eDsU=,iv:UNzMlckVVkAuF7DrwzqGVzy8mn4K+vCPptVCaQUaJwA=,tag:Jaoa5Ub4xG5IrQkfPdAp+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb1kralYrRWRLaFErRzRJ
            MFhLMDdNRGQvMG5Nb0NPOFpZNEZ3WndlMWlrCnp1VTdXVWFBVEpPVUdMLzJIZ2h1
            RWdlTDZpU2k0d2h4YVBNY1h5aUw2NXMKLS0tIG96TVBzN0VEQ3hYdG15OStjbGhF
            dFU0UkRSTlprVE02YWx4cnVXcVdrR00KZODJv56WijGlImv9tsOHG1Cc8uMxXbHa
            L8rvRyUmbhngypvsioyhUMobQNnV/8D3lELNj/xRmczEt4p1knJheg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUek5QTW9hQlpvbllvS1lK
            U3I0RWo1T2ltSGl6K2M2RXUzay9tRlAwbzFFCng0YmRjNXY3ZFlvMzE0cXIxOEt2
            eVRmUENCR1ZCTkgxWTFHZnZ5Ym91WFUKLS0tIEhSb3NZemY5NVBXaWVYSHhPaitP
            R0ZuTlNLS0JadVhzNk9laDczN09vS3MKEcDhTkNgBGBVTXNo6qKoVMTqeewG4YZE
            pP4s0bmbKpDDI5oMoGQGpsTlzr8jPVwkobNAsWSti3wmSG5bD28gEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T00:16:49Z"
    mac: ENC[AES256_GCM,data:2x9sQUcRaDoYjxhpmzXFxoSw9JXq+MxU72XkFoo3aLshXbxBStvd92HdR1mbgeSSDEOkE97y21XI6okf02ZLB9JeWn2+c4jGsQA/Rhp3jp4n5+uGuYqXy3XwuqCWuxozbeGuzVRFh3efblQaS6bDT6SHY6a3c7+UxVtOjfW46X4=,iv:ydacl9QZuFYeqxzJuI10Oi8pnuGovqMv8VcUpxyhfYA=,tag:VGOY1KtJfyUXbuuLmC0FEA==,type:str]
    version: 3.13.3
