apiVersion: v1
kind: Secret
metadata:
    name: manila-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:P0WO5zksshiqcO5Tco0fqHfzs5CBQZk/JfT856vHk7hsxLQaiEH3ghOsaDBDB+8oz/h+GFOq5cGR57yoiXwY5oaPhj6pc37hBm6P5AVSFQeuWVfYjEByiNDv4Yd7tk5Pgee+gO1LuAGxXTimX5ZZ7YmKR9FrEJO+vX2eC7Wwti9idqGO4bCMAfVLo5A71Qv+aWTcSD/9DJHXeify1YOvzTsGLIO9Z5T4e6nHBY8xK7LjXAfRn+Jw1kcZ/TcqyGXnmC75he8GAoUt8P1g4GRRWi/jLgZ3nw3EwAnOZHzkMF2hPITV2qRRT2dGQcXUt5Q1O/luAaqjzZYmImHl+ex7Yr47Zum/DNSqdm9wR1OtAoqROpcfKyZm9x7roLQrtZvyG85pn9AVVX97vVQ19Z8N3GWgKEqto/wWfmTW+sGFCldRoVyGUGn2RevRkPRHerTtr6iVarwIGVyUuLu0V79BNx36oRU9xfeXO3FfBdiBNqP3J9SyH5eDlhHzs2Ve76pl/lvqKK6UI0pcAjlo13c6XlwUpMIspp8RazEHjODP9zUYAXltrsHYrykFd4Xyi3+Yrqv89IfLgRLfapXW4MgWSg6RDNRF/WJ9rjUatwWK7M6GfjKgal7cx+t0NopvdXeeEdweukGdC3FJyZEupC9Lzi6eymLK2zJZHjVYzn/bUpuZZXlww4ZlTcK5/BoXzJ+H6p3uliQsUoVRut+jam/RIZetkwuCMN2znjU+n86i3suFtc2W2QSRYwbn3p2o628QYZw1t9CCXMpWP3BEaszeRdSF0aU5LbuUF7uRc7o6i2eWoLQQaITEt6S6H8jNrh80R74vz58OlV8yxJE7wfB8RUiyfY8Q32p0oJpH0isjYA0NhPwEGpAJ+ZSxVj7AkpJP6exUz6MQZZ3j+bxSE0wG3OMVyAVS7eHh9jE1z+RE6mdcVlXYw6qTkRstQKibqNqh/LoeOBD8vtu54+W5v+9aLs6Ueq4s3VI6cKTDhcFUo57HMnqKcH+UfVyKBpSjcRFuz5UGUc2FfRdzeRGPQfbIfshUPI8Luehh3fqf1vq5OsAZmY13fW/uCrS7A/2h76spRmbxqIWbyUn+XPYMeya09geD4NjW8Q0gTpfbeXWblV7U2cXbMyRI6yGCsc6thwb1OkbiZUb9+HxSyoDuacPQOOq8hkFdr8VoN6v/jBbObPiGHapbrQM5LyXz0gobX2jbSgNmcrAianb3p6U1Q+hvSan85Nma4B6NXYgyuvcdfPOoxUk1vHc+oKps9wALG6/UoZ9eYyEn2jYETcaB63Mi8YJNzvwfdFw6+ex1FLJ+C480ZSj6HMGpzmzmSDpUyXY+gIbSajUlJgG+p6pM4mt+NEOiHRAQCRiseTFjBQGl7CIgJnwQEqIKS71AVQnmzswA3/V9JTWjxwJY2MY/Wtcqm7PhAntJrDRUMF3ySzTiIhITD3o5mNPzrfAf3u0DAVYGJKaVAnQvXAWskOwgvJN+WvNSMkpBNbPqZQA=,iv:LYdEmJP2EXXpl+WaVWewxYjucRj8uFUjvXrc03Ic8kY=,tag:2sHArtgkpElp6ewU7t0nFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbEIwS1Y2WVNSSEtNcDI5
            eW0xSlVSaHhPWFB0MXNCRHJXL1E4WFYxbVNrCis4aUdYWG9CTVFuK0VJWTRxMkdT
            Uys2UW5NUXVWR21vYTJnRnp2M2NPdlUKLS0tIDl3VTd3MzNxenBNZGFjOWQ1TTlp
            L0pYbHhLdlFqVTVTWTA3cnBpeE1UaHMKuT6x+Yb7pP9XN9PonkR4+GIKC9PRvSU+
            dUD/m627CwFFYFpf3DBqA12qm+5iqaKaR+HtBSOj0niJFDpILsAPwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4S2hpUml6dXlOUGtxT1RE
            SWxVaTk4QTRxM1l1R2IwRVlPUnVpVzBRZ2pjCjI1Ny95Wm5FeTN1SW8xOVM3cHZn
            Vkd3UzU5STBuUElNN2VTa1h0NnFYOEEKLS0tIHBEZU9TbGsxeXRyZE8xM2E5UDcw
            VER3R1JrN0ZCYVl1SXRjSkZJRmp5MGMKWWzEz9kWGVwYF7cS90jOQ6NU/v76q1dG
            N3E4seQdygz4ib2gFKuXToX7RuwkhsIxaiscpjIv0VgYNSusBsuvPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T16:08:50Z"
    mac: ENC[AES256_GCM,data:0uJvKhOnn8pHoMHPVKAASAcwApNg6noafBP68v3bLFF5X6+DtDJ8JHxcey6+Zgoc2plEpgmOQbn8dFYmK755aF5snymZ7uKz1BdvMN5RlsulPoCw4irWVmppFZscJd1DIe/4kc6H7JSk0SGhLN3ZCond4DyKG3PSnP7gS/DN41k=,iv:BRDYYmuwwEa4/qWAEtoQXOk13pPXr7lnVo7IKtkikyE=,tag:2EEx9dR4kA2IN7GW8Pbmcg==,type:str]
    version: 3.13.1
