apiVersion: v1
kind: Secret
metadata:
    name: manila-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:itmugNbuJA9f0JJ2GORayO1YwgMOPXwDVnHdX+vWwZU6zVjH0R8Omo8zGWgH4J+Jy5OXu0oLIwyLRhtQYHNCrX0JA8W/jxvbTjEcE1feOHGrgD9gy0r8wvbUyOEkGuEmmsVZBncXwphzKust4Ei9xHUwQ9UElqhry4uIFZNTsJ34NuKuZMk7TT1bPo/M28puPw6xry4TnR+g0P+ufLa6kFv/7PYdovj9QmMkWDOoYOua9p0ecuaqQ2JszfYNjQzMRsABAsQG6BGUpsL3YLQp0rcQb0UKEDi399FmE3XGXs/V4p6v/dJ609wKGI37h8SMYTWmIhJKu0P/g0xlLB5JdXiDTT64ZXM8rSwZDCumGDcFV3efXsvCLUXdzyP9xgWd5qAQvxF5b24PaqooRykZg80b4o5eFg1ghAfR+DQKsHPI/ijp1jZAJefUmC1sE9Xly8aikBonLJWU6+eekunUsrD3ekvH7tmoB9ItoOYrQy62Mcho2udrWpEMliZcN8lZHjXAWmukVmqmflZc170EF8xYuVLCVlt2sUBRlHOav03MCFwCfq+cgf8NSEHDy1XrPtVTjAceize5kOM9SrmRGJNyz1XCIGrc36Pv12Xx+pojj0BuDmX2uiWNu4O/JjBz4QB1pQ+aeBmglYmbrhLPJdZsyM/ME19+p8ixuzjZohh/UIr1+P2M7zSu946zI6YAy8LK76uAKajdhxgZxrHB8sYxeEhI/RDVgcVeAkuIFvPYivoV5WRkbevtOp39UHbmrRIldYcq2motqHXINjd7uKfx0pnqCOhrWg8AsjK4sq/CxYVPMrqYpOqwKz7Jh6g9x3PFu+ZRcc0zxLhK5BZ6yMWbV6xRP0mPKBVXd6ur19OU8ujSuHY5Ag+DFZVOYFjVuDKNNXMkkTZkRt8msm0BXcdHEu6bdHb3aUrmbA+o9+9SMAjJ12wvHCti1x85PrQhwo4DGnO8m+PwgdM+DjJIpk0M5I7VHTuGRLFpfFEFEQtjQfQiPIQqhZLHxdpadmHk6ty1ihAhbwd1GGWKZYYPydBaj/h5M/R3NerCy1f5beq0tabZiMVw0wT0AWxztocGgg+MMHogi06xDdFJBS/tR00fTZ0+16pxUOU/x2PCng8daVFJgoYtuJ2bD4LJEySuvvoh5uDPixpcqUpMPk0G7DaT+ejJMBdae7/5sVp2SlKKuaRmJlUjSwe5RGK726gG83/Rm14UCP7Dz0wcnL1vG/HbzGaDNB9n/BCMWxocwIwmSxIi7aPynXozSHmAMeZ4gLYpGJzWhjmmADoZdeyea0NvtfQlh83aZNvnttdIpzCw2i4jzAZbEVRjE7vdSrx3jqRnOpjIKSNNlf8WxJtrvEbQ8Hsu5Uz+2XR8P+vZiyDno87oV8EEosxEZ+zSU6NpiUXFNA1pMZr+wL0GOHVSIZUL0fiJFKxz9jsydWruzhy4d/Soyr3cdE40q+STDUTs4dgzkSL5JE8vwz/xrGFrz6xcwEOuat+eNyQ=,iv:eRasPGPWSKwAbshW81nICzNmOOuxg7BR3Rato1lD1XY=,tag:oDSOIHFLcexMbkpiN0TVrg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbEIwS1Y2WVNSSEtNcDI5
            eW0xSlVSaHhPWFB0MXNCRHJXL1E4WFYxbVNrCis4aUdYWG9CTVFuK0VJWTRxMkdT
            Uys2UW5NUXVWR21vYTJnRnp2M2NPdlUKLS0tIDl3VTd3MzNxenBNZGFjOWQ1TTlp
            L0pYbHhLdlFqVTVTWTA3cnBpeE1UaHMKuT6x+Yb7pP9XN9PonkR4+GIKC9PRvSU+
            dUD/m627CwFFYFpf3DBqA12qm+5iqaKaR+HtBSOj0niJFDpILsAPwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4S2hpUml6dXlOUGtxT1RE
            SWxVaTk4QTRxM1l1R2IwRVlPUnVpVzBRZ2pjCjI1Ny95Wm5FeTN1SW8xOVM3cHZn
            Vkd3UzU5STBuUElNN2VTa1h0NnFYOEEKLS0tIHBEZU9TbGsxeXRyZE8xM2E5UDcw
            VER3R1JrN0ZCYVl1SXRjSkZJRmp5MGMKWWzEz9kWGVwYF7cS90jOQ6NU/v76q1dG
            N3E4seQdygz4ib2gFKuXToX7RuwkhsIxaiscpjIv0VgYNSusBsuvPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T02:43:49Z"
    mac: ENC[AES256_GCM,data:3N3y8VlEq2BIBF/rwDuKsJdpDFA/NLRdeqHOqniuzum6xhg6+u7or/7DO3UBjRNjB42tabedNn5qSbvQwUQKCg5ZYJ/Q7TgmQTq0UTUvJXaSgBOqwx26XYCLdW06cHbtXQVx25zHG3a1Ul4XDSw5EVuuFc3GjZr5LHm4EKco5NU=,iv:o0hmt1QjNSYIuBvgg/VA+VIyRaZDQA4scSxZu43RhMs=,tag:s1luRn/B4zh7g/ZIfIMvhQ==,type:str]
    version: 3.13.1
