apiVersion: v1
kind: Secret
metadata:
    name: aws-mail-provisioning
    namespace: openstack
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8X1ivsxOxYVrLEyagHwEmPGnCiPTCGqv+vfVTQ==,iv:8pT99xExp417aV2ozRInfbSRbvbk+gtIk7JcB5xwxT0=,tag:p7XKYcSWBBYRcT7sOX3u2Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Q8QlexXtn07N319dw3phTPO7IlCLX62WQ/HnQ8uXT7skp9nzLg9otun5Vubdh6LyVGOHaPYVmDI=,iv:1brugFiJHo2/V/QLBE54x9Vnf47i7sWhveYq1bVwVvk=,tag:QzYonEtNmnQuMMHyJYN9Mg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFN0Nzc3lFdFNZM096NFJy
            OG9GU0tkUVZtR3h6RFZiekV3c29IQkV0ZUZFCnI1QlRkeHVaUG9sTnMvWHA2T1Rl
            Tmlqc0JQVHRKM1ZBOVVybTVWZDdBUTQKLS0tIHZ0YUR5R3c1ODl4bG1EckoxUDBG
            d05vQUtTbU5uYzVDN3NoSVozSTJOWHMKk9LiFA6O5+mvRq5puryZRrl+jmJH+9Be
            hwFKcnaaIlftsBdm+AtkPct7kupYMk4tceYa4KYlVfTu+ZZYU1fLww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZjY2MEVVWFYzMHN3ZWhI
            N2VHQ1NodnZWUzV2eEdxY2g0TUxCWEJjalZ3CkVPZE9KMU43ZzdEbGJvajhsdWVp
            dzI2dEVRM0hjOVM5Umk0ekhCVi9oblkKLS0tIFI4b1BHaENPTUsrUVhPZGhFeG9a
            OTB6T0lQK1Y3dUlEcisvcWlDNzBrbEEKwkwkKGqhY9X+krSvuj5WZUoMxz85xRIP
            SjY8St1IMZ/F9ncOGmRWmUMRvjp+bV93fbFPGwDfpgTIYjsNXu8ZVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T19:14:44Z"
    mac: ENC[AES256_GCM,data:uovnryT9nAZXrh4bEEDsR5t789aOom6ITiMFksX7lTQQKmrLB0mita4qdlMkFvlAj9qHfk9MF9FcX0tdAPm0cB4XwdGtUeoTZN36rz7GEu//qxpBfiDAFnNYIf6lzj2jav9dHiL6ag8wRD31+rGvNCLYDeOxKCsemEi5/WK1Udc=,iv:H9d7fqjKKq7/7nrpA7QGH0ohWk7gdakragZPbMHW1AI=,tag:Je1Mj0tKk2no/B3iMJl9NA==,type:str]
    version: 3.13.3
