apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: service-dns-tofu-source
  namespace: cert-manager
spec:
  interval: 10m
  url: https://github.com/funforgiven/infra.git
  ref:
    branch: main
  verify:
    mode: HEAD
    secretRef:
      name: service-dns-signing-key
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: service-dns
  namespace: cert-manager
spec:
  suspend: false
  interval: 10m
  retryInterval: 1m
  approvePlan: auto
  destroyResourcesOnDeletion: false
  path: ./components/cloud/services/dns/tofu
  sourceRef:
    kind: GitRepository
    name: service-dns-tofu-source
  varsFrom:
    - kind: Secret
      name: service-dns-inputs
      varsKeys:
        - mail_ipv4_address
        - resend_records_json
  runnerPodTemplate:
    spec:
      env:
        - name: CLOUDFLARE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-dns01
              key: api-token
  writeOutputsToSecret:
    name: service-dns-outputs
    outputs:
      - services_gateway_address
      - mail_ipv4_address
  remediation:
    retries: 3
