apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gitlab
  namespace: gitlab
spec:
  parentRefs:
    - name: gitlab
      namespace: gitlab-network
      sectionName: https
  hostnames:
    - gitlab.fahrican.com
  rules:
    - backendRefs:
        - name: gitlab-webservice-default
          port: 8181
      timeouts:
        request: 0s
        backendRequest: 0s
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: registry
  namespace: gitlab
spec:
  parentRefs:
    - name: gitlab
      namespace: gitlab-network
      sectionName: https
  hostnames:
    - registry.fahrican.com
  rules:
    - backendRefs:
        - name: gitlab-registry
          port: 5000
      timeouts:
        request: 0s
        backendRequest: 0s
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: gitlab-ssh
  namespace: gitlab
spec:
  parentRefs:
    - name: gitlab
      namespace: gitlab-network
      sectionName: gitlab-ssh
  rules:
    - backendRefs:
        - name: gitlab-gitlab-shell
          port: 2222
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: gitlab-private
  namespace: gitlab
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: gitlab
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: registry
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: kas
  authorization:
    defaultAction: Deny
    rules:
      - name: private-clients
        action: Allow
        principal:
          clientCIDRs:
            - 10.21.10.0/24
            - 10.21.91.0/24
            - 192.168.82.0/24
            - 10.21.40.129/32
            - 10.21.40.128/32
            - 10.21.40.154/32
            - 10.21.40.125/32
            - 10.21.40.126/32
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gitlab-admin
  namespace: gitlab
spec:
  parentRefs:
    - name: gitlab
      namespace: gitlab-network
      sectionName: https
  hostnames:
    - gitlab.fahrican.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /admin
      backendRefs:
        - name: gitlab-webservice-default
          port: 8181
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: gitlab-admin
  namespace: gitlab
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: gitlab-admin
  authorization:
    defaultAction: Deny
    rules:
      - name: operators
        action: Allow
        principal:
          clientCIDRs:
            - 10.21.10.0/24
            - 10.21.91.0/24
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kas
  namespace: gitlab
spec:
  parentRefs:
    - name: gitlab
      namespace: gitlab-network
      sectionName: https
  hostnames:
    - kas.fahrican.com
  rules:
    - backendRefs:
        - name: gitlab-kas
          port: 8150
      timeouts:
        request: 0s
        backendRequest: 0s
