apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway-chart
  namespace: envoy-gateway-system
spec:
  interval: 24h
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    digest: sha256:cfb34ff4266c87a394cd6be5c13607a2dd47083aef771368302eaeaa99c4a0a9
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 30m
  timeout: 10m
  releaseName: envoy-gateway
  chartRef:
    kind: OCIRepository
    name: envoy-gateway-chart
  driftDetection:
    mode: enabled
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    crds:
      enabled: true
    global:
      images:
        envoyGateway:
          image: docker.io/envoyproxy/gateway:v1.8.3@sha256:e7a8c70537628bf996e5dec5c4c835704b4b9f4f715a74cf361bea30608c49ac
        envoyProxy:
          image: docker.io/envoyproxy/envoy:distroless-v1.38.3@sha256:574348fada8eb1130b448132287d76626dfb07525b16668075382f8e154a45a8
        ratelimit:
          image: docker.io/envoyproxy/ratelimit:1e50889b@sha256:5bb3741fd6709bab1d498eae1a5807faa2113b712dfb236fb76c04a00871ffc9
    podDisruptionBudget:
      minAvailable: 1
    deployment:
      replicas: 2
      envoyGateway:
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 1Gi
    topologyInjector:
      enabled: false
