apiVersion: v1
kind: ConfigMap
metadata:
  name: services-backup-destination
  namespace: openstack
data:
  bucket_name: fahrican-cloud-recovery
  endpoint: https://s3.us-west-004.backblazeb2.com
  region: us-west-004
  prefix: services/kubernetes
