apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: services-identity
  namespace: tofu-system
spec:
  interval: 10m
  retryInterval: 1m
  approvePlan: auto
  destroyResourcesOnDeletion: false
  path: ./components/cloud/services/identity/tofu
  sourceRef:
    kind: GitRepository
    name: identity-tofu-source
  varsFrom:
    - kind: Secret
      name: tofu-zitadel-credentials
      varsKeys:
        - jwt_profile_json
  remediation:
    retries: 3
