apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tofu-controller
  - signing-key.yaml
  - runtime.sops.yaml
  - service-dns-input.yaml
  - resend-domain-output.yaml
  - backup.yaml
  - share-quota.yaml
  - tofu.yaml
