apiVersion: v1
data:
    ND_PASSWORDENCRYPTIONKEY: ENC[AES256_GCM,data:Lf6mO6eGwp+rq+Kx6ShjaX5ohJDGGhaMDOp6drIqg4wqg1LDOUPyp8P4cOYlDGTR0dWl8Mt2tynwUePqNOHnNp+Unid9ReYhpzeALJqTu2qYjnXd2IxF+w==,iv:vwP6mZw4/GGxCjbqz44kyQ1pYWtHwrY33yksFw3OanU=,tag:4B4OHE1FvGwXGrWzzY1FKA==,type:str]
    SFTPGO_ADMIN_PASSWORD: ENC[AES256_GCM,data:ROAmh2rbShO1iUg81seaaiEqAbRw5XlllebsD+MVGUuAhGw7ObRamiEy2MGxhGUeg+XhrLzOkvRlZcsCNKzHImVDBgUcguLFWfWVyD+8Bar0sVSajWkX9A==,iv:7VRXe0goZrlOJuCprrgX/CEtlltpMRWQtdPqiCop26c=,tag:gknqa+vwnQycjAslVGCILw==,type:str]
    B2_APPLICATION_KEY_ID: ENC[AES256_GCM,data:7EHIF7uDpnbP68Z70MP/rI/9YcF8zIYqqM2rOQa14CLzCz8D,iv:ULMH9BaVrAb5X1iAQH/ubxQ1DvYS38hfa+yqdqGirhg=,tag:7fe80KkJK18VVmVEjMDMLw==,type:str]
    B2_APPLICATION_KEY: ENC[AES256_GCM,data:+nBz1UdNKydJ+s1karrfUej7K714xm+ViPlXJ6qZLcBrB1ifKqzyRzD6k/Q=,iv:9/OVNDwr1S/LytWK2FyjgBBbwdUOIwnJcmVN2M/uEiU=,tag:oDeL6T+ODZRLUc4N0HwXoA==,type:str]
    INFRA_TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:45wncBQWaCh2M3WH7OOEot2wRyJMBF5qy/UVKV1/bNcMr3q3pUAQoI9aIWrECMZ1Z9namGHE2bThilT3s7aU7w==,iv:I0WYfrir2Ce5lQ4KeydrH2+fOImKs8K/psujrmmltDs=,tag:Wa0CN6atG/SUERn0AfPu/A==,type:str]
    ND_LASTFM_APIKEY: ENC[AES256_GCM,data:DT2gxNxGgn3DIOAI3/CDDcptDUYZ8ALNNjIlQ6b93kaFdomwHxiifS4ZKek=,iv:XDkzzHAv05cf5Q8XWPWLQl/eaWHQ/Ee/4I0qVXpuspc=,tag:8Ay3MV2B6/OtgjMDHsRIsA==,type:str]
    ND_LASTFM_SECRET: ENC[AES256_GCM,data:okSf1EvJud0arP9DAr9IgwWy7vNvZ9B5oucYnI/CGaxYu0XmwFWjWvaIpPs=,iv:eEsIpA+TDkT0iLLzLtvSHLMQFDQzgbA6ZQDmXUip0oE=,tag:ph0MGiSlXepbDFTn1y/zcw==,type:str]
    RESEND_ADMIN_API_KEY: ENC[AES256_GCM,data:QKoLdViqlYqmlttZmobLiSUMM1EM98WOzSe63ryfHj+BxVIIowtwMHgpZRDjY1MK,iv:jen7NaTE9nnz4ja89gRbthcQoldUJ9BksPh72FSUTdk=,tag:XbocqjKRcEjbggWEo0N9CQ==,type:str]
    INFRA_TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:ufFK9BvSURhArLic8yMnIw==,iv:o46rtCSHUrINgtOOYUbpoQK2rjQQkNkgWuKvLax1Tm8=,tag:fV5t3vy4fWHWcjkHH8nHXQ==,type:str]
    AUDIOMUSE_NAVIDROME_PASSWORD: ENC[AES256_GCM,data:KiGgu2flsXKcaHDwspMycig2qmJw77E6joijk82N0j6cT6GQT0GK2cbK0g/5SbvCxFqCHflxdrCY7z24HL3jjcSBfiyBXrqrvehykwzZBX+7ycMrQUJm6w==,iv:ureGe4aHmw9leUZjLlvX/ebo/Uw7zB686C5gIO6WI3E=,tag:k2qmvtp7PLivAonD/OYwJw==,type:str]
    AUDIOMUSE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:pje1YnTLzJSzcK2MtIUPqStaiJwterwRCQKIx5BoQHar3HN4Yd5ynfqcvAMgZGzs6wqbf8epmdntsh4DieRL5OThC6MsywuvJ9qBeIQRyCV40vAgLb4+Og==,iv:+SrOA3dVRxijhcRTaQyf4J+35elLUv+m3EhRUhtzN0Y=,tag:VH/SEF/tOR2Vbl5yGJ759g==,type:str]
    NAVIDROME_OAUTH2_COOKIE_SECRET: ENC[AES256_GCM,data:556Bkfi4/R9YhGWcnJRFnvql213xZVidbNkhRVfsPmziy8WwYBkytJFdvP2ccEOzPDFvAAEAUakrVJa+,iv:G2IWGCS/WFzZRN+JQQt8pgPc1Qr810RX6rYx/G+c0Oc=,tag:z+u8siPBvPYJXrDOtViQEA==,type:str]
    AUDIOMUSE_OAUTH2_COOKIE_SECRET: ENC[AES256_GCM,data:Cz3CSjUgJBvgVUo5P74YJhZNSY8ge3ZUFvAmewVcyUfPvDxI9LQcUPyMyLtvKBaJFuU3nTJpoa4S1nAW,iv:jXMBKKLv7nxgXN8KdWbVxsCbzCOtgxOGQ3uD0mPdJQk=,tag:0YOYhGf3/PXLkPxfcwmieg==,type:str]
    FACTORIO_RCON_PASSWORD: ENC[AES256_GCM,data:XkEdwm9377Qc4BcJ7uuKjzDUZsGl/ZD3rQW1rXgebNlEW56SDV02SxTujK/cg6K458nq/CLX0vyRZccRNBzSWUTmg88djoWKoaZmNAZRTNHeLmOSx5XRAQ==,iv:lYDXNcZiO+x2ZHHKjgWKn1QxoYfd24i1Hey/E2vaEfA=,tag:6bfCZ3MDuhq5oGz3Y2LLog==,type:str]
    FACTORIO_USERNAME: ENC[AES256_GCM,data:HKyQaoQCz41wex5ePTAdSg==,iv:WhPCKbfsBfw1em+VgWkmRz5xyAULkEPZIoRg7D9ZO0g=,tag:hczU0X3isZdroJvt31Ksqg==,type:str]
    FACTORIO_TOKEN: ENC[AES256_GCM,data:vbSKP0+cfAtjWkoGeBbuxoW+zjV6fDM1SA5mce7XuycbbVk93eeyjg==,iv:6e+LdjuvNIWrLFhFVn9E00CnhaDC+1F23Mr7AhkJHdk=,tag:Hb0T8+OQlCeM4JNXWMrARA==,type:str]
    FACTORIO_GAME_PASSWORD: ENC[AES256_GCM,data:385qej3tloyerGacYTnNZItp3h7Q5Wp4Bo5nZLH9kp0yWJRsXWafloj4Yp0=,iv:gdGmemJzvhVKsNKwi0hH716cswGzOeyyeNujWzq8Dbc=,tag:/laGiMEzqB1NhNVVT8fhgg==,type:str]
    DISCORD_MUSIC_BOT_TOKEN: ENC[AES256_GCM,data:x5sVDWeEAKphHvqA6Rdf4WSxHN1dLQgyNbqK1e+QDkR/LPqGoOghDYMG/GY7oYLCMD0TJ9vYYWEHoomOKVAeu0hLrBJxqN0hLLzrhPEGzAwkHnx/vQLSPmtWqCwcoywW,iv:tpTABmB+Mkf/TZRxi31GOxwnRFJ+u3+ZWWjHYZOcqvg=,tag:/ADJ7kFBeEDjJRhjvvZGew==,type:str]
    DISCORD_MUSIC_YOUTUBE_API_KEY: ENC[AES256_GCM,data:/cvanxHDODicoNq9DGKOzlNklLCjjiLyOTK3u+F+PqFrwtIo7O8RQlvn3wz62i+5Ui4dDA==,iv:fT9AYpWUoXBFsZbULoCOQI/4jC/A7iPgkVnQFqCAi7c=,tag:oapzqoX/YkHW19ae9xn8xw==,type:str]
kind: Secret
metadata:
    name: services-runtime-bootstrap
    namespace: openstack
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeHZLTlJHZ05tcldWUTBh
            WDdJUU1FK3E3WlR4Uk9FNXQ3Rll0b0JUbW4wCjBIZk53bUJlZktSZHk4WVU0QTJH
            NGlqTHo0UmwzQ2wvVWlKQnNlSWQwaDgKLS0tIDNFcmsyNTZiL0hZK29UMDBaaHpG
            ZTFycnFsZEdjc254cG50SnBxa3lXMXMKENY+MaUchdEhZY5I+FKcnL6VmqLkUqfs
            VkXS5T8T9Af4FNUVe3u6BKmsWgzzY4Y/vak5v/Jok+LRRcLL66aZcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbkFqQ09oZ0F2RkQ0UlR2
            V1M3UktTTTFMVTRPT2x1dTgxSjBHeFU1S0RBCmVOQXpFSm9aQ1RZUnNyWnByK0FP
            TlY2bldhd2FOeWdKbVhBT2tacnY4Z1kKLS0tIGdaZDRlbmhlaWd6QkM4SGxqUGZn
            WXJaa0FRczBhSWtBb1FOY3RzbjQxTkkKnIU8D4TZvlw+/3rgk9HIoOMc9e+TgikP
            Gpfv0IZsZ7WxP2gOQPksJ2QSSIgVhcTKvRpfYj0ENNqvxAVULbkGfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T20:46:52Z"
    mac: ENC[AES256_GCM,data:SwbtJAKyGYUMmrQpOhlnX4zeWmiCIBlTBOcWoKrVfMrh7cRNdOuvdd646dLWPeNQcnSg6fTjnfNSX0sBBD1Lx20mB8N0uY4sTk6aX1gjyeTigseOfkfdT9n6pr1YaS1A4mvePpLM1derYP7UB2AvOndc0vJuJR92svAA1tUcFZk=,iv:spaM4E6T26Tmn9kn6InPjInN+oaxrvt/WgTgKS2b2tA=,tag:AZzr2jk6ICIPpRPqPOh3Pw==,type:str]
    version: 3.13.3
