apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: mail-edge
  namespace: openstack
spec:
  suspend: false
  interval: 10m
  retryInterval: 1m
  approvePlan: auto
  destroyResourcesOnDeletion: true
  path: ./components/cloud/services/mail-edge/tofu
  sourceRef:
    kind: GitRepository
    name: services-tofu-source
  varsFrom:
    - kind: Secret
      name: mail-edge-tofu-inputs
      varsKeys:
        - management_cidrs_json
  runnerPodTemplate:
    spec:
      env:
        - name: HCLOUD_TOKEN
          valueFrom:
            secretKeyRef:
              name: services-runtime-bootstrap
              key: HCLOUD_TOKEN
  remediation:
    retries: 3
