apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bootstrap.sops.yaml
  - runtime-contract.yaml
  - rbac.yaml
  - reconcile.yaml
configMapGenerator:
  - name: services-iot-reconcile
    namespace: openstack
    files:
      - reconcile-iot.py
