apiVersion: v1
data:
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:3eorx4xLmt6dS2mzngPT7KwqCoaJP7l1iZb3mzncRNOfVzmpBNyJ3Epaga/9rxpaJpAk1sYMCu4lXZArj9vhDf0CYLjxu2gP1vU6PZ1qYrtkIXJo5cjZaw==,iv:MbKP8f1dMMoY3AztXSDr9qa1uDfWmbGvdlfzMpO+UVs=,tag:SjLvrAIa3qiqPU0TlrUj1g==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:Tl70Ihxgu9EtLQR0SakLiQ9BsKQTxRlHcLTfqkWy7FfDYyl5ntfiUpT+2HGrdHdiBl4Ec336TdyLcsbnXvazadwaIRXapaieFgOQ8ps9GRxc36C4G+Jmnw==,iv:9dNEKuQBKg2jsoCh3/D5N86tJWkm0WFV5trXq2l+E5U=,tag:h05r3Ry9nWYz0LfWoMD57A==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:cutYi9IlfcOte1DTBl5hLmrwgl+KNkc8ju7q8XD6y6UloGVYWRDmEOKdv07EQPpND23AMRL56UGVElg2PDPrCQ==,iv:5sJVDhIjbsOZR7mQOCyX2wRnpJsze6JULCA1dpyxNeM=,tag:fg/biLYEe++LSpFJluWRBA==,type:str]
kind: Secret
metadata:
    name: services-runtime-bootstrap
    namespace: openstack
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeHZLTlJHZ05tcldWUTBh
            WDdJUU1FK3E3WlR4Uk9FNXQ3Rll0b0JUbW4wCjBIZk53bUJlZktSZHk4WVU0QTJH
            NGlqTHo0UmwzQ2wvVWlKQnNlSWQwaDgKLS0tIDNFcmsyNTZiL0hZK29UMDBaaHpG
            ZTFycnFsZEdjc254cG50SnBxa3lXMXMKENY+MaUchdEhZY5I+FKcnL6VmqLkUqfs
            VkXS5T8T9Af4FNUVe3u6BKmsWgzzY4Y/vak5v/Jok+LRRcLL66aZcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbkFqQ09oZ0F2RkQ0UlR2
            V1M3UktTTTFMVTRPT2x1dTgxSjBHeFU1S0RBCmVOQXpFSm9aQ1RZUnNyWnByK0FP
            TlY2bldhd2FOeWdKbVhBT2tacnY4Z1kKLS0tIGdaZDRlbmhlaWd6QkM4SGxqUGZn
            WXJaa0FRczBhSWtBb1FOY3RzbjQxTkkKnIU8D4TZvlw+/3rgk9HIoOMc9e+TgikP
            Gpfv0IZsZ7WxP2gOQPksJ2QSSIgVhcTKvRpfYj0ENNqvxAVULbkGfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T21:35:22Z"
    mac: ENC[AES256_GCM,data:Qo3YeGXMHwxFVvZ6X5fVFQ8YF5/f1nG517kaQAX1dUgFpnlS6mYnaxgYziyU05WKMuQbrOkZbrTgjAC2IVGYrnaB1CzTiSc4GJaW4ZfOuYCeL4OJX2hKIbb0Q9RNa8SRsvy59kcz1jY1YZYgfv/M5JQ+6q/4YLVr7gUJcZBhJ5U=,iv:cbedYiQWd2PWjOS6OTwBZCqcoLNUKklWhknHbiDMOZo=,tag:5KYVUnL3QK75RrIFUcQouA==,type:str]
    version: 3.13.3
