apiVersion: v1
kind: Secret
metadata:
    name: zitadel-b2-backup
    namespace: identity
    labels:
        cnpg.io/reload: ""
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:dpTtuqNE4iYZJt7RJoKOrPjgh35znPqAtg==,iv:4nX8csJQqOJ81pUe8xgv567G0g8SjzWWWq/8mZ+JNQw=,tag:TaNifCrxQkPz+nQGsuGwgA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:4JUNyI4FY8z4V11Ilmw70a7KV3mFUT3IDiEbNYcoWA==,iv:TVZItxkSCaVNt5leL5Gbpbj+v7cdTOfGox98Cp1kD0E=,tag:sCjGARRAcdLOG5ohZpvbTA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:xOkyW7Nwdi7MN5o=,iv:HHFusjmWkip4yHFyq2vFB0zaR5imIwiuPvIxKrNoqyU=,tag:HGGD4IcO+GLo9MD6Ao9d8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUd2VaeVFzQ3pqL3Z6dHd0
            amxINE8vV3o5djE2clMrb09FQ0JNc01VYVd3Ck5acW02REFkd2Q4cHp4MTlZU1pT
            SFBQaVNKNVFlVE43STJFTFNCcUN2aUEKLS0tIE9GZUZCT3VNeU9xZExrY1lZMmMv
            bHdIOXhCa0lHeEdVbEk0VSsyQzRaTGMK6w1x5ZpsZ2LnBZrJaZv+XfogknwhiLop
            N4ug/rB7INqo/gTj0hTjeIrNIcS1ggswdPN+52cv9w+YQJJr8W6A1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRnVCWTNSUmhRemxBVm1i
            Rlpmai96ZXNHKzdIV2FiVEZDOUwxNTJaK0cwCkJwamtaa1IvcDJGRmVaMmxxQ0Ji
            dGYxNythTWkxRlZpMzZBdklvdWdKNTgKLS0tICs5T29udGdkRTFxWUdsRlZwL0hM
            WmNSbTlQR1A4bTMxdDdGZWNCa0FtdlkKFZPOkApoficfYllJHxrzL6Rm3COC/LmI
            bJr1zL4i6W30eAArHAisRTZGg7R0sSRfgOsZFfC2R6ccIZLFRsthbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T10:02:58Z"
    mac: ENC[AES256_GCM,data:25Dm3Mk7XR/qWBGXbeYqnsxXvgzqQIDSiDFeYeWhZ28eNKCz1lILkYCEALK3ZsT5Pa6GIzNzl/2c1yXtFws7zXgQaP2MSUSvE6lVZBkzPr+cv5LTyeVUaswooIjQGFzKWjMMo8Hwlp4h9hjZIL3NZyugDRT6856BfKleinAezos=,iv:V91Geh+XFCWMIGj1SYt76CK5CZpWclBJL8qc1YbhmbE=,tag:Oj2p/5L61nVxs1NVfBvZgg==,type:str]
    version: 3.13.1
