apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zitadel-postgres
  namespace: identity
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:f0cc49632b5cc1e51f65ba03658c89bd31d64ea2672b14843a808a8d281417e1
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: zitadel
      owner: zitadel
      secret:
        name: zitadel-secrets
  storage:
    storageClass: general
    size: 10Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1536Mi
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
  postgresql:
    synchronous:
      method: any
      number: 1
      dataDurability: required
      failoverQuorum: true
    parameters:
      max_connections: "200"
  monitoring:
    enablePodMonitor: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      isWALArchiver: true
      parameters:
        barmanObjectName: zitadel-postgres-backup
