apiVersion: v1
kind: Secret
metadata:
    name: zitadel-secrets
    namespace: identity
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:MQ3Rw2qn2Q==,iv:ABtCbbulJFFvMV7TTXQUnuI9/zYzNvtTtFfbS7bB3Io=,tag:OsA16hB8tTHHrEv+OpT77g==,type:str]
    password: ENC[AES256_GCM,data:rDWY82h+Y2P+x9SkflhY/wDXwNtvkVFK0R3ORUr9fCHau2Vv5T9Kew==,iv:ZFzcvNnElVcODrhdsH4kTKZgrgXJczIYmj7bMi0W8N8=,tag:Qx3H6axgXqR0voDHCPP/uQ==,type:str]
    masterkey: ENC[AES256_GCM,data:Y+sD8YBhrpbHp01Cx4OWEBYtqNVaKOVuzFuy+SsCKnc=,iv:lDR/6BZq57VZurAJCZKwRzPBSvnFD//bM1DiqPGcnzs=,tag:TLyc7iUfwj0LqxPDdYdYtw==,type:str]
    dsn: ENC[AES256_GCM,data:fgZVG34aUb49bBJmODNv6QBtql3iZl2IErMd+egex9w852nYJqBrtJAnxBJFN6Z0YCcX64uxH6ZFv8S1sm4jceu54nHsOx20Ua48Ino5t6Ysl+GDEoM0l+4d5yR5cHOAc4H37f63DXCnnWviaViXxQa4VRkQ84oAVSTGMo8u/yNY1b81CNvxe7s=,iv:sOP+vrG1JgbkOKGujlbsJK7mxkeImv7YtQApBgJr1/Q=,tag:IfWJ4AuCMedgwllgOYsj5g==,type:str]
    config-yaml: ENC[AES256_GCM,data:39HZE8O4HM4MjDLYRcvz09J0EBQBbvHn0TkKDDvs7+YAacCvZm4Iati746igfKjsCxZd5GBCmB6nC0RwxFldSwaCeRh5Z5q/QItE4EDBjIRiKTqeNpTEXbfP,iv:lL1QdtUnN937vlBtnpiixzsOajvzt3ix3KdzE1bJBAY=,tag:3fmiRkj25Ds2HmH90gT7oA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvN1ZrRnBxYjBWemhORllS
            NDFqajlkS3RLN2x6eVJ3Y1kyRTlzSVV0UWhnCjlGRGJvdXFDdDlIM3BoNGlJVGd4
            L1h6TzF0MkdvN0ZLcTFxVjVLVWRhK2sKLS0tIDlTeUpQQkdncHhWb3NTYUFKVFN0
            WS9DNDVWN3BYVmlQcXR2MHg1UXpGbG8KaAHujgq4oupZhzjXXFmOEaej3maWSsF+
            QFVeRkylJ3hluulYi+pmAunM1/78mAeDGCPWzNfC5GQuje6WZis7YA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwR1JFa2IvVTJKbFNZUkxO
            bGYxZXRNdENuUnBPRTgzRHpJZEEwaEZoNkcwClNUdml4Y1dNR05ZRFhIZDhxZXp2
            b3BvTE1YUG5PNUh4UEVtZ0RWUVZnM2cKLS0tIHlCZDhsN3VXZGFsR1ErS3A0dXZm
            UjVRczhtcHFVWVRDcEpLVHVSYmVNOTAKSuxEVble0IPdpVjYHvneYsr5uFrpfCVY
            2/mlS8/W3rStBc66PoAoMojEUKIXDxBt0UeRk+LwtAtA66tjN3tE3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T22:22:06Z"
    mac: ENC[AES256_GCM,data:p/JdgpsP0rtCDUS241Pus9ayI9pNlX2RetQWhJY+CzqHUFqZLwDWDwimmjTNE8ZpzKWy69hL2gQ009I6x9Q0UGU3QByjOdAhgNvEFEaD1eQDX5SM78RT5zBIIbx6PguUd881Bw5cIKrV64bTVdAQndgC3zO5FkwupPhP64Yfvto=,iv:f4LaJkC/M/UexK9nLgLtxbhbqit3Nso8Nce+xFTNszM=,tag:M6CkXGNLJR+fkb+1Aj2MnA==,type:str]
    version: 3.13.1
