apiVersion: v1
kind: Secret
metadata:
    name: placement-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:CXavSD0Z3EcTnzbQ8QyKqehGjnk87z4VXyW5QbCs88p14kGq2hh7wKKRYp4dZRUjVKHNwsLnOnElbP3iN8PRqicAjkCyZif5JN4cbRAuL7L1I+Ec8EMDfcrZ3yx+S8aXJbeG6/4lKOcz0P4mczkKzlrdZGaiohTF31nrAswRjRD789d8fpeDgCuQEnjtqXJa04L/di1ONe7Pqibe8WOLh5Ju+hy/E82/tNVLzRYZC2T1XQa6Tqt6O4YkgJh8DJqvlqkQuWoeburdPqJY4gVwfyD3fbXDb3mltzIIiO1vaIF3yHf1tEiK6u5Jo+wDj6gsyxT2tJXisyVKcIf0FzSZleo1GGWhEgtNk+Qv+Gzb6iqDCccCceZ5pgElxp/sbHO4nw4C6jZ1pBemXGZe0eAED3aSE0gWRpdD5BQuwVfapvDn8ewXJyWrrJlK9fGTxqI1WrBZI3Vk/ojNflFgcDVJnX/iNOiTQtUAYV5XTJnNHjAwns/mzB0Z2ERLlh2V96s4V4kmdJeI5DqSovM6h0TZoia6NvHL/jN/OllKCDtiUlwgwLsQlJl5HhUP5kObCPG/Itl5yPgG3+eHDDwuQXqROlFQMj5Ccp2QcMPgadnInl3kD4W/OUltWKuY7bRnt/pruGc6NnZPSAqQnJcLBnldhYEJuhKFS8ztFOVPqzbo9Zed9w==,iv:91sl8hlNKRkNRqKp/9nPejeojl2mfxo/skXo7t4p2nc=,tag:BPQKtNWZ/VRg6CbR+nXEKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SXR5UG9YWmVNYWtzY1Av
            UktXR1QyeE5ZN2E4MnVDQmM0RVVBLzNDUkFjCjJwejluNmxGUmt1UG5xMkRXU3ZH
            UnRWcjNCY0tGcjdqZnBjK3VHN3F0U1kKLS0tIEtBcWJTbHdkRkdjNERqVGNERFRs
            c050aDdldEZiVUFEQzY5aEdvOU1Zc00Kto6XfdwI6P1UwUynyA7NuDsM+t7MKMfg
            eFaqReasf2EvaSXm66qzBTgRJ5Yu9520PtW6uPEuEOVkKcOPme9U4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNHI3eXpOeDR0cVdzaW55
            bTNnL2g0Z216SHFFSko4OGpVaTVTRFJiamc0CksxY0pMSmU3ZlV5L3JmbWkrSGFr
            aFRIL2ZQNldzc3ozcklNY0U2M0p2cFkKLS0tIGQ2dUhhbFUvYlJleUhSclJqWDNY
            SEZFV2JxWEdnSS9QdkdwK3Yrazk1TncK8leXn0q1Xqcs9IFcNnk4u8C1i8y/0ofw
            x3pSyOdOgBKzrHvw/ChK/8zURjU4SSgDW1qnXW6PJZ63ttBqcaJT4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T00:01:03Z"
    mac: ENC[AES256_GCM,data:tb6xQAqZCqePog0ukFlf1aVZvuCetI//uh6eZXUTsiJBf/y1GTW51FfGCpcRV2nkyAZaMnHhpOIGCawhM4t6dHlfNjEtU4Y7EXwSrMbgDsMrk816s986Vd+lHFocFAcRxuLaJ3n8EVbfey9HUZBRG4pLraE+9TIHJXemwbMkfRI=,iv:RIHr/SIuiZEtG7yi/P0I00oOH9PyjKCg2dlUv/KL8hM=,tag:Y1dF8zE/gJ6/F/+rxJFpiQ==,type:str]
    version: 3.13.3
