apiVersion: v1
kind: Secret
metadata:
    name: placement-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:8rqp2xl7/F0t20tbbMT1k++9qy1hsAzXhlA9uUXiDA8MTMAS6QMV/CQ5PYcgeXwo+WfgPmTbfvraaIxTp97c00jExnMHcRNM3HEK5bEbFkFpBXwFDgvcN8VD4zLhN4iMQkLmpQogFAEWXYhFtDpb41zWJG49XP5H7KqI50B4QokdI0WICx/ib6J7sjGLEbMf7+RIcUyQ9BslN2D+uDJ954QMQsurUIoz8kNnVUZoAIATseULUCL+RCPtaRPj4wfzfvANWY1rm+H/W7xGjyPiz0XbvIyb7G8Im2oq5NmjYZW/g2xuJ0S3lqZhuREQ+hXT0SFOFmlsEO9puDYhSC43fEynxWWutw32scSIKkjfAcAkJDGjRvSBusJWlrVwaPYEOJd7FYLhJAJN+zOCDMo4/omOmYgHAlQOAQU+7a0e/cn+DnBH78LNYLov+02eYsWMXd2dTyeKNkbrDlHU+c17QFeZKQ5TjuOxEtirc3Tzv38wjfQULIPHnjJFujN/uHiU+POToebn5iirZZxIB7Exi9pjGifz65S6q8zLOdcdsv+KHU2flTvzPCShyQC7LC068AscZ8mwwy3bwWh8CwdfPsZ23gwmBOfZqU4QsmJGtM968P/4jQ5vDBXvSncIaYAW1tMv,iv:d42ogZjsuX3yJmQ9ZbZ9mHBVDz9JuVbm+vbocIAJ2U8=,tag:ouZct7Q0TQCectfdwigmgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NkQ5NlJFQUVZcVZzS09O
            dmZLU2ZtRCtDcUlYWUxWSUxSV3plTTVJNm4wCmFWYTkrVzB3Qm5iS3RaeXZ6dE9p
            TmxUSWZKYzlwSEllVUtjUHlGV3pUM0EKLS0tIGtsY2hoNVBwdGcvbThRNWdrbUFB
            NFVIVk1aSEpaSXRKTytQOTJONFVLTk0KM/d9OAynh0Gf11cllw0DEhM5bvNXWs2x
            HnUWd59iRr+r9+lshBHuzXIxgqskCTZHrsm1Q3akqTxxN7VM3y3s0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeEoyNFdxS2M5TjZzQkJJ
            YTFJZDRIZVpDRWxWVk9ZQ1E1bVljeDdqMFJvClFNdTZvRSt4WXVweHovUDhmMFdB
            MXc2ZFBKWHpIeGRxL3ltcUpyWkpWaFEKLS0tIHlxWGl6TDJiOGlXSkUzK3FSMVdE
            a3hLaW5DZXBLUUl4T1dSWmhXZ1MwN2sKM8jgOF6+Y8/Ti9qG/awP+TE64K906e91
            KFXYoXnlPNsD7tQ6ivSG2MaA2GRr72ScfxlBP1MUJ+6aDmsZ5UrJzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T22:18:10Z"
    mac: ENC[AES256_GCM,data:oDgKylbgCbNtVqt25dccKvPyvq62/qusiM5NRlwYumuJ4u5Q7cnv0XHLkpNxQDbByBUO2DM+q5SO70QDf/IAMn9b+3OEZmBOrTHevhkEBmDMyc1gT2rcDzZv8AcyQY7XVcWk4J0ItQpJWowlYjHFZ7yiBYlu1thvJyyIO8E47B0=,iv:SOxV2KykbxrphBIjyBLrctU6/z3HVcm2shw9BL44SGo=,tag:luFyj9pi/FLITdsXeuMljQ==,type:str]
    version: 3.13.1
