apiVersion: v1
kind: Secret
metadata:
    name: placement-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:jlo5dQn5dFDj4j/L+Ou7u9erI/XoIYxvMF7pmVDhSoQJ4agVjyzkA0RNWZGn5KYn7/6b6OFJlIzTWZUFNHxmmL8eSo0Uxf/2gQzKk+/t0CnjpE7PIpCr21EemEMqO8uNdI1uTkP25LfYLTYJOVKopM3VP7/QPg7cf3T464pQSUaxdegzyaXFpMmQWJps7XxmNjjwWFwEMv/mdlm6Uc1ctkJi+rrYqkr1vH8F7IYOvAcdZ9yvcoMfv1dB7ROFoECbay+a85HH8wDoJUafOvQxwMFFsem8bU/4aNXkspbtkgqXSsO0kziFV4XZl01ylb2CCx8gZdo79IfW3afAchA7vzMV197izH/RGLyAHGICBXrZtZhRIHZ7HzEsyeu0QCdtUktDLAXF54Hbr8zYnhZB+T5Uq2BXjMRli3CkDtrVXU0WFFfHx+qvHgiL0/xWEbuWLwvl7DqcExQqCdih+3qF+KmJT5OnbVQmt2AHJMz8tmBxC3Pr7NwT1iFuA1d44NpecSKioZdEZn0OsmH6gTU9lyhZTu/TLh5Z5cZsZY8lOgrfx8WxXYqedrfpYu5kYIMLkxe8rW09iaAD9i2y3n8iItpOeSDJWuWtS61oQOtSiUPD4M2GiOQOPdvIeE9J6n8ceEr4MWMxABMqm4zu8xfkdypRPwSIoNKdj9Oerq9MJ2XlJA==,iv:w7z55rSjF5K0WmxmWGMbgNpvizWuZARnNY5FeEtpsvw=,tag:LTOujygBNVDXqAGW71yPRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWklrQnBCYjJQWjZRS1ph
            NlRQQi9iZmxjam5wblF1WmlXUGxtMnRNUHd3Cnp2bXkwS2hlQTJQN05GOElZc3Er
            V1hIbVlQV2sxOERBUjB0eDR6WE15UkUKLS0tIFdrWVdIY0tJdW82RlhpcmZoNjY3
            WVovWnRrY2Zsa0w1ZkJsVDZxRFArRTAKQXDjW9jVDIhn4P/yJUuUq/PHttVzz/PL
            sE6Te3NY1cbkWgjWdyjOz0tbcOk4524+eRzUE1hNbQMDyyLjZhX6eQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUFdyZ00zQlJzeUhqZGd6
            M0Z0cmVJNUw1WjVLTThQRDFySHI0YUFBb1VVCjc1Tit2czI2bnJEa2xSQm40MGYy
            STN4RFliMHFaeVJrNm9nZzRIcmNpNHMKLS0tIEJ0dDcxZ20vTG90QjljSUlwVzVu
            RlRBSGlQL3VEcTc0SlRUNjU3akNXNVEKc5VfHZJXJRlJAZ9Qh3CgYX0YDXeli+Sg
            tYmds2tAD2OZQ69IStg1+iE/kBThRRliYOFF17bTFQD6WQOBVj4/tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T00:16:49Z"
    mac: ENC[AES256_GCM,data:qVqtfmdIO5LkN/HlnXP33pwXiTatJtyNfpQuXqpOADAtQFKsEFt2q98SJdXX+PGiN3lKtF2wZgTjh+Dok4+++CxrGMmI2dAwYAZDgOPgSKtG3WJ2gb6nbkQ2wEGmkgGHJlESWW7ntD2vKVnuzaMIrRma6Dh0/EzizYTNVEuF9Cs=,iv:e+okBPIMNANVShNgK7mFvxR0XIxj1k5OG3NUgEVOKfc=,tag:xugeei0SRg50Y0Bas2WWww==,type:str]
    version: 3.13.3
