apiVersion: v1
kind: ConfigMap
metadata:
  name: audiomuse-config
  namespace: media
data:
  AI_MODEL_PROVIDER: NONE
  APP_DATA_DIR: /tmp/audiomuse
  AUTH_ENABLED: "false"
  ENABLE_PROXY_FIX: "true"
  IVF_DISK_CACHE_DIR: /tmp/audiomuse/ivf
  LYRICS_API_ENABLE: "false"
  LYRICS_ASR_ENABLE: "false"
  LYRICS_ENABLED: "true"
  MEDIASERVER_TYPE: navidrome
  MUSICSERVER_LYRICS_TIMEOUT: "20"
  NAVIDROME_URL: http://navidrome.media.svc.cluster.local:4533
  POSTGRES_DB: audiomusedb
  POSTGRES_HOST: audiomuse-postgres.media.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_USER: audiomuse
  PYTHONDONTWRITEBYTECODE: "1"
  TEMP_DIR: /tmp/audio
  TZ: Europe/Istanbul
