#!/bin/sh
set -eu
umask 002

media_root=${BEETS_MEDIA_ROOT:-/media}
state=${BEETS_STATE_ROOT:-/state}
beet=${BEETS_EXECUTABLE:-/lsiopy/bin/beet}
inbox=$media_root/inbox
library=$media_root/library
quarantine=$media_root/quarantine

mkdir -p "$inbox" "$library" "$quarantine" "$state/cache"

# Quarantine is a short recovery window, not permanent duplicate storage. Only
# prune the top-level review directories generated by this CronJob; manually
# named paths and anything newer than 24 hours remain untouched.
expired_quarantine_count="$(
  find "$quarantine" -mindepth 1 -maxdepth 1 -type d \
    -name '????????T??????Z-beets-import-*' -mmin +1440 -print | wc -l
)"
if [ "$expired_quarantine_count" -gt 0 ]; then
  find "$quarantine" -mindepth 1 -maxdepth 1 -type d \
    -name '????????T??????Z-beets-import-*' -mmin +1440 \
    -exec rm -rf -- {} +
  printf 'Removed %s expired quarantine directorie(s)\n' \
    "$expired_quarantine_count"
fi

# The pre-Beets library was written directly by SFTPGo. Catalog it once without
# changing its tags so duplicate detection also covers music from that workflow.
if [ ! -e "$state/library-cataloged" ]; then
  "$beet" import --noautotag "$library"
  touch "$state/library-cataloged"
fi

# Apply the native release-group presentation policy once to cataloged albums
# that have MusicBrainz release-group metadata. New imports receive the same
# fields through import.set_fields in config.yaml.
release_group_migration="$state/release-group-metadata-v1"
if [ ! -e "$release_group_migration" ]; then
  # Beets expands this field template; the shell must pass it literally.
  # shellcheck disable=SC2016
  "$beet" modify -a -y -w -m \
    'release_group_title::.' \
    'album=$release_group_title' \
    'albumdisambig='
  touch "$release_group_migration"
fi

# Normalize only genres already present in the library. The acceptance script
# replaces LastGenre's network client with a hard failure first, proving this
# exact cleanup path makes zero Last.fm requests in the deployed Beets image.
lastgenre_maintenance="$state/lastgenre-offline-maintenance"
if [ ! -e "$lastgenre_maintenance" ] || \
  find "$lastgenre_maintenance" -mmin +1440 -print -quit | grep -q .; then
  /opt/beets/verify-lastgenre-offline.py
  "$beet" lastgenre 'genre::.'
  touch "$lastgenre_maintenance"
fi

if ! find "$inbox" -mindepth 1 -print -quit | grep -q .; then
  printf '%s\n' "Beets inbox is empty"
  exit 0
fi

# SFTPGo publishes each file atomically. This additional quiet period keeps a
# directory containing a multi-file album together while its tracks arrive.
if find "$inbox" -mindepth 1 -mmin -2 -print -quit | grep -q .; then
  printf '%s\n' "Beets inbox changed within the last 2 minutes; deferring import"
  exit 0
fi

if find "$inbox" -type f -print -quit | grep -q .; then
  "$beet" import "$inbox"
fi

# Successful imports have already moved their audio into the library. Preserve
# anything Beets left behind outside SFTPGo for explicit review instead of
# silently deleting duplicates, unmatched audio, artwork, or other extras.
if find "$inbox" -mindepth 1 -print -quit | grep -q .; then
  review="$quarantine/$(date -u +%Y%m%dT%H%M%SZ)-${POD_NAME:-unknown}"
  mkdir "$review"
  for candidate in "$inbox"/* "$inbox"/.[!.]* "$inbox"/..?*; do
    [ -e "$candidate" ] || continue
    mv "$candidate" "$review/"
  done
  printf 'Moved Beets leftovers to %s\n' "$review"
fi
