apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage.yaml
  - sftpgo.yaml
  - beets.yaml
  - navidrome.yaml
  - routes.yaml
  - monitoring.yaml
  - network-policy.yaml

configMapGenerator:
  - name: sftpgo-bootstrap
    namespace: media
    files:
      - render.sh=render-initial-data.sh
  - name: beets-config
    namespace: media
    files:
      - config.yaml=beets-config.yaml
      - import.sh=import.sh
