apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage.yaml
  - sftpgo.yaml
  - navidrome.yaml
  - importer.yaml
  - release-watcher.yaml
  - routes.yaml
  - monitoring.yaml
  - network-policy.yaml
