apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manila-nfs
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd1
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftpgo-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd1
  resources:
    requests:
      storage: 5Gi
