apiVersion: v1
kind: Secret
metadata:
    name: glance-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:RrQdEIRzdTS5b6KIsBBGAnIq3ZmMcaqlxAAlzSLgStw7RxSCnzHzAFlySfjA1284QNKfUax4odqodgVjdMsMRoMx6/SnnvFlKT5/3anuLk75ESuQWiDVk4bvTnTLBXKN/L79tKo/T1mZeJNRGLY1w4e/BTYIN/M1Pbm/8ljnjUDfVMNWID+0AyxDqGDaNBuXexSj+sJyRgJfbu6+jhGPltWXPDOdkKaOFpDrh4QSwaRtZOf3PhGxRys+Ma3G+p50gPT+8XX4tAKWzj0dYknwmF+AVk51l+nDJXT8IJf2YNh9ImQygHsOnBaLwCipS0vLZZprPTQ96dpjVPTYnPCcxmrLMbPNReLMQRpVsSCDRPEliHYoNURcn3WpqxwZGldYGhh5S2QT5P+VgN0gXpA0GGq/gtOMsAcsmtlUAwxy7LlUxdnouLPPPriY3kJGZXz7naW4ZmCgh8GKkAwomSmS1ZBQJxLDtu8139FLeK+GusIxEA1Em4g5ViudhX31Z1uvEXGK2/J9Q2nDjvooxyuq1KgvxKhKFuGYNd1G4kIlllDA22ow3HUq9W8Q2tjN9vSyNfcWRDVVL/ZW19ltG+10QlCnBgElqzt2Sk1KP/a2kIBWbDyn8SmTNdoUoe2FYibdTA/ixoTr130WLy8NBU58AiFgfK/XZOozyDlvoK6BF2GORepGBaZkcekK3+0j3rWbud8GQNEW7IKvyTHa5jO8uFTx9SA7PBS04/kImu0uvIVHLE7bcs6X9peH6uHk+8NVPNXP2KyEM42HFfQjXnt9E5aM7Y7lbFT3gErKHsKAaDOFlqJ7vWjRr0uc/JS1qK/jafc3SphL1apBV/IcHKEZb52ui4TeSINHueLjnLIGLtd3HQDAffDzfSulrvypaqjyOYi3CzfEGoBRiZtl4PJtqkPErABUNLPLFwWpnetWcY/Nmag6u4Lrn2Z1J2VU65Xh+bKx7h/JVnr08qBTFU6KwPfwkI5RLnzX5z07O/cOXmM5H+XNay6NunkGfO+1bwePTRWtd/A8mVv1Xqz5hOQh71ELBvd94gdpbi3Ah+wWGPsedBhrsVwg8FTHa7nMvANJPNE60+qIyqwP88479GpDAitWhZlxkt1zz5vh5khtf9f3c2oYI4SxaEOaL/rA5lTjNnmvmQuaA3QzQGVGqaA690jNlZiXSUfPFoEziXN5QhdhtSg=,iv:Yuelakpqyr+f2KcLOz3MIwCsC99H+nAZ1b6ziPMyEgQ=,tag:zQGr+sWtjUF2JxqLwibxPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUkQ1NS9zTlMzZVMvV3Mv
            ODlDN0tBTmMyQ0FReTF2Z2ZkdzFQVy9ybERvCnRTckw3WmpQVGxyZW9wcVJDVTdL
            SFIwSkVaUGIzaEtBQUMvMUJ5TURGcTAKLS0tIEtlMHBVdTlaaFJVbXZnOVhxNnp4
            ei9WL2JWamhhNlhyZ0hPZlJpN0RFWkUKxhq+ktnxm6hKVvh9qDcMD3xWKcvkVjZc
            dnoyA1t3JcDmXG0vJWIshlj7j01fYpNU8S1JznpruuN69WN0TR8Y+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aXgxK1ZIdzdraG9TZkNE
            MFNhV2RFQmhqeFZGYmNMTE1nbC9KU2dvNmtBCmIxRWl4UllGZUZZdk95dmZKR005
            TCsyaENWNCtDZ1dGdmNvMURTcHNsZHMKLS0tIGpMQjlSM2pTalBsR09wa1hMaVN3
            aVA5MmlZRmdzcENGUDFtYzVQSW9MaVUKExIUBY2EqJlbgeUKy3FV1tpx595HzJhO
            xzj9rVf5t/TgibTmM3KWah/b/cxz9BeuRtV83zJ69QCvKQcYeH/W0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T00:16:49Z"
    mac: ENC[AES256_GCM,data:ibMahba4rx2Fp6N+gQE5gDrWooFwiSZDcludPzwZPqJTx2gmGODqR/zQAwe2Y2pJdjBwLMDC/SKqggMKtlijB6gcyOnI9o+Gc64NnSCeQISKaAuAsZqIiim7XX98zQeDJEpL8RPhEO8pVAYwa9W7YRTHQOAKya5/tuiGxP8S9v8=,iv:JD+4D/11vLcONlY5S5jOLJ+d554vvT+YYPD+/MPRSLA=,tag:gRe55vhdLVPVXD5hSUfn2Q==,type:str]
    version: 3.13.3
