apiVersion: v1
kind: Secret
metadata:
    name: glance-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:bR4XraD5LHkqPO8EVHTcHqzYKCiJZ859O/WMWgNqqbwBO9EtZA7AOs+GHJ37Kb0JX6QGNYzE+Ztk/uOnRMA0bPIzsoIyBSOspbze9KWX9lgsic2UhxymMlJBluVZJRDLLKRhzB+5HJwIz/qNymm1RwjKGqfF7JNn4Z2/KZlzd1kPwIU/QDTUkIyB0kUxRWUMrC6gE/9V+s1Qd7lQ7JKKxXq0wud0qwVqAHmnVYe81J02mhSyKT7NNGnRSBX1WhYTuhPU2fLbfLFHLKmBB6UeZYjd6HbU4nZu/SXo5aeW4trXdNk1nozBFwYOWauqiQ+QVhGZpFoJE0XE/Pdd+QmhjAa7avYNfzasecuL5nhVemdLwM+j6Moz99avI2lj1qn7P+tKhnXtYpYTgAfb18MJ1MiXqf79U0kQ/IjfrHX13OAo6Jx79Kd85/KYIJ3pxkT6TAWYxzyuPOYfhHffqFQVlVMZVmvcQplgwD0MA/HUhXcxik7aqz0/Wn+XsieEpYI+zZO4UMHkulwl29aoXUA2rEzlMKIO4tnmObZsOzMEqNXGbFxAXdoQn6xOW5xTrsYKOzhsdMRD3nggxIadHnzduScta4ZI6BLigzz1PPz+QPW6duP/YuFlI0a+lCPd8bP6wv/3nha4cvp2eauqeiAUaH1o9XOC980i6Xmspt6slNueP5rxRssiSt1lO9aoLVMhKEnb2f6wNV/yxO+KTu89uFsX6cCrLNSoP3il7lWgzyQBwX/iHC/TQOUG7CNR+/jc1EstL0jxDM1k8EOPS6Nnf2JFkay8oWCSD1ooBihNbNGFTBrNPgyYR7mZppWSU3LW81ukYsaUM9ON4iVO2HY80mQ/pYnbRogFPNhQKS1NpuWpK13k8QOGIoPTZD23SXOC/N1C6ag/R0F9HGAzDb8dyb47Ll51BrI9BEucqP0ew7L5EMEZelyGruUOsY+6eGe1RjsWY6kEAjj7FqkpOBG7IFkiiAq50uujAgaBTQkQtgrWHQtY+KaMIzqILPmqcEpat7uyrgWiYKACV9kxuQahEXqaBJNb9ys/y5zqCzudx1jF3E8ivw9N9rSFNScUlI0UkH1IOx1OWYNKY9BkZI9S0hbshyfNxUo=,iv:hvtpPweQRi7apwDAQxlyalwViLNeQoby6TEHYI6wJjw=,tag:IcD/ii4FdZyfMrd7CYERIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxT1RYSGFLOWR5TEc4VHla
            eStla0FGOEVZcXFpNVh3TFBxbEZzc2M1QWk4CjlHbXRPbUJ0VHFwcGwzL0dGWFJ5
            R2JVWHgrdXNldlNuNGhyM1dJNWVqdlUKLS0tIHBBOFVDZ1pLQTBFTU1ZblVDMzE2
            SWpzMERteEc1OU1rOVRvYXZwbFY2WDAKrOgGQNGrVEg7WiQQxTGtSyYkMmqSg7gv
            7Mu+yV5QUGEANrSqHUZFv9okMDgio+cwBb0t6zj4h8B6LWap5rj2GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUV0UvSmdDL3lNVW1zY0tz
            QUVDdDBYazFaeVpCU0RtYXQ3L0hoeU5pQkdrCng5RVh3NDRCdmlCVWhDTFVTeC9Q
            Y2p3VUFOWXgyK2paeEdIN2tYVGRYN0UKLS0tIDRUV0F0d2hTME80VXc3K0pZSTk5
            VzlmWGJtSmRHVVZsTXZwa1R3SERHVE0K/LAUHde/EyQpVL40pTjPjNEKzrxr54sp
            g9gtyXBHhwMPxPUjp8N9i1BebH3C/NHfz8uaNjB8XEVJ/1I4wqc2sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T16:08:50Z"
    mac: ENC[AES256_GCM,data:K3QvMOwo3CUadUvDcWO9cyiTQwJGTh5ZQK84IUIsgQeqQqRJC+i7ILxcYp+vUfP4/swm2LS/iZwoKIn4Oa5+KQ/cZgRGIHANM6yYPmLFqI6HmUfCTP8p1r1YIu4TkQKwr21bgJ7uiiX2+BdBS5O6T+pZ5GaZq7MWS6vDzKgGaTk=,iv:tUvjGmql5vXiWoDeLCyrbZldg34sGeRD7AsdIdQd7JQ=,tag:+DFkcYiMdL8E/NG/w+Q5aA==,type:str]
    version: 3.13.1
