apiVersion: v1
kind: Secret
metadata:
    name: glance-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml:
        endpoints:
            identity:
                auth:
                    admin:
                        password: ENC[AES256_GCM,data:cie7qRRVuGiBDDKBCBpqVYGep/w4XvTunjRaR7wDEw/KfuDjNK72AtgvO+IeOYOl8/zfpMqYE+D6Ikq9N8RYow==,iv:lq/GQ3n+c/CVoHguZ+ooytFasXFUsKYFcLvJASajqRc=,tag:d1VIsJIb0tK5tbNYhCfNQQ==,type:str]
                    glance:
                        password: ENC[AES256_GCM,data:y/dZ+3oQiDAyBkKP6lkZObcLbdze5R2lCeR/VzJAxO5qcDMRV5k7zoQ9qrLeTj65+IiIzUf2XDUEpCxlIpRKsw==,iv:hScqVVsKY/fAC4LMD/EX3L2QSfnmzjoj9uXssfDO4is=,tag:hoRoi3z4jBlk4IWhy8VqIQ==,type:str]
                    test:
                        password: ENC[AES256_GCM,data:BQ0rY77GR/TVapFIJqR2H8RZcfgEKZl+IFe0f9mV5X2YZCvClxCq6worVe6hJygagoLT9UEyK59Npd0/EHGXcg==,iv:eAj2kOrlU48sIMn23jazDYO5la3k+ABKdVVpAaxonhM=,tag:fga0Upw8FXe647VYoVVSCA==,type:str]
            oslo_db:
                auth:
                    admin:
                        password: ENC[AES256_GCM,data:gtX0iJ8zdXX/+vKsSLuBavErX5V+mHRi/49aPATxaXNpskgi+2RfYHAUe2e3jJIApN/ht51kX957Zb/khGvTRA==,iv:v6R7GAY5uxDJc5LJL17G20ANgXq+5dBbJKPwDUY230M=,tag:k2n+RUx2rLK+z4PLbbCKGg==,type:str]
                    glance:
                        password: ENC[AES256_GCM,data:s3Sy8mvKaLt3Ppy9ysG9pYOtsnJwFHUpyBmasCWMBl0NPpo1kCNEDhbui5gU4NUEZwWLPK3wd//fXWIW9IqUTA==,iv:tBS5b1p4zjzVbmICpZo3fQB5XRHleCJPNOuuIMLteZY=,tag:xLmasD8tqjNNVjcJf/zSXw==,type:str]
            oslo_cache:
                auth:
                    memcache_secret_key: ""
            oslo_messaging:
                auth:
                    admin:
                        username: ENC[AES256_GCM,data:8roeKmXufnQ=,iv:S+usfVpdfr8b7QfBGvH3k+ctg+1mIiKCYwp+dhrljUo=,tag:DsKEW3xM7u48CqoqSraJ1g==,type:str]
                        password: ENC[AES256_GCM,data:fAdomckyiLTPqoOSTHUQXYCgJa9mwa5Ks3PzpDkHi4HZm8hpbnYb0k9gqzh4zW2ZWGhsRmLKe+YmJCoFFSOSMA==,iv:CXKHy53ycM6AkQNNjA3hxKrdgeztK0QXrbjUzgk/eIo=,tag:qlV5VANaA0aXZSDbx6Qerw==,type:str]
                    glance:
                        password: ENC[AES256_GCM,data:AaSPy8C/eJWb2uOyt0DSRF8EJ5QK8tc72gob+cTEFRNUin2Blvv2dxJKZZZgjPbbJbA20/50yZNZD7UHaBi88g==,iv:J9RKyO4pkXzLxa77OByIgsndnEW2so4/cD4v1jdMQc8=,tag:XJt2nYnP6P+HOGIkcsUkyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxT1RYSGFLOWR5TEc4VHla
            eStla0FGOEVZcXFpNVh3TFBxbEZzc2M1QWk4CjlHbXRPbUJ0VHFwcGwzL0dGWFJ5
            R2JVWHgrdXNldlNuNGhyM1dJNWVqdlUKLS0tIHBBOFVDZ1pLQTBFTU1ZblVDMzE2
            SWpzMERteEc1OU1rOVRvYXZwbFY2WDAKrOgGQNGrVEg7WiQQxTGtSyYkMmqSg7gv
            7Mu+yV5QUGEANrSqHUZFv9okMDgio+cwBb0t6zj4h8B6LWap5rj2GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUV0UvSmdDL3lNVW1zY0tz
            QUVDdDBYazFaeVpCU0RtYXQ3L0hoeU5pQkdrCng5RVh3NDRCdmlCVWhDTFVTeC9Q
            Y2p3VUFOWXgyK2paeEdIN2tYVGRYN0UKLS0tIDRUV0F0d2hTME80VXc3K0pZSTk5
            VzlmWGJtSmRHVVZsTXZwa1R3SERHVE0K/LAUHde/EyQpVL40pTjPjNEKzrxr54sp
            g9gtyXBHhwMPxPUjp8N9i1BebH3C/NHfz8uaNjB8XEVJ/1I4wqc2sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T21:06:36Z"
    mac: ENC[AES256_GCM,data:6G48BkqcDPEPewN+siRseg7CrWWQIXN21xFtD9/FC5uTHPy34hKcU6GVB8xdi2qKqsuGlmVmpMNJ0NBleMSmH3sQBpARpjU5MhLTi5VMFqvW/09ftEYzXmF1W6d9sIk9inf1NQv2x6LOU+91KD5HTHekCbfkdX9abaqjy7GAmSQ=,iv:l6larvuZLlM7Erju/0Tw+VOiK8mUqLz9CO4i4QVDwfw=,tag:ZANuNx3WGKKliZ3ewOJ8mw==,type:str]
    version: 3.13.1
