apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:OtgSOx8=,iv:6QBdk+IEco4FKNqqLF/HWKY5QMLn1QP7Etd8NHCT030=,tag:+DXy3r4tY/o4oW88qZQdRA==,type:str]
    admin-password: ENC[AES256_GCM,data:G1/3uRpfpZgiDtHlV1FvhNfE7btxXxKqP0bCMYd8yyR1pZ4RQNqc2e7EbSqcvx10Hy/veMqtHxpqqjD+2vez2A==,iv:PMgQXVx6KxQaWBVyphlF1LodgyEQSFy3gSXeXSK2CaI=,tag:NcLEEiFf9dcnG/5Ka+2zgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZWNwNzM2ejZyK01GZjNG
            aFI5aG1WcE80ODg1VEpadFV2RFkyN1N2VHlvCnQvR2x0YXFWcEhTTEdyL3Rjck1p
            a24vZjl1NWhybWxta0R6cWE0VWgwbnMKLS0tIHlqMGppYTkrcDIrTEs2UjMzaFMx
            RUQwWkFNTjV5aVZBR2M3Z1BJT29oZE0KEEGa2hTMh6KM7Y1YiP4CtMybq6Sm0qLO
            pA8+a7KmlW7yyycvroYIo85JMM4EZoBewJgceBZEif4NhzdrRy8n9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOVFWQ2VKbWhWSkRCNHc4
            Ni9DL3RlbjlKdkMyZFFhWTJzVEI0NDlUeG5FCnluK3hpZ3ZpK2RzeU05dUJSbDNK
            ZmE3TmhjRzJuU2xySy90eHh5RkswTkEKLS0tIFovSWJDeXVjUWVrSTVNZU82SkpB
            Q1NmRVJybWVyeUpKK3kvSnZDaFBhVjQKXptD1CVx9AkTvhoAuSjosGQh0LqfbkOF
            /cfl7T6EZ+meZSXabFC95hf81XKiNcrQ0F0ISUHKefC4FxV+Jbg0bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T18:01:38Z"
    mac: ENC[AES256_GCM,data:/kZ3ci0ryoj2inbLGv2taYEO2RKerAfQwohuLVjF3tJiwvLX4cA+fJQtbjZNjTufzPOd2R/IP2eqkV5fk3H41VeBnU+tSog+IewIA+GTMMkEU5uNCSRQjPz9li7OhxX3qVjU5EqmwUN9jV/V20KBWjUVEK7vLav6EutVM3sgErI=,iv:zUklD3DLkI8uFYZZKvYxdfIaCCUOicXiKXRrVioV4/4=,tag:8vHekcYdPkOfVcd1a7SzVQ==,type:str]
    version: 3.13.1
