apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - grafana-admin-credentials.sops.yaml
  - grafana-oidc.sops.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
  - fluent-bit.yaml
