apiVersion: v1
kind: Secret
metadata:
    name: openai-admin
    namespace: tofu-system
type: Opaque
data:
    OPENAI_ADMIN_KEY: ENC[AES256_GCM,data:9Y7MwMZzJhEmlr1GZP8nkAVutRIzwkgFRSUJzeKGBy+hxnKd8bEeyWczanmCO3jsQ3s+QoKqR0w8eLDwpwYiHePFPIsOrZfoYsR0efU4gXZ+XBBmVhDjDRjry1qu+iSqfi7ELbpO828/hqT6dSbVGgzq/AKe3dje5cfYSrXldfKu2kdCTKTcO7xlOilGEUqRoeoXfnMaHLdKtggKgpLpAI8Lydew4zC5narFuCQE/Hjas1pk,iv:hYbcCWgwPGoN4WsssNSOB1AX8cTLZJnd0EmgwvrNCRI=,tag:dMO+GX6DfYdMkGwH2WTdnw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK3FwcWhocU9ZbE0wSXh1
            ZmpVQ2lXbDNCMDZjazc5WTVtQytUd0RCaDFzCmJERkY4K3RIa3FjVHdpeHFWNXd4
            b2R3eVJJeklQUzBKZG53T1RHcUpMdFEKLS0tIEpqbC9wUDRxc0EwR3ZPUVdLM3pm
            djQ4RnhCZTZXQ2krc3BUUHY5ZW84Wm8KXTUr0/4En9N87VenjW+1f1K4JXiZ9wTH
            pP1O7cnnCWaaCaTeAIuGWp1K4jDBwswBGLVcuqjGLytnUsINOxL9WA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aTlkMWdBaHBoS1Y1VFJ2
            ZVp0SXpIcmpqc055b2U2bC9lOXRXQm1PRXdJCml6bG40dXk1UzdOejhUa1lZL3BI
            REsrd251Q3FYVi9SYy9zQVhKWjJRMkUKLS0tIEpHc2U5dHA4Z0RrVjJjMzlPZjQ1
            blBQd3pySE9lUlJLMmUrNy9RcUpXWmMK4pkR/VQsIgmXczfrJMGD/2UzslFW5TkR
            dJk2HkIvN+mnccxWxSLXnZwIRZL9C9andaKfe9qXSQrgSMppy0X8Sw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T20:32:01Z"
    mac: ENC[AES256_GCM,data:uL6U1HHpiHP76krst83HkuGONjsrwjE2wMsKMg6rUTVlCrWE5ZEoCDSIsfuIKmdY1bQPGnVbiYEemACwtAWUdu7p0yO8Jf7zMqVKWUIQQjJg+v4ILg2BiDdJSc72XfAa/Wiv/979WRZkufpZs55IX4BXFCRpbH764uqWBF0zQ3g=,iv:bbLxTT41SkcV7dlIvZqZC32Y7d6wZFcUaEXJ//aObXs=,tag:IbK1f3lnisRFWzL2KKfpSA==,type:str]
    version: 3.13.3
