apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: openai-tofu-source
  namespace: tofu-system
spec:
  interval: 10m
  url: https://github.com/funforgiven/infra.git
  ref:
    branch: main
  verify:
    mode: HEAD
    secretRef:
      name: openai-tofu-signing-key
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: openai-hermes
  namespace: tofu-system
spec:
  interval: 10m
  retryInterval: 1m
  approvePlan: auto
  destroyResourcesOnDeletion: false
  path: ./components/cloud/services/openai/tofu
  sourceRef:
    kind: GitRepository
    name: openai-tofu-source
  runnerPodTemplate:
    spec:
      envFrom:
        - secretRef:
            name: openai-admin
  writeOutputsToSecret:
    name: openai-hermes-outputs
    outputs:
      - project_id
      - service_account_id
  remediation:
    retries: 3
