apiVersion: v1
kind: Secret
metadata:
    name: netbird-runtime
    namespace: netbird
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:adTTQjtcKw==,iv:ANG6yHzo0+298S+xtTaMY8xzsBOIutj6/s7Sn3g5T5s=,tag:ANuBXha4ZpW5EWZmJuEKrA==,type:str]
    password: ENC[AES256_GCM,data:OFgzoFc/NUX9mN1blSOw57F8G8/ZwySpJXhRXlftVjIn17b8KY3Da4i7kTKN57g1qIScLDUexhaCs/oMUnw1fA==,iv:XzAb9+L0vK97Pe8WAFJyVnSVEXS0Jxj7VPrbkrD5Q1g=,tag:RToIzQWvzxv5m7aAXNT31g==,type:str]
    config.yaml: ENC[AES256_GCM,data:1BeptDlme5rtxVJgZ5u8dePtRtxJq9/2Pp7U+QLwxFvbGdvrc+FD3p00ArjYNKvPpYgNpA7fafDzc1EMFBbPZP6kFNrUPDnRpsQN+ZSCm4Ql39WGBwaNGGrRlAxzV+LacBqYVbUg1O46vf9lQV/xcMTB9fOvLORq9h3kCKzq0Ac1kU4sY9kvRWerI3sQa1xuFev2JNAY/u9vCZeICAooklduVaTZ0ftKKNsOPQhUE7s2Mzzgr2GxW6pX/PIbqIqAWGT/oBWWE1lHW+pv9Tmv0NFMUJ6S5qFdsM4cielL37C6k3foESqFQAic81FAkMNW2EeNLhiC8eMCdpFix4+g3mj9+ewQ5rGpiCTHag7csbxOlFXIMcJOsud+rG0yjiYEjJf4JrnVu7Sk92Ig54vWK5nmJU1dBaUbAL36dO5rL04egpSKcFO9BVdjQN/ku7Jnpdd3EdDoeTkUtgPvCe6U69Bk0+Gib8YJbDNhVdBWqCU3JahRgrCRk3b4p5Ep01O6b44CA6Atfy3OZ3A5twJtOmLBG4YsqO6IppUxjo1ih9IKGw3vpNzZSiceeRcw/ATJzHbL5WsUT28f1KV1i7NpmGMjcSS4npvREoOIvrdacMNSpawZTuVqQrepTdb9H1w4/WhXfhOA3JUThwcjUoN8nK3TcXMInXY4cI2Mhq253blvLYvuxOrrQNEsWnT8XdyqblSXT8KQMUSrKnCEnQoQHOIkbgI2X97Q/Hk08+hYv9cSE5L/OpHvE0cVFsDwns+z1EdjuIgWI+tiQ8Gt2by6olWITh6TLQIGt92kl1/2MZ6EGX2YLvYCwzEtKDIbVKy3+rUpqGMiWkW7kRfovVx37i+yiOW2FDj9Va4Myxa0vjekADw2R1vzKuUZksgd7lDeQGb39/e2YZ7XQe30qXDmpA/DDgsoz0OJmgebbm4bdk/qR1YzEgXH9ebCJ8+drSLK/M21+MUapb5OiiF8U+u2MC3HvM9+e/D072Wm0aha4QXwedli89qXG+uk3QZiFtMhnsJDEJsrU2d/jPIiwwFiZSg34O9XXZtjMCeT9Houb/yemmMZAzta02lpkocUcezdlM1p20BwDy3fJBJ8YfmVJg6XwLzkgK6+Wd9AEijYJoKVHRTPbIq7RwlSG3Q5xrhyhqS5BfCDxBHHZQw/RRn4uZjjJomP1m+BZfwY65W+Y2+G3zRbujoo8ISLFUBy4pgazzes003Tq7B27JGfZmHCo1CL89p3oxhN/NBYgjDorZlnbUUw0E6cgkx+x7tz+fvoxcG85+QIXnYDPcNT7na7Y9KcqPohdhcAVid727mWTXNHXKVQeWQrMdGJ6V5Qfg9kNiCt5u1dfT+5/1CCcjh6UVBIVz1Rdn9NawQb5LJaBHnpYaSgjKsxBcri0rIBka3VAZX01JhvXy07mxhGngvE+FUswzft5XFeNtSZP2zliWHogcsjBS6onxrxkKbFCcoeJL1eskExmx6Pu63PqK77ifsobjLbOpVV/5JScsfqcw6BcUvvI/PpH1zcVW2/alcV8XnDSt0iGJHjZcvNrhnlHXWpDltEugtsmu/6S3ewSt+Z1qrOPg9Ii5WApAhjkWlpsLNiVuzVFeyCKTI5XDhSXg5XhQzvFhttAwLbq8Zv7TX5aOTQYzyx+uuEMCrtLLZJr/RhuTYrGKwpCOWgv3+aUvelqqIUw09/m3tl05cBjmnrZ5BUS7VGdxtxFfq7lAkSl7si5l5mPCmkQP/EjAG3y9z3eSE5iTbLz0nj0IjtsgL6HsDfjZBjv8Qm9IJBtin8vx+C+XbcX0Yd34tVmPtXBNrlECxKaAM6N446MziCgpPs+o+JWr1vFD+ziQGj0ClHP3LCOkG7RtBda16HFTACp8+Pt2As4zObIrCnlos52uvt/htTgdohJGBE7hP6aYDGWyzjPM8U5YXwrhP3sivsyT8Er/q9Uc1DrZjUUV1T7UasX455S2wXWJqmm9Bj4hRCNjIYo19yrCrbHLS174hJ8QFis/m72w==,iv:+3Qb8H4gcnFGnO2n1kTWeuJLQkfZD1Ax1K1SEDW5UnE=,tag:v8197Cn+M2G3RVKztIBN6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eFR5OHp1Q2xzWkZTejh2
            L2Z0TVJDZTY3dXRLVDlVQTk0YktnanpQamlBClpMMldCamZldlgxUWllTFZzeURs
            a3Z0azUyYVdwVHREOVpna3dPTmxRa1kKLS0tIGRYSnlYOTBXbGNEM08zL0VHeUNw
            NkprVWpaOSsvMHZDWExKV2xWeTdZTlUKQU1q8ZxN15Dv0OwTIgH3B/deum3pfU23
            cqWxUQ64QFR4bqqCAwIXVWnmUDBJpI85sqAjG7rpKmeXo0c/Tkn+XQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OWlUMnhJOU9FV2VsOG8y
            LzdMaC9CMFhReFd1bFk5bllpY04xZVRIVGhRClBvTmlNNHFTQzdmZWVTZXN3V1Zo
            MEZ1WDJHazhRWTFzM3UrK08zdERrbjAKLS0tIEU0bi9GOW1WNDRmUmMzMDB3Zndr
            NXcwVFVGTDJKaFVhZHBBeThKQlBCaGcKuxiYmxuGqXi15UywWYDznxJdyU8OYsPk
            1rVFiEPMo2co+yz7DtpW1kanzQdtfoD0WXC+FwqAXJjgf7MrlFBTuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vfxeaxdj7jze5p5ytff0peyjm3rusn8naacfudklvzwknv4yk5wq3qqg3v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T18:47:26Z"
    mac: ENC[AES256_GCM,data:2eQnb9a0h5AeU9vbWeiQJm3MS6K5RnsujAG33j/vzBSmuIYpbQUo6HxjvFwVi21P2RjwiqVkKHkTefYFhz7iJD0UkFjw6z+lTPvhkm16XshyjdehzIpIrJfVH5uQWJml8ZkmhUZnaH8auLm8uiNib0Dn+p39GeTpMQo4rghljPM=,iv:jXwrtaj7bktV0lbeWXP+pY1Fz+RFMam4xz5kg316ttE=,tag:Zgs66LztHTmdxCm6hUCT+Q==,type:str]
    version: 3.13.3
