apiVersion: v1
kind: Secret
metadata:
    name: netbird-runtime
    namespace: netbird
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:OiW2vJnbgw==,iv:UHRoloKng7UNqY1Yxi/zgvpSgzMs1EG3c5fnr6Nkp4o=,tag:WgsH6Q98U1G6uKau5HC5Nw==,type:str]
    password: ENC[AES256_GCM,data:2wN4ngivsq8QJF1Pz/Y/M/KFPTXRcCjlSCEMb/A+9XwDEQkGkkaMrmeFzXcnzPmJse+d6TFyVHuFp0siqrmSuw==,iv:N4Et2iZY3Z0lk5LHSHircmMqiexC0K3xp7Z5b6piS2s=,tag:kNEdn3um6SyNvcuYsII4hg==,type:str]
    config.yaml: ENC[AES256_GCM,data:1a7F2nGeOFOptg6Vj3/UHG+aaTvY8V6ot7Bkr2SIFyuH94flqD6h7VQ1WW/cl1eRVmAdqPM56JcMSjm6KgDKIzAr4aiSmG5uyIaOKKRQq/iEiLauV2beIWSKuRh7+4Rol56RYDNdQMPEGj2QtzmBplyljN80mQfOx3nOo1369MRfBclX4aqv2Ho17syUVvqVs0nw5ApAZkxeS0GiWjIWkFeFL0WjZqgB49OQ+SWwr9b317LZJwZq/8keuMshZYNPz1p1BLgF+GTxYsEN8swK3Q0Di+lz786li50NvjLfpYr/QmrRiDo/nfTUDzjWMYpI2SMY+dIfJMY3//XJmLB5wV0oHVOFO220Grb5ZHbQ1vrsF277ZiIkSqnMldiRBUkdKZs4nTQx/zf3Ixa4gKmr2I0kmg1hZkvaD+KwYJrgbN7YuCnHd5XDwXkmes6RO5jAHKOMdOKxsdqqCAOrnerqnLdLv/u9zCas6YN3GPhkcUjIX+kTlNIX65xcrA5tmN7xZnZLwqupMeeQ3SYQB4ajVa7dbrrGY93XalON06TjbBWB9roojQ7683sUxuIZe7V+uWMdNc8bhUCITJ9vEEP7ca0a1pWPS3OEMZXa5W+sh71YClx+TVJSqklB3IzTExXLhEyfexan5h/soMpNOgOhRbktnF+FGApf5U5JKhHmlwxLmd7EenDHgYhxN3ZC60ezZ57qjzOSKZf/UgzvNLrxCWWtAQPtHl3zPC+nmy1STQzaSzX/ILYvmLJt5bZ4lXzcQhcrlgleYwQsJ20214qMkYmTyS9YG1ROt3Fv3AWU7Y1GYcpDTYM0O06hm8J+ORcFqfKa62R/XEFQXbF2vy7tUrEUx0YBC1qdNBGVmDf4LncqHVuGVLNWZEI7ZpFWd4x99V5ZQrwUI0CRgfWuwmCbS17tDpdXHuCrcSnpgA3K+xlvUWQvc4NgY9Mj3mp2yHZvC/ud4UoXRfUwlpsPgvzz3i64fGwXyFEZMXmvWZJEtqW20DhopgxZnoHdvXLUhf/VcMRgw56PXcLyK9WcJ12/k+Ez1jVajseUIo1THnd5l2DkOELDc5YtRtFdv68JGrckme2k3HrUnjc0KReLJByiLu6Ow36B2vnUN1YTM+8Y85GMQMiSfVmkmt1efCyf68uptAFxUHwTn1wTRE3NwGd9ATQWgnGpmEyRKiWe3nK613nbaBveX8BZ15N3LsGcSemj8AchJs1w6MwalSjYzp2Pd6guCe/6h7PWFz6ouRfKDO/aWzwxzGqME5bwpkcscoP45lcmktcBsXzk7UBVeGb+DnX2ZGiumD7llUZ29PbK9TafbIkl3QQnm2CW15r0FkWy3/4j+GBtLvhiO9fH8kICN0hcHp9m3ZfPKFiJSs27xMTav0xQRLrjAmOpzSpkpxz/4hT1hfor0+D3t6XXy6UXVieFEUVbBNztB+tHZe42c/uxWbaKzettOexbWZgsptptISIV5rg8pChaXUhR1WbjnUDNyueMryceAi9qfNfI5dEHaXjKOEPcXYejsJ2cnyI4tH1TpxOJOMc0cC81vIXF4RWAGIaMYvUtf6PRR1GEoP+UXPh6QX1xEFBtxN9pHfZf480Me8TOD9I95qklxWfN1xJ4Ativn+dSfU1RK5kFssl4eBGXFqGgpFXh8vXToI46iYQqOAW9Pl8uZWp6zcMdazdaD4WBGOXpiFWW9GqUVe8wGhV0aXUxrVg78a1K+BrY8FowuRDTpa8/pI+ekKwsG8HantbXOt6dFjJAczmDH1WxzdJSV8PdGHvCfUol3TOMMaO5TGrBFiPcntmmi4FJPXxFkiCPLOmUmRTvHgs6lAK9dp4IuCMQrMnUIwdP3BsU5+7Aueo0Hr2+fsR61CGMFk42syAiQXH5IqXrJdxyDb0k5x+Ub2LfeQ+y9vyApS6EoTJ/1PbNZVbnkpKZrBRPag81oPvIlLBtemmD7gl2D2Sd/tCE3hfQU7Mvadew3SH83fGLT9ymI7FI+bsSkJs4qIv7bOYLb8M=,iv:ry5lGpIAEHRN91rPrvYHl4assrVMotkTiWgspmlVKhs=,tag:OgQDdR4KGcGVjBBgXeXwPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Y3h5Rldvc05YalkyeTlW
            dFQ4OWFTTEFjQ09WZUZ1QjZWbk5YMDBYZHpBCkVFbHV3N1dSbEFtNTlMbnVEUmRM
            bGZQUlNzZXc4eEJNdWg2ZVlqbjhIRGsKLS0tIE9hMVZhQkx3ZG5zUjR6b1I1Q1pG
            TzNRQ1N4NS80ZEp0d0lvNkpyRWRuRk0KX9/Ffow/kQIlMqvgwr49MqbcO6CtCSeN
            Ew2eSKCgYEH6cWnR1oAMtUUbNqEB5aFnpO9AlZZ4oI8mFdq8ttj2zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VHgxZm1pUzFhbWZoaHB5
            eTBQeVJ1MlZDMTdjSEQ5di9iTE5nQ2hhWTJFClRhU0hDeFZ3NnF3T0R4QTAyTG9O
            U3Fvb3V4L1lzVDBVbE1wWVFLZzRZVGcKLS0tIFJpRFJIZVpETEZpUkhjZW0wWTQ5
            dUQ4WkNoYllMSXJnUFY4TXlVUXdoQW8KunSOnOM7wzheEi1fizddOF2tniLVSp0z
            v71Drm52nhLXqCPvKk9+xdiMFfdFhfOC+bkJGmMWAyEkNKV8jTkDUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vfxeaxdj7jze5p5ytff0peyjm3rusn8naacfudklvzwknv4yk5wq3qqg3v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T17:47:27Z"
    mac: ENC[AES256_GCM,data:Kq5dQwxSzfyuMtw89W/StWLc5VtAkGoztR2Mj8KgXmIY5WDhwWs90zYEb82Gcx6vVIGsducj8Rf8cBGVmbFWuKFfghSc60+/v+BqPeA3W3JIXVF8dSg1jid4cGfR7ssw1z/Q7QQk3LdxXkO+EZTZQITWcdSl+GgT3S9PZbx9nQg=,iv:JgXXlvSDb5SSz+B2fuooe14jSrBMuxNj5HdLRSOgEX4=,tag:GT8MnGR9nPUmPinKbRTdtg==,type:str]
    version: 3.13.3
