apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitlab-chart
  namespace: gitlab
spec:
  interval: 24h
  url: https://gitlab.com/gitlab-org/charts/gitlab.git
  ref:
    commit: 24447d31f508f3ead076b1692539b059a82b6ee7
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 30m
  timeout: 30m
  releaseName: gitlab
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: gitlab-chart
      reconcileStrategy: Revision
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 0
  driftDetection:
    mode: enabled
  values:
    global:
      edition: ee
      gitlabVersion: 19.3.1
      hosts:
        domain: fahrican.com
        https: true
        gitlab:
          name: gitlab.fahrican.com
        registry:
          name: registry.fahrican.com
        kas:
          name: kas.fahrican.com
      ingress:
        enabled: false
        configureCertmanager: false
      gatewayApi:
        enabled: false
        installEnvoy: false
        configureCertmanager: false
      initialRootPassword:
        secret: gitlab-bootstrap
        key: root-password
      psql:
        host: 192.168.82.10
        port: 5432
        username: gitlab
        database: gitlabhq_production
        password:
          secret: gitlab-bootstrap
          key: postgres-password
        ci:
          databaseTasks: false
      redis:
        host: 192.168.82.10
        port: 6379
        auth:
          enabled: true
          secret: gitlab-bootstrap
          key: redis-password
      gitaly:
        enabled: false
        external:
        - name: default
          hostname: 192.168.82.10
          port: 8075
        authToken:
          secret: gitlab-bootstrap
          key: gitaly-token
      shell:
        port: 2222
        authToken:
          secret: gitlab-bootstrap
          key: shell-token
      time_zone: Europe/Istanbul
      appConfig:
        enableUsagePing: false
        defaultProjectsFeatures:
          visibilityLevel: private
        object_store:
          enabled: true
          proxy_download: true
          connection:
            secret: gitlab-object-storage
            key: connection
        omniauth:
          enabled: true
          allowSingleSignOn:
          - openid_connect
          blockAutoCreatedUsers: true
          autoLinkUser: []
          allowBypassTwoFactor: []
          providers:
          - secret: gitlab-oidc
            key: provider
        backups:
          bucket: gitlab-backups
          tmpBucket: gitlab-tmp
        lfs:
          enabled: true
          bucket: gitlab-lfs
          proxy_download: true
        artifacts:
          enabled: true
          bucket: gitlab-artifacts
          proxy_download: true
        uploads:
          enabled: true
          bucket: gitlab-uploads
          proxy_download: true
        packages:
          enabled: true
          bucket: gitlab-packages
          proxy_download: true
        externalDiffs:
          enabled: true
          bucket: gitlab-mr-diffs
          proxy_download: true
        terraformState:
          enabled: true
          bucket: gitlab-terraform-state
          proxy_download: true
        ciSecureFiles:
          enabled: true
          bucket: gitlab-ci-secure-files
          proxy_download: true
        dependencyProxy:
          enabled: true
          bucket: gitlab-dependency-proxy
          proxy_download: true
      email:
        from: gitlab@fahrican.com
        display_name: GitLab
        reply_to: gitlab@fahrican.com
      smtp:
        enabled: true
        address: smtp.resend.com
        port: 587
        user_name: resend
        password:
          secret: gitlab-smtp
          key: password
        domain: fahrican.com
        authentication: login
        starttls_auto: true
        openssl_verify_mode: peer
      registry:
        bucket: gitlab-registry
      batch:
        cronJob:
          apiVersion: batch/v1
    installCertmanager: false
    nginx-ingress:
      enabled: false
    nginx-ingress-geo:
      enabled: false
    prometheus:
      install: false
    gitlab-runner:
      install: false
    minio:
      enabled: false
    registry:
      replicaCount: 1
      hpa:
        minReplicas: 1
        maxReplicas: 1
      database:
        enabled: false
      storage:
        secret: gitlab-object-storage
        key: registry
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 768Mi
    gitlab:
      webservice:
        minReplicas: 1
        maxReplicas: 1
        workerProcesses: 2
        resources:
          requests:
            cpu: 500m
            memory: 2500Mi
          limits:
            memory: 4Gi
      sidekiq:
        minReplicas: 1
        maxReplicas: 1
        concurrency: 5
        resources:
          requests:
            cpu: 300m
            memory: 1Gi
          limits:
            memory: 2Gi
      gitlab-shell:
        minReplicas: 1
        maxReplicas: 1
      kas:
        minReplicas: 1
        maxReplicas: 1
      toolbox:
        replicas: 1
        resources:
          requests:
            cpu: 50m
            memory: 384Mi
          limits:
            memory: 1Gi
        backups:
          cron:
            enabled: true
            schedule: 15 0 * * *
            concurrencyPolicy: Forbid
            activeDeadlineSeconds: 7200
            persistence:
              enabled: true
              size: 100Gi
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 2Gi
            timeZone: Etc/UTC
          objectStorage:
            backend: s3
            config:
              secret: gitlab-object-storage
              key: s3cmd
  postRenderers:
  - kustomize:
      patches:
      - target:
          group: batch
          version: v1
          kind: CronJob
          name: gitlab-toolbox-backup
        patch: |
          - op: add
            path: /spec/jobTemplate/spec/template/spec/serviceAccountName
            value: gitlab-recovery
          - op: add
            path: /spec/jobTemplate/spec/template/spec/automountServiceAccountToken
            value: true
          - op: add
            path: /spec/jobTemplate/spec/template/spec/initContainers/-
            value:
              name: capture-recovery-secrets
              image: registry.k8s.io/kubectl:v1.35.4@sha256:e8bc9c71a813d90d5f7689fa57516b2aacd7a02bb9d70d3ab6664ed6d202fc10
              command:
                - /bin/sh
                - -ec
                - |
                  umask 077
                  kubectl --cache-dir=/recovery/cache -n gitlab get secrets -o json > /recovery/secrets.json
                  printf "%s_19.3.1-ee\n" "$(date -u +%s_%Y_%m_%d)" > /recovery/id
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
                runAsNonRoot: true
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  memory: 256Mi
              volumeMounts:
                - name: recovery
                  mountPath: /recovery
          - op: add
            path: /spec/jobTemplate/spec/template/spec/volumes/-
            value:
              name: recovery
              emptyDir:
                medium: Memory
                sizeLimit: 64Mi
          - op: add
            path: /spec/jobTemplate/spec/template/spec/containers/0/volumeMounts/-
            value:
              name: recovery
              mountPath: /recovery
          - op: replace
            path: /spec/jobTemplate/spec/template/spec/containers/0/args
            value:
              - /bin/bash
              - -ec
              - |
                set -euo pipefail
                cp /etc/gitlab/.s3cfg "$HOME/.s3cfg"
                id=$(cat /recovery/id)
                backup-utility -t "$id" --maximum-backups 7
                s3cmd put /recovery/secrets.json "s3://gitlab-backups/${id}_secrets.json" >/dev/null
                s3cmd put /recovery/id "s3://gitlab-backups/${id}_complete" >/dev/null
          - op: add
            path: /spec/jobTemplate/spec/template/metadata/labels/gitlab-backup
            value: 'true'
      images:
      - name: registry.gitlab.com/gitlab-org/build/cng/certificates
        newTag: v19.3.1
        digest: sha256:941d9c2622c1878d173e0145744cb9ad96efd9ac2a02d5bac4b22ce17ae82fb8
      - name: registry.gitlab.com/gitlab-org/build/cng/cfssl-self-sign
        newTag: v19.3.1
        digest: sha256:890245a541c2373280c8a907c230403a1247c61c2b4b7ab02fd7054c78d0639b
      - name: registry.gitlab.com/gitlab-org/build/cng/gitlab-base
        newTag: v19.3.1
        digest: sha256:8f1c2a33cfa5834af60ea44fb9be1e7500e8ba102eee0affd7403963b0f6391a
      - name: registry.gitlab.com/gitlab-org/build/cng/gitlab-container-registry
        newTag: v4.40.2-gitlab
        digest: sha256:f07e7b54cc1228cd4ac7b349bc00d231d06c3922f41012a8f9c50bab54c4c591
      - name: registry.gitlab.com/gitlab-org/build/cng/gitlab-exporter
        newTag: 16.9.0
        digest: sha256:fe9f9fc832a095de37f795e4a53e5425de626ea7b64190efe1c3e288cd7a3dcd
      - name: registry.gitlab.com/gitlab-org/build/cng/gitlab-kas
        newTag: v19.3.1
        digest: sha256:b3ce4507bd4f4b1eaccb2825ad158f79f5692c2f47b31b2bbe33c53e5acdbc97
      - name: registry.gitlab.com/gitlab-org/build/cng/gitlab-shell
        newTag: v14.56.1
        digest: sha256:a27a2e65e24bf7591e19a0583137b8ccb4828b0fac70bae94ba0bed492f126d4
      - name: registry.gitlab.com/gitlab-org/build/cng/gitlab-sidekiq-ee
        newTag: v19.3.1
        digest: sha256:40be351d42dac66dfe740da8af688aee39d8cc1f1351871062a6f8b77687ea10
      - name: registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ee
        newTag: v19.3.1
        digest: sha256:9bff4b6d337d6782289d9cc4aa02f6a0a230dc44a2e071f731c99eda3f768338
      - name: registry.gitlab.com/gitlab-org/build/cng/gitlab-webservice-ee
        newTag: v19.3.1
        digest: sha256:fff90daf8040131b071b715f723cb803a050fd7582ca8c5badc6264620e98816
      - name: registry.gitlab.com/gitlab-org/build/cng/gitlab-workhorse-ee
        newTag: v19.3.1
        digest: sha256:f380c9da2ca06310dcb748137b4425f33b73e1fd3e46de5167abb6c1d6dd170a
      - name: registry.gitlab.com/gitlab-org/build/cng/kubectl
        newTag: v19.3.1
        digest: sha256:f988746c511d16642ef37adae2ec4e710d2834813412b66029a3a938a5dfd879
