apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-gateway
  namespace: observability
spec:
  namespaceSelector:
    matchNames:
      - envoy-gateway-system
  selector:
    matchLabels:
      control-plane: envoy-gateway
  endpoints:
    - port: metrics
      interval: 30s
      relabelings:
        - targetLabel: cluster
          replacement: undercloud
