apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: gitlab
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
        container:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
      envoyService:
        type: LoadBalancer
        externalTrafficPolicy: Local
        patch:
          type: StrategicMerge
          value:
            spec:
              loadBalancerIP: 10.21.40.127
              loadBalancerSourceRanges:
                - 10.21.10.0/24
                - 10.21.91.0/24
                - 192.168.82.0/24
                - 10.21.40.129/32
                - 10.21.40.128/32
                - 10.21.40.154/32
                - 10.21.40.125/32
                - 10.21.40.126/32
      envoyPDB:
        minAvailable: 0
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: gitlab-envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: gitlab
    namespace: envoy-gateway-system
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab
  namespace: gitlab-network
spec:
  secretName: gitlab-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
  dnsNames:
    - gitlab.fahrican.com
    - registry.fahrican.com
    - kas.fahrican.com
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gitlab
  namespace: gitlab-network
spec:
  gatewayClassName: gitlab-envoy
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: gitlab-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway.fahrican.com/gitlab: allowed
    - name: gitlab-ssh
      protocol: TCP
      port: 2222
      allowedRoutes:
        kinds:
          - kind: TCPRoute
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway.fahrican.com/gitlab: allowed
