apiVersion: v1
kind: Secret
metadata:
    name: atollion-launcher
    namespace: forge-control
    labels:
        velero.io/exclude-from-backup: "true"
    annotations:
        forge.fahrican.com/atollion-token-owner: funforgiven
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:6H8AZwDe6b/6jgDtpbV9WIgVGk9JkI+qqE2mO7H5sbMEA7te8KnBOQ==,iv:EqoB9GOcVk2mWBUL6VYimOeLMhujHvZmgHeHrQZTe94=,tag:dgIR1ofioxaUjbMtAjPfRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNN3J4U1lDNHJoNitHbHA1
            MTRyd2dsSGJ4dHQwbGNBSHFmdkRRTkhsb0JRCjRBQlc4dGY1M2ViVHVEU05RdXhT
            SkZmS3VRV21lci9Ja0V5NVgvblpkSkEKLS0tIDJreUU3dmhOZU42ZUVPcyswZDJq
            WTZxamMxOXNuMTlIUXJuUkJ5VUx1SUUKE1ZxjQ4sqoE1RBAAs9c/HAgTRxa3cAbv
            lg/c3e2NA85UpCMoqBFdPXO1oBaopYWNDyfpYDV6zmapoL1aJh+lhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSzFQMlVFQ0l4RVdmbDFn
            MXZhNUlUV3pGb3JxSjZnRm42dE5Dak5FbFQwCklKQXFiSTg4S1ZrWGg3MnJXbmJS
            dGNpcUM3ZVlyR01wOHVmbGNkeUtEOVEKLS0tIGt3RkFRRnFvZmxoczhrazdhQ3Rq
            aW5IL2lmdjBYc3lOVVRWTXA3RVJBczAKWUcqGf7rIqzC21i5GwZyFFd/T2TtMK7M
            75GaMPsHeaTmCP71BmS9NqMC6pHfW/7fJusnkir/sWGWC5sjE5p/fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vfxeaxdj7jze5p5ytff0peyjm3rusn8naacfudklvzwknv4yk5wq3qqg3v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T14:42:25Z"
    mac: ENC[AES256_GCM,data:0/m0PO4xnPzHK2KPL9ZFuukYXUQ1eRmyh5zgCyYUkAmgKVe8u/GfBu6fqouye1fsnthubAEBydUv+EYy1D5/nld0z3N83eKZMzoart5QLk3uDWn4XWJF7X2qs/8slIB39MS8s9TGPv+JoYQHoMEGag83VMev2Z+tX7hBjy9DtSU=,iv:D3uykLLXaMV1O3brMH3/0NsEd0cMVaBZ6ZZgSvHwObI=,tag:L41jZ5R9jyxlJQUKPQ/6iw==,type:str]
    version: 3.13.3
