apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- storage.yaml
- workloads.yaml
- routes.yaml
- network-policy.yaml
- monitoring.yaml
- runtime.sops.yaml
- runners.yaml
- runner-qualification.sops.yaml
- runner-registry.sops.yaml
configMapGenerator:
- name: forge-bootstrap
  namespace: forge
  files:
  - run-service.sh
  - backup.py
  - render-forgejo.py
  - forgejo.ini
  - bootstrap-forgejo.sh
- name: forge-runner-bootstrap
  namespace: forge-ci
  files:
  - register-job.py
  - run-job.sh
  - runner.yaml
