apiVersion: v1
kind: Secret
metadata:
    name: native-windows-qualification
    namespace: forge-control
    annotations:
        forge.fahrican.com/cloud-credential-expires: "2027-09-06T06:39:05Z"
    labels:
        velero.io/exclude-from-backup: "true"
type: Opaque
stringData:
    forge-token: ENC[AES256_GCM,data:0l3G7V+s5vG5Ovocq6Zak6O4fUg9dmOpJVanqWnkL9g7nmPaWh5CYg==,iv:SeyZRavCwTru4jP5+Of13IzEHymK+M8/XHGHgWs02YU=,tag:ELmxEupk57wCrMdAq/L4BA==,type:str]
    cloud-credential.json: ENC[AES256_GCM,data:9VOOXxkySYfFML0XnT1TaE5WwALOoV6QBPZn2gTy9//+jbRsms8N9qJzvA4gpuS1rYBTmQD1Xdr1TSy/KWd2k12N9Wr0+WJbB4zI/xiDYbzLAbZ65/fgzfCuubsZNlrCD6HHhLm/9YPK8ZOkdZtSPS7mzl/I+etuY2wbM9cfKfc7y+plbhCte9I05KUYfg==,iv:3P88eYeW0dYeKc578Xr1+3TDgFinet3+sNDd7RmGX6I=,tag:fDM8rEsF01SE46q/ZUzZ2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dzhjNTJsZktzZzQ0bjVY
            ZVdGWXBLYVBaNmVGbXB6ckV0aFZLZkhzOUc4CndpTlc4bjdXUmdBQThRSlNua0cr
            VGtoSHBNUHk2K3dVa1FLQnVhL2UyTTAKLS0tIFVMVS83dmpOV0NDTEpnd3psRFI5
            RHBWUEZVQXpQeEFUUmNnSndQVjArTFUKBKTAJfDhAkPEGTfPhnqEhwPDOGTMLRm7
            ZUFjFUFR6oJMF20GxW1BxsYIcGO+Vp2IffyxRVvJEzw09+9tfbU5vA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcTQrbG9FQTBaYS9RYlg4
            UEY4MlAvNGt6Z1hia3o5TEt0ejRUUGJydGp3CnkwbHhyT1hMYzJkNloreTVPWDU3
            S09xVzFSLzBJeDZpM2NIWVFQTGhrREUKLS0tIENQeHlXODBNb0JORWdoWFJYbEVx
            UmxGZDlkOWdKcnE4c2VueUpBdnozL2sKBkaQQTKmVwbLeYN5KvhRmtnuyOXAYq19
            R6yoltg6rFrsEduCqZSUBOL5kcFAH45qV0I/KuOJ5Qa8zzknqq6vew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vfxeaxdj7jze5p5ytff0peyjm3rusn8naacfudklvzwknv4yk5wq3qqg3v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T06:39:05Z"
    mac: ENC[AES256_GCM,data:40TlYy4g/+Mvo+ufCqaKEB+ElY9nzyR9q72gkJRbJsWK6m5RmdHNh6LAi6XS/0IS1UBowk711Drv9O3L7kfUSqRmLOvNunenLUmKXmKhDe2Y/7tzGOum0zFQGdX9kbnBIIphyScUtILI28i/Y+dd8TljofbMDa+sjT0V2cgg2lY=,iv:4fYc1Hk0gIT4UlGEPJvJkgZKycZBfQn3HdknBV5iLzQ=,tag:B1oraguod68deuQmrWOE2A==,type:str]
    version: 3.13.3
