apiVersion: v1
kind: Secret
metadata:
    name: native-macos-qualification
    namespace: forge-control
    annotations:
        forge.fahrican.com/atollion-token-owner: funforgiven
    labels:
        velero.io/exclude-from-backup: "true"
type: Opaque
stringData:
    forge-token: ENC[AES256_GCM,data:ZrrAb3czmck1BDwzfX87/dLEZur14Sb//M+npTQoulgR3wjtuXD3YA==,iv:THF0WUQZDuwt8F2ztvQaTKxNfqHYPpPdzQGBw4StEws=,tag:QhezCGhCmXjkmM8+KU8Hbw==,type:str]
    ssh-key: ENC[AES256_GCM,data:H68bmc77RrqtFPMg958cBGSrcSynr7ZVjfmZMvT8ZGEus0KH80ujLCL+2L8ZgkT01Z1PB8OvOqi6ff/0p21hwc3DWRI6O4mSkJvyavjj0cgXPEjeNuhGbHZmyq+VUSVc39a0+BGsUznYuQY4sxAgaruxfBXMFTSdZHUjl9ZnmpcQe0590YkXrjGFt+z3z8CEJyYJznLqD6at5Z5iy/zmcLJwEgJmgaFYnsN2EhbtbA3x+6fnDvNuntd3uGGZUW1sK9Xq7uVh1pQTq83rLOa79IBtgdEfPG4rBXAtgNCQOal+Ev3pbWTQvuzIJufHPL59lNRC9XNAW7nDfKV0L0xE6nB5kl2PlCXzfmnMpOMBxES8pHJTMzJ/BE067S3bdI+VjksgNW+goG/3kTrYsNDZXHSiC8cM+KkX5ZXElTpaIs/pbQPYklZCXXCMeu9rooRRtQIlv7M7RSgGmkP0CU9v+MJDwEtdpTjMm00+ULWoqMfUWXucdicUZJ97u/ZSo9aYgEa93m7LwZiJSLSNUP8WQWZd69BAqDIP+mqiZBLdMmX7DNQ=,iv:MWeecyRXXNOiu8IqSppFckbyDnGDN1sBXPzqmqrsk+A=,tag:s4WdyFMLtf7k5QobSaov2g==,type:str]
    atollion-token: ENC[AES256_GCM,data:xyCel034Nr0Se1OMC7CCrdg2BttbhSHIMevJBFW2BLmy2EXjc69tmw==,iv:Y6pnHPIQCF0lyQS2Rlqped9KTMCxPFB5g8+aY2u/mjI=,tag:LoozSMxO6mQvAias7iqxiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbmpnSmtwM1lQZTdmSnFr
            alJ3L1V2d3RLelpWOXg2K005L3JWajZMR1hRCmJ5MStuMzhzTG4yajlZZ2pzRVNU
            VjFoSFREZE0yOGo2SWxldUFkZzlLR0kKLS0tIFZMSWxuS1BiMC9xSlNIcmt6bTdi
            aUx0WkNudUNpdkw5YjhrckF5MmRPa2cKtAHTANIjrjZfz4XDIhkw5X8278JY0s1i
            uL4KDsGRKwgaKXp3mS/JaJ2p+YSvZYepMl5Z8Ap7/Pf9GBEJMAJpCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTT05EK0NnZWExY1EyK1V1
            cjFlNW90MkJwd1l1N1R3aXdiK3ZtWUFCdDJzCnl4eG0vYkVYeG0zTVREeUNTMUpS
            eTlUK05qVTdxTk5vUXVhK29RdGM4OEkKLS0tIEpyTnBDWDBoL1BHSTRRZXN5LzR3
            TCtVbW5nNTNJRi9vZG92ZWVYeGdMR1kKGs3/zlDeVcEeZWFUn7H7R4TKgatUzoNA
            y86IgrVjAeOMSl5CEJtYAdGrUmF8f2KvfUcww2f8d25MsYIBB412gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vfxeaxdj7jze5p5ytff0peyjm3rusn8naacfudklvzwknv4yk5wq3qqg3v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T14:42:25Z"
    mac: ENC[AES256_GCM,data:cW/REdv/yx/DeY3sfOQrsjiCLHqI7LkPv2CFAmIOjP5870/O6NY/fiUee2ZyT8OeJxri7EUsWekUWyfYil1WAFt5FEvmFsSKPcxasdBpm0GJ669otVpDYSIqwMr8W8y4+o+W6KzN2/0zs4G9UClr1JB+B1js/B3T8JoFPJ4MhsU=,iv:X+Y7K7B5SefD/flBeqbmg76iszmNEzY/qTbUa4kEusE=,tag:layK6zirPhkWBKXTGcXMQg==,type:str]
    version: 3.13.3
