apiVersion: v1
kind: Secret
metadata:
    name: native-windows-qualification
    namespace: forge-control
    annotations:
        forge.fahrican.com/cloud-credential-expires: "2027-09-06T06:39:05Z"
    labels:
        velero.io/exclude-from-backup: "true"
type: Opaque
stringData:
    forge-token: ENC[AES256_GCM,data:UmPHwGvRXZVePJWvYqxXjF+YlG3oK1wtLJmJGhq4vpWEcAk6SoaYPA==,iv:cZ4D0uTlyrAzjzyN8v66G8znYahTse1Uqc47vmDsHJ4=,tag:k+mqCgY5S9I4zjODmgJJ4A==,type:str]
    cloud-credential.json: ENC[AES256_GCM,data:almqjZykh5Pj9hjnQFaqKAe1kTuw4ElwsxoOhLibAmZM7yNqEai09pM8McdamqaY0WNsF/n8OmnMoBBJsUdxPPhwSqogJree5pikz8CubxpQFHdxAnmPtYC9TomS//8FIwcoX7BlSePRkWATDAanrB4z/dYUQ4s2phf/GsRhbWzgzM0MU98x7gg7Zqislw==,iv:ON3fJybZeTxO08+dLki8KAB6LSB5XdhQMAbpTSgTm3I=,tag:n+NmhfJXeyGl4ntaOEqctg==,type:str]
    atollion-token: ENC[AES256_GCM,data:5inmo1cS9NhJ5f2bQ7BDv0BhvTqSMGJEApzD8N/JEhytkAkheEGB8w==,iv:8QW+IqH0fp1Rd3j4IJ/zhOSNCQvUrq7nvi3Q1oKN7wQ=,tag:oPy+P/lO7Uqto4pADXnT1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSkNrRXM5OTdTRTJTaVFT
            RGJjRlh5VUMrSy9MRTE1eENRTmpOM1o1VVdFCnVLeUF5MktlU09wYlVZdlZaSGtP
            Y1VLV1p4cCtjMFk3NjUvYmVveHk2dWcKLS0tIGswSUVNaGVYWEU2MDM0NmZ6c1lQ
            eXp4VmtwL2w2cEJEelhmYlRJM0NZdWMK7/RIAQiK+2B3a1ah4W/76TPBErQ1NDXA
            lR7ilJ1igAZvlBcqaRThJVda7vU/bXNuHnZDFIUqS0v16Blu3pNObg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WnRYelkyVklRT0xmQld5
            YkM4b29GclNDdGtZcjhyWkUyM29rbi94OVNnCklrQkJsb1BFWjVoV3pieUZOZDBy
            c3NUcW1vbXhhRVpCSmxIeUd4UndjVHMKLS0tIEZrMCtLSEVYVGV1TlJ1NVk3UkpV
            dTJKVTRPTzNmS0xLaDBpaUVSZ1BsOVkKle8MU3Tr6rI2yA3i1A/vLQqslAbZcRrd
            dx1IYgXjjylnbkhw+6ya9XIVGgTdWONgLfzSkCp4ljNYasC+BijyBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vfxeaxdj7jze5p5ytff0peyjm3rusn8naacfudklvzwknv4yk5wq3qqg3v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T14:24:02Z"
    mac: ENC[AES256_GCM,data:98mKfXh5oUe8/+yxGTlN75vU99uT9PJQyIySoa/7hv72U9ZE+h5joEpU28Y1bGrK0eQ1SoDqNv7/gKZLg2eoppbUJvMhrDPefnk8DZ4uRN/k4j477FaEcrgv+xRnKWndvK6xNVEye4xpCxO/AafD/IysHcrhkb8F69LzwNvGzJQ=,iv:HYRXOfkV7ew7VRSJx2T4JB/Wfzf9tJluWEyWKnP11sg=,tag:ZXkVcJ1vfOj2BqE8FyRiqw==,type:str]
    version: 3.13.3
