apiVersion: v1
kind: Secret
metadata:
    name: runner-atollion
    namespace: forge-ci
    labels:
        velero.io/exclude-from-backup: "true"
    annotations:
        forge.fahrican.com/atollion-token-owner: funforgiven
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:3QcNwLpJ/tAMbm+NIoEOogr2gOwzj0mb5zJux5341PrjqbRK79dGNw==,iv:PPxSNy8ulB8v1z7jW7mPkLuVAZa3mpYXk0Q4zNkG/z8=,tag:e9EMgJEXVi28wqkUaUYV8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYVlPdlhPcW5yL1JyWXl1
            blFQdUk5aTNYdHpNU1V4SDA2ejBaMnNTRzJvCjVUVWU3U3RWZHhwazFvcjM0Uk9D
            ZXkzTFJFQUdyUHdnZUNGbUxxMUtJVkkKLS0tIDlOSWtaOUtYWmZJQU50KzBVMS96
            VGZDM1NDS3FkeWF1M0VYdlovZTFJVDAK2tb8R1iJHOH8Tk1W1z3sitYQd5CleaPl
            AuVpMHj/H69CseLvOp8sy5PYTwO6SzDQlc7KqI3afRyid6aSMstYiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RmpOVWcxcU5GbEpwS3pI
            RTJMNjVNR0dTeWxOOEsyVFZOZktSU1Z5SlMwClFHQWs3a0lxSUpCZk5PaTBSR1pT
            ZHljRUZmL1BPa2NXeWVOclBzc2wvQkUKLS0tIFExTTJnRWM1ME9IN0NiVVI4akp0
            NGVmWWs1cWNXNlJpanBnejRBKzJpNk0KyocZdCTRBHK/hOY1xKKl1U+gmVf1Nlml
            FUyQxZNf9TejmiVbLS3IYtEB/npZGAxVajc6fqR0R25vnvggs/FNmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vfxeaxdj7jze5p5ytff0peyjm3rusn8naacfudklvzwknv4yk5wq3qqg3v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T14:42:25Z"
    mac: ENC[AES256_GCM,data:xRwagwcJ3gPcyjva+ConT2UP8HIujDJG/Pq4MazQnfttz20AQAzfFzxNRTD5yFj06tTfvxZocXxvyPdCOrDb6MvoaotjlR8VHg0jNR1BpvfviCqPZeUujX/2ArrlobVc4cjgKKUXoD6w9txEn4NlQGPSSW6XRw31PT4SqwT6zRY=,iv:Cr6cwOiK3L/EReZ6kJRAzed1v6pu7EuZ63yCl2PQtGM=,tag:exIFN/kt48HCwiT+1ZaoZw==,type:str]
    version: 3.13.3
