apiVersion: v1
kind: Secret
metadata:
    name: forge-runtime
    namespace: forge
    labels:
        velero.io/exclude-from-backup: "true"
type: Opaque
stringData:
    forgejo-secret-key: ENC[AES256_GCM,data:Ey+/prsIZNw1nn5LGXmjkcxR/0QDRRd9c5EFW9Q10AO482Fb0QLGIX64eZxu4VVqvjYKK2+xFBpPCltp5P7OQQ==,iv:M1Bu9KwtvF5chYLIvpZysjfl70fVgMecQ7i+PfULWqE=,tag:5N3VbNDUAbwpLcxtJW3FqA==,type:str]
    forgejo-internal-token: ENC[AES256_GCM,data:9pD59h7WbCnNzGyhPCjCjiuLSJug8B7uyCkmQ3ZA9K5b9q15nrsiPiPmCg4m8DQuaoxRcsLp6VAyZfrLuwzUsA==,iv:L4IjklBoT5oTj9lPi3pqUo0UPguvuzHK93ej/0XZZbc=,tag:3lbHGtQvAQnfPAfpQpDS6w==,type:str]
    forgejo-admin-password: ENC[AES256_GCM,data:Y8wW8zA5QRNGwndOvGvZcVPpvCmjAijW9rKHH0w3woyWWwEcYWSheLACtsFIHagM9kV97Sck3BX9tipGp3bO+g==,iv:YO1t0YhFeWBCa/OXAI7RctM4f2AeJNE0cbH/zcfeL/8=,tag:vWwI9kV6W5zRlHoLejWGVw==,type:str]
    forgejo-metrics-token: ENC[AES256_GCM,data:WPk7gRHrD3fyyxjrCln1Sq4Yi8OELuW9HV6I51ywKR7jjPDX4GlKi3XUUyfZBAmGECWIBhbR2mU33U+YM4S6RQ==,iv:6GxP7fe1PFteATLWCsD1Fo2AhEgtHB7QhC0vICtO3pY=,tag:9ABBW9Dq/nffN0IgmkArkQ==,type:str]
    forgejo-lfs-secret: ENC[AES256_GCM,data:2M8MtEeHtukw9NAxNuMgEzV3FQX7/WhsMyGEw9+xEdT17+YHKqhYClIb9Q==,iv:7wfk/nke+vYHAH42fVjuX9l3uhhjFHf+2f94k7eFjoU=,tag:DW3ejG5ozjMG1CME5w2hRg==,type:str]
    forgejo-oauth-secret: ENC[AES256_GCM,data:zIjHZTEaKELyaM24AOja2TrLph7lg+P48avbfFZKJyDdenhyA8uBHa3J+A==,iv:dvoYHNP7BqupKvlMRI0rp4C402BTyxlUX+kNxgEAZNI=,tag:jrj3tFQ7sEEP+yaueNWNPQ==,type:str]
    forgejo-oidc-client-id: ENC[AES256_GCM,data:EK7PLKBGmls1V+otu5G8jKbN,iv:/io0nyagkeD5L5u5YEc4InroxBXj1VGVVOaCp2q2KqI=,tag:WvuKJ5UPhfIyMFtAIBmwzA==,type:str]
    forgejo-oidc-client-secret: ENC[AES256_GCM,data:utPibjYRyWKYMSTVvOxiN7kN8rugiqBYZvQkQwqW2d+FQiuc4DTvzokRRt89vXoJ2zKXP9Y6FIFJygYUfwM6BQ==,iv:EraTqWJLjRpiyQ1/nB6/ld7y/2LnTtJXnO4v9uvtVl4=,tag:1NRMJPE9eva7M+2bvOd6bA==,type:str]
    forgejo-runner-password: ENC[AES256_GCM,data:B0PBoXbiThk309H7mNHVk1s85lwYOxAWr0E4NGqbDz38Q5ghVeumbCXf0CNfZ13t8c2bE684O6t10XuK+E2lmA==,iv:It8dzPqzd7QEGjY58VgRsRNkqamWmDqm/PMzs1yAfDE=,tag:8wJg+IKH1gV6cunfis+q3Q==,type:str]
data:
    FORGEJO_RESEND_API_KEY: ENC[AES256_GCM,data:IZE+Lai5nv2kIhJjWo0dqfC7/Dgts/N4WxMHHI+OkNd/GGGquXWLx+kGOQnWk66w,iv:TK9GhJF2MaTDdmK+73K8iC37trIGF+2TsMIg0ECzMPg=,tag:joqv581LI2Q5MPoh99jiAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MVJ6b2JUNU1pbENwc1Zp
            NlVNcXdEMmlEUTNySXhMaG8yTXNPRncvTVdVCjBVckViOFN5aXk4QjhITktZSGlS
            UTBZeTlNZEFYVzZveDQ4Zk9UemFjR2MKLS0tIHlFekJwUXU4S0FsazVJREczaTVt
            VG1YeUNpV2k5Mzh0OFMrRFhGL0pjMDAK8VaBbhaBgZV4Gx8gnW2/ccr/8Q37MazY
            UzeSJkpcF0c+pW63uuKZVLA8iHADoN8WJeP9dxazea1e3/I9g3yKtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMFdQMUxLbVk1Si9LdlR6
            d21WSUxqcU5PTTZUenhsM05aUzZ0U1ZQdXg0CksrRWJaZE8wdTNDYThtS25RRVpm
            dW43N3dpdFJValpDbEVsV0tzTk5wSVEKLS0tIHkwR2toSmJ1T2FBcjJqSzNobEdP
            emV3UTN0Y2FHODF4UUIzS29WSlhad2sKjFyhd5G9emUprZ3ggEC2yi7HZkcexHPc
            J8TzvpQKBr6AxgcVVRLeipmA6loO3z6tthwkcA05HPabao+mQM8zug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vfxeaxdj7jze5p5ytff0peyjm3rusn8naacfudklvzwknv4yk5wq3qqg3v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T00:08:03Z"
    mac: ENC[AES256_GCM,data:agoeEgmIQH1BN3vAVb6+KkpXWX+cSbuVL+MikFajNkvO4cXPFIzo3JZ9z9va2WFhCZNS0PvnZEmT5neR4twkJckQYt+DgzrQkdlmdVE+OFWw+Crej0iGIbs9WiE1RzMYbztwnOCKBa/IC6A9pVyo+/IwH0FRLMwKAbcSDvsRQmg=,iv:6LmzgeVcS0j2Cqk+MbQprAjP03fCn/zkiZVIEihy1pc=,tag:oTJ9FyQ86tujGt2aRPBOeQ==,type:str]
    version: 3.13.3
