apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: netbird
  labels:
    gateway.fahrican.com/services: allowed
    gateway.fahrican.com/matrix: allowed
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: netbird-routing
  labels:
    pod-security.kubernetes.io/enforce: privileged
