apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-origin-ca
  namespace: unifi
data:
  ca.crt: '-----BEGIN CERTIFICATE-----

    MIIEODCCAqCgAwIBAgIUMTgSyIt1WDRBpyMQ80DBecsbwVcwDQYJKoZIhvcNAQEL

    BQAwIjEgMB4GA1UEAwwXSG9tZWxhYiBVbmlGaSBvcmlnaW4gQ0EwHhcNMjYwOTI2

    MTkzOTAwWhcNMzYwOTIzMTkzOTAwWjAiMSAwHgYDVQQDDBdIb21lbGFiIFVuaUZp

    IG9yaWdpbiBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBALlmIJOQ

    6Fokp0joI1JTDBeJ4xW9flJJv6SaxU7dRBBP3XhpeUXYhzjJQEX+XGE+VW7RDJdF

    90W+EUz92lFrsAjY1MUuYFQxWjYaFbUpLCT6iSMtIRHMOuWIrBoK/FXEk7kuMyu+

    qp6JKvqYTeTzvOs7UEMHHtQPtukapEhRhDq6GSG4bVVDVSrQo42EBM1AXHm+A6n6

    n3f86VylzkwbgsYehf8knaG3C97JgvuFbwzbUNuhgIV3a32OUR+laOxrvZIyQv6g

    fmX9Afc2hql8jVC0d9en/D+jwMRC2vPsLKSuJQVAkCCSpGYTti7ObCYqC/ynTxkA

    GaaXnHR53Vm6C/qzHmA7mLOnu4X6eHudIu0nfDxIKoClxrgGLYOFd5BiGww/5YXj

    snMA8WNU/v/4J2MF8nAYyHIm3m21siPhA5UzV6SRyfXDlxIXk16LrgjJp2CTA72U

    Io7pwTfJj2/ZNFLTMvhj5qrX3gsJhe8oBZxCuIDnqg9qKKdd1IIYofTbGwIDAQAB

    o2YwZDAdBgNVHQ4EFgQURDSQ0E+9C4ObqMMG6Rq1qOF7hsswHwYDVR0jBBgwFoAU

    RDSQ0E+9C4ObqMMG6Rq1qOF7hsswEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8B

    Af8EBAMCAQYwDQYJKoZIhvcNAQELBQADggGBALjxfs4NtCwDfAMy5hLt7k7dXuPx

    8TretH4x4d73PStuOpEpCNhWusa5vc7Qy1qIHdaeRaE63kDPvRzEsV+ENWle/mGV

    ++0CIZjygx3FFO2KRMidtxxIAlCGW3lZcOw20yIIEqPQw8Q0Z2/p8CdwOeP0iVgH

    IiIbxWH4lH/8ZHFIFTByznD9AK9hm6q+kIzCBTxwWPPchWntBsS/SEvkF6HSEMvh

    hyLuY0ja9WpuGpwqJOihIquBfnBtQKhsPIIFQkbdygjzvXWyoCOTyGdL8jS4/GN2

    brJQ4tDczX4Oy3vTqz2HiMXUcqtFxZZ8uzpGcnZ5Zevu4T9XVUbc5ZXD9YDK6ESW

    PGSSGFTNVcUmKeY7YOraF9kcJUt/i2XKMpqKDKyPv92ZXRrGuksKwXX3bcd4LMRV

    6De4AEHLnPHPIlZ7m5QDiHPNH21cao3hdtvMAgIeXxvNUpBYBjMnUGsQNVOtO/ra

    3DXXOvlLRFzIiSrmXH7EKlOckLfTWVykcGjYow==

    -----END CERTIFICATE-----

    '
