apiVersion: v1
kind: Namespace
metadata:
  name: openstack
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.35
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.35
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.35
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: openstack-helm
  namespace: openstack
spec:
  interval: 24h
  url: https://opendev.org/openstack/openstack-helm.git
  ref:
    commit: ce8c7069bcba495e3df4cc6075dc6870472f6c14
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: openstack-ca
  namespace: openstack
spec:
  ca:
    secretName: openstack-infrastructure-secrets
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rabbitmq-server
  namespace: openstack
spec:
  minAvailable: 2
  selector:
    matchLabels:
      application: rabbitmq
      component: server
