apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-tofu-artifacts
  namespace: flux-system
spec:
  podSelector:
    matchLabels:
      app: source-controller
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: tofu-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: tofu-controller
      ports:
        - protocol: TCP
          port: 80
