apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wave30-management-backup
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 7h
  path: ./deployments/homelab/cloud/management/30-backup
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: batch/v1
      kind: CronJob
      name: management-etcd-backup
      namespace: management-backup
  healthCheckExprs:
    - apiVersion: batch/v1
      kind: CronJob
      current: has(status.lastSuccessfulTime)
      failed: "false"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wave35-management-private-dns
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 15m
  path: ./deployments/homelab/cloud/management/35-private-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: wave30-management-backup
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: coredns
      namespace: kube-system
    - apiVersion: batch/v1
      kind: Job
      name: management-private-dns-v2
      namespace: kube-system
