apiVersion: v1
kind: Secret
metadata:
    name: cinder-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:0daUPy4GN9c0hiGDOlrf9nLLbgDLkRSoS+TVtG7Tc8oVAcs/2u942WTCYkaEzFvdBTb3ajyvTfny2coIdmEUdYsVZt1DlphsIAPiXs95OVu7G5qA8SaJiwXCCoXncMETnMh6Ojneny07xrbVLWN2HnpnPI5nARlzPhWDmNzRlVPkoyK9jcEPdm/B0fdHTaxTqJdxW3TgVUL3AtL9IO9S8zovklqdSWjpFy2r0hrOmqi5EpJ16ILCxSs4rhfhgu7is5TIVw9MMxr4HQPxfmBhqtnCplR1IO+JtxfdkUfcdlUiG6XVev1Ab3YypXzvFszec95nUXvnk04SSSEOFbzOARYAPjNfAi7r32ZMxkvXOBDWR/ZwFX+UDUO8gMa9iEluReZrD2JMLqj18tMGMn6/8mwwpGfm4A+bLU2Ugi+4NbjH7aFFc8pv/XqPK9ynQ3Liw22fSrenooeWBOHdy1VhbAyP+jE/O4L0fQssiKZSca1Ph3SabSLf4wvJ75k55VZl2eqhlpm2H78nPOzvE8uuCV6tA5YgDfN8iyNw99yXzvp050ZTXgZW5No0BQS55omS1F+f7CER1x9EdXEk3K8VGmaZu2up2ejg3m86humaKdl7UPJgB3SKcc7yRMZV7mogbkaC6wfee/mKUyD04HrU7mXMonFQ+2yY/ZSvZn1DKGtYqJfR7dmcDA5gSnQ/zzuqmj4UYGFSB9veVhoEwIBwHWONeHyKfxeQyD/SSsDKTgNZnFQfmB5mpyLSwknSbq40W1XWbXkDWKaoVn+PFV08IrhawPvMDtqxp1rwdlHbfTi83dO4cHGzwgkthChn9AlJ/LMXwVz/lpGxb6eP7zNVg4W9wKu6d6K2c3q6pZlNH1gY3i/tDtQRhDzkENOdtjsqeQN8Nm9m1totNSN/8VbOSyOMPzZ3w2w0gph7GgXLfXORIharhNMYAPnaudw2gUtfwyzNeOE9qKOMyBdB02ZQtxjKfZbAE7bZHN2KTn/4uqVCQXllnK5848AQo1yk/u9iCJ2aTqOL3ttfIvhOBmXyd0T2KF436OeV53jLni8E6tcZGR14rvCxHMlHB7GKJ/B0IWL/9oCI/IeTlC8iUePr5Nyb2YXWpejSy9Z8VkGJtR+8wgpdJLPc6Gu1JSLcrR2mzpcg+FIOV0GSADNJlFUDaYScW05KidR1IKjLwrnZq3eOGp0EiMvlOXG37YKOSt64litoEy3ggjIIsmxA212hLjIOfDtMXJxtXf1zeCgYPzBH76hl+dGqKOe/W7C0Z6IE+Gu/DWa6WCcbyRXkV0nZg5lZoXN8JVZUAuGnWrw/dDkrI6gzSPbyCZvj9DS8qeLRhL9FoQ3z2nhCd4tS2imuBNVxSn3T9eRYuOADuhTqgKyFSR1w4c3RD7ZUXwVCCRPCxwKc1MFGmJVYcINBMdUlyhqZU8fMSLG1JlucuhEjJfIjoA/6Xw==,iv:4i+wtENHDrLrevvVoJOcDnS+RBlq8s715nsyni1AJw4=,tag:AJXZUHr2smSa3zNHtABGLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4akVHTHF5ck5nRlU0VjJQ
            YVV3UFYzc2pqMFZrVU1mOHpCNWdmOTA1cFYwCnNkYnEzS2ZVMTh4cXpnWkd4eEZE
            U1EwUnpDZ3puT3I5MmNHT1VqTm5iZlEKLS0tIGtIQjZsRzd0b3l1dmRXM3hwY0gr
            Wm04ckFCVW5FRzNPbWxaV1RabG84bXcKDEYYVx5ib4i+J9sJ1oZPnWivW2+OmC0R
            BVOoJAhjtxltYkbLzgplrN6xuyxdrQ5pZwT8p1cnVEGztJi8hUJFIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMzhPZmw0c2RGUGMyZFZR
            UytMSnFZSkVvNUlQU2E3N1ZGUlpLUjJaVVVvCm5FelNIMXFMQTU3Zno3bXcwTjZH
            bExrTVN6b3JybHBaMG44WGIvQUprcG8KLS0tICt5aCs1SnFuenFBUnBBZDBucXlO
            UmpzUGw3N1g1WWpzdlZQdlpHaGEyUk0KB4XgQgZnp5lxXnbW+QCjBERrUTRmJp+n
            xVHpD9QxOdVaZYgnVet86Tzp3maxXmxfZdfWYtAuXA++qpn1M5BX9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T00:01:03Z"
    mac: ENC[AES256_GCM,data:SwJMB4gE6814/MLqqdU84TghvrTbnUrzGSBQq7mR8CEI0XiZPtxA9dm4mswQVOpqcsbeBamr9TL7ky73uQqGFtEXHpzqrOpGP5jJTkZkqx0hfk4/8k03wIlwv/NmPI/EnU1xYhGgAblr01uqeVYaskpMxb7sipf8HVgxnUEEhxw=,iv:XOw7qdJg+uniRijBndt6NyLTiexS8wB3tHIv8bjcy+0=,tag:kYEkB2zq1AEFjs/XcRbKUw==,type:str]
    version: 3.13.3
