apiVersion: v1
kind: Secret
metadata:
    name: cinder-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:Y/aB4ZFTR1hA1Cmd4jfpuVAm96mW1K59Q3eYRK5Hfytd6ld8QA74T9mozFCEuVlt1vBLwgqSwqw2n3KPvz8F+nryx23NkZi9B4uEuz6RUjsB75XhWTuPgBEqvAN8MomxZDseEuARwUhICRaOX/OIYbzLapHhbfDyosViKJ1v5ktY3UDf3qGNGXmomEKO0pI1Le43vYjVCzg6xzO1bHuAGeX/Wwmv0eWrofTmEeJTtDH3M7x3KzqzyxErFJHkd6BFR7m1C7HjD4vUGCUR5nzBxBFiu6ZZWqNiIc9Ztrxnfb7Gh7qMLF99r8jM9dRRXEkqBYbOZnW7ljioOJXYBKWtl1m4bSsUe2L2KRc/O4BoOdb96W8rdLoa43owF7wPqh2vAAF3vO5CsHaBLxw/3aiG3OaaRAXZrlCjLleUNn9wFLfZ14ew0KN8RFV7GLU0wGYa70gV1cxc5wd8eh/3SSKKjzkSZFgsrlx9P8p1tQwn/IjLAk1erGVQt57/XU/+VQY/7Jlhuj0Sdal/jCYsRGEd0GdhAJ7mi68Mlz9LOlOCmGteJNYsra9YiJ+Eo1gNhSo/pwMKRfFsD2IkmYP+EallIZzWsNxuowu+qgbOksP8EXUuV5pfOa8uz56pFIDF5ryxaGA0MKcqJ6kxMoIbP4ca8dEtCl4GqKAOrN3wwu7Uj4jGT53G8Dp/VGxid6JKfohsjrYzJKuaVUX9Sy0rPWtkZYdz8y2hChzeKOPvC4GXDJGvcZyN7pPRQwtehFVmw6sRiKMW4TuZbhLIAXJbJAlnn3UFzPQ3kn8CuurHDXR7J1WZi0scVHMF5h4VpTL9nGZfFiIc8EQKJx1DUA3eB9Ldii0GWQvBNiZBFysTkKm7mLj+xc6pSh3ZvMAzf3Vmn1wdzvCwshDiQp7MLkHwI6F7w+GB0by0iRR6lPEP47N2c4F8qJZypC40mQV/OdHQX/9ybV7/m4PxoAfPlPeGzydaP/d317EJQS8R2Zhu0kFLE/ENFQrth52a7hebW/XNDR0d1VKgDFw46iUX08nnozkpBs/RAgXHycrpMNL5FspWYai69W4NYJei4Sbbcfgfkuo6L5vJaUp76fIUY3/kzvLHPE08nSE///kXcralmKXOt3KMW7+TtDrwOvS2v/5YQavE1P2gWNmo45OE93Fy8SYWeMRZ4gjGodDqYFuuah55EQGpENB4JIXNX7+cQQXyrHqXmj5Rxey8Ar6237KGoo/51yvc4BYpJt0CDxm7vwVjrzUacSnkdqfzg5DMlWsofcCU+dsGw3n3O+e/v8yvkUf+2DoBytAkqNSYe96rFPnb3EbmUmY78c96k+8=,iv:QMlvGdHiKdNWGUaXKIaco6wG3VIBh5Z7RiHkyFnWBpM=,tag:Ijny3tvEE6P6Cw5QlMUIxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVW44VkdrQW01S2lsb0ln
            YlhRV0ZkajdWeFFlUDYxMWNJK0VsVEVpQkFnCnJPSEtTRmxvYUpjd1pOc3FOeG9N
            amlOczJoNFFjMUZRckZJT0VHaXlnSVkKLS0tIFJ0RGRUWUFRemFncnRGVlRuREow
            UFU1L2p0Skl5RjFjNW9ZU2NXZEdRODAK/8n7Ex82fHEwG2FeniT3Y/KWimSSYnwl
            Ez8yhTj+ZS8ttgWtj+D52rf6MEeuW6IZ1gc7wRjuG8BwOEfIPaFmcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYVFRUDBHaVYrL2srYzlp
            cFZLeXVMR2xDVEVSZ3RLeTJaTnpCc0YvSVdVCklFdnErRVBxQzE1Qk1IZmp3RXdl
            MmliK2c0S21BTVpwNWtxWjBqRk1zRTgKLS0tIDV0dkJneHkzODUydGJXcDlYV0Fr
            QUVsY1ZZMFFqeTY3dGNObWpvblNSb1kKLgeoz1Xlh+lzIBT9h2Q3f96Cbwa1GfIE
            sJ8o6CDHYoagqA+WezW6svSAnL52mPacoeiGdpQpkluyUQyX2khYbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T22:03:27Z"
    mac: ENC[AES256_GCM,data:uq2NAj6hRsAOEYRkE8vcbvJ0Lbguy9VA88xBnkK9kw1ivVHukGRdTudaLUt9duXeHstkbNlPzjd6Utx8E/lPliJw+GWhzPZ7U3/7M8JkZQeYJA/7ZpC3G8P6xi/0fv7KJRVKwPZzJbKVfhxZw97NUsvbxLHbO6V4TTft5KomO6g=,iv:GosCGAt1GSSwUQ/R5h81g8F6xltq1N1fi1e5Q2b1/kQ=,tag:TkdxW4B5z7GuGzl8GKTq1A==,type:str]
    version: 3.13.1
