apiVersion: v1
kind: Secret
metadata:
    name: cinder-values
    namespace: openstack
    annotations:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:s9LkiBUVY6eo5LqyXkuKWfR4XTrmktx21wkhRCQJCiG8FCKgxImy196vBcGrhLrxo/t0yt/5+J+yNMMQx331BS/MKtDF8tVKJNQO9bukLsFQBK4VQYOolL7IYSlOvTw447v/Ulyg8GxqoD73FLfaNnSbg6zi5527t8cq/kUsM15JMLgKJbpfB8phJIwt/HDmZUaAppl1X9uqG7RPaLgioZ5DnPQpUdN7rqXD+qSL5qWpxfjt74/iQBhG7M166pam+HnuAFwU8MrywHONTSiHxYAESrI4Ho8AzfXuybyAqFNv2P8rY/zxNgDV7lcX0uNpzPREvlBZitCPuxO/H750PKUaI+lRNY+xbdop5s5XLDWT2u344yPnQF5beSb0wYNizdbBeh1Rlf3Um+dNYra6TgB1UalnAK2eyuDZulF3S6+4qdgrY2W76eJXtnFFUrst7tA02Tx9lXalSiegz5XsqVmXYP88dUVSxSo92GoJfHsBn9BirG7zm32o2nxZY3HzfIibImp0+scjxnF2IKBQBhiRVHU6k88juhWTE6HKj7kMkAG1rbmxQD+hyoeURJREUBWynmHdZ8QsYqjrQ+wfpbIjPzdkV8tTY2Z7dNJnsIcP5vpcfLpVnAuJ/zJVeOhrK7hPtrznJIH62DHCYijq3TRnpKm9EdGTn0YKDBx05QKJ6iP2OYY+g3E8eeeTTas61EN36JtKmkiyh51JK4xzOux/jQOp9UhggO3WU64aOWQOZH4Y2razOOooYxisrwFld6MxzuK4Z+19en+93c2ZHCVjOkfk/CvATEaHsU6itrHyuQL4dE+QPmjFj0OchGcyni+vuD8/j1O8km6pE6qS/c77dhi3DAntwTxD13Hl1z4+6ZB3T9NIu8b8cwcDHFDuoYdbGOZvKfv4ksPBYYk/tIE3C1iYegTQ3MxaEHxjRQaxVaDSGTAF7nb8uCE7d7IcxyFo2ZqqLhy+r72EYMyeOVbJUdXpE5zJiWoLyUY1eoT3ESg8mMW2deOQldhLEdVkKufwHrQQRfoUwn5oYCiPYTEiqPZUUMFu9Yg9NiGvT0PB2bLM2HeqEm/PtQYVyvbeBlXO4cYHkHr7MSZxdE9q+w3LQt2hGoMJcjucQ37/IoKPmCcd7EbyvU1Qh7Yxfg61A79cjKqY3Y9fbpOxE50ebnjMlOLKYGWU8Z3KRCKjQao7GxpMhrJDG/vYPovjvdn0vZsba5jr3FqQrnnfATyxbrUTIBm84xOlqbZiCCveM1AvhmYEa2tx90Mn+zTpUHAFDTLiAunjwwyYbCnRXT+W7fBPij8FLsuc+ev1ACtuzHE4D4xybhyt3rk=,iv:C+XHLuKdMu1IMfRFGFrg44yLcCS/ptMkylRcWRjmaPk=,tag:LYs/7RZi5yr8/xyrNd4tmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVW44VkdrQW01S2lsb0ln
            YlhRV0ZkajdWeFFlUDYxMWNJK0VsVEVpQkFnCnJPSEtTRmxvYUpjd1pOc3FOeG9N
            amlOczJoNFFjMUZRckZJT0VHaXlnSVkKLS0tIFJ0RGRUWUFRemFncnRGVlRuREow
            UFU1L2p0Skl5RjFjNW9ZU2NXZEdRODAK/8n7Ex82fHEwG2FeniT3Y/KWimSSYnwl
            Ez8yhTj+ZS8ttgWtj+D52rf6MEeuW6IZ1gc7wRjuG8BwOEfIPaFmcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xx2n9unst4zc02lt26fxez8hg9ke44hrwefm3c9w79fap29mpuqu26eea
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYVFRUDBHaVYrL2srYzlp
            cFZLeXVMR2xDVEVSZ3RLeTJaTnpCc0YvSVdVCklFdnErRVBxQzE1Qk1IZmp3RXdl
            MmliK2c0S21BTVpwNWtxWjBqRk1zRTgKLS0tIDV0dkJneHkzODUydGJXcDlYV0Fr
            QUVsY1ZZMFFqeTY3dGNObWpvblNSb1kKLgeoz1Xlh+lzIBT9h2Q3f96Cbwa1GfIE
            sJ8o6CDHYoagqA+WezW6svSAnL52mPacoeiGdpQpkluyUQyX2khYbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ep2ztjlquplkgts8kstufgcx9add4enwn2dzsy6s7euy2scvvksgwevv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T16:08:50Z"
    mac: ENC[AES256_GCM,data:+uSP9Kf3i8kj4svFXnsaWwtJXmGHVMmwpkiqz+NwvbX7/o8j/pfDWPuz1Aln+SPO/hosvpmB7nGGQXKSwdGFvI7wQ+1KkREfl5dXHB2KmKlgaF/OM+nk0qCwAqU1JR7eumMwdHm8/v7Yhgw7zvjgo/4R+YuBTiXmVSpH5hDABXA=,iv:boKGTHEvMKuYl8YkUIs7LILsoEM7XDzgc72LdE1bTI8=,tag:hAHFzhv9Q6ywZTS+6MfBWw==,type:str]
    version: 3.13.1
