apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab-controllers
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 30m
  path: ./deployments/homelab/cloud/gitlab/10-controllers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: cert-manager
    namespace: cert-manager
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: envoy-gateway
    namespace: envoy-gateway-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab-gateway
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 30m
  path: ./deployments/homelab/cloud/gitlab/20-gateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
  - name: gitlab-controllers
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab-storage
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 30m
  path: ./deployments/homelab/cloud/gitlab/25-storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
  - name: gitlab-gateway
  healthChecks:
  - apiVersion: batch/v1
    kind: Job
    name: gitlab-create-buckets-v1
    namespace: gitlab
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab-application
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 30m
  path: ./deployments/homelab/cloud/gitlab/30-application
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
  - name: gitlab-storage
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: gitlab
    namespace: gitlab
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab-security
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 30m
  path: ./deployments/homelab/cloud/gitlab/35-security
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
  - name: gitlab-application
  healthChecks:
  - apiVersion: batch/v1
    kind: Job
    name: gitlab-security-settings-v1
    namespace: gitlab
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab-access
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
  - name: gitlab-security
  interval: 10m
  path: ./deployments/homelab/cloud/gitlab/36-routes
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 30m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab-linux-runner
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 30m
  path: ./deployments/homelab/cloud/gitlab/40-runners
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
  - name: gitlab-access
  suspend: true
